mavlink/mavlink

- pymavlink/mavutil.py
Needed it to get mavutil.py to work properly.
> Fix failing import statement.

- message_definitions/v1.0/common.xml
Following https://github.com/PX4/Firmware/issues/1986.
> added MAV_DISTANCE_SENSOR_INFRARED to MAV_DISTANCE_SENSOR enum

- message_definitions/v1.0/common.xml
> added MAV_SENSOR_ORIENTATION enum

- message_definitions/v1.0/common.xml
Updated DISTANCE_SENSOR message info.
> updated DISTANCE_SENSOR info; fixed typo

- message_definitions/v1.0/common.xml
changed MAX for ROTATION_ROLL_315_PITCH_315_YAW_315
> MAV_SENSOR_ORIENTATION typo

- message_definitions/v1.0/common.xml
@LorenzMeier Found a do_flighttermination, which does the same thing as force disarm.
> Common: remove 21196

- message_definitions/v1.0/common.xml
@LorenzMeier @tumbili proposal for VTOL transition command and state message. Here to discuss. Is there maybe already another command around that would be suitable? Would you suggest to add this to PX4 messages first?
> VTOL transition command and VTOL state message

- message_definitions/v1.0/ASLUAV.xml
> ASLUAV: add new MAV_CMD and SENSORPOD_STATUS message

- message_definitions/v1.0/common.xml
Moved an ADS-B enum up a line so it comes before the float that it describes
> Moved an ADSB enum up a line

- message_definitions/v1.0/common.xml
Add Squawk code which is 4 octal codes that, when combined, correspond with this transponder list: https://en.wikipedia.org/wiki/Transponder_(aeronautics)
> ADSB_Vehicle: add uint16_t squawk

- message_definitions/v1.0/common.xml
Will need someone to confirm these changes, but getting responses seems to go fastest when I submit a PR instead of an issue, so here it is. I broke them up into individual commits so hopefully the non-contentious commits can get merged quickly. 1 & 4 might be wrong, 2 & 3 should be straight forward, and 5 might be contentious, so let's see what we get!
> Clarifications

- message_definitions/v1.0/common.xml
@priseborough @magicrub @tumbili This adds estimator and wind status to the generic message set.
> Added estimator and wind reports to generic message set

- message_definitions/v1.0/common.xml
common.xml: Added FENCE_ACTION_RTL as a possible fence breach action. This goes with ArduPilot PR https://github.com/ArduPilot/ardupilot/pull/4244
> common.xml: Added FENCE_ACTION_RTL as a possible fence breach action.

- message_definitions/v1.0/common.xml
change comment from milli to micro
> msg 'ALTITUDE.time_usec' comment said milliseconds

- pymavlink/generator/mavgen_c.py
Current windows builds are broken until we get this in...
> Fix packing for non-GNU (windows) compilers

- message_definitions/v1.0/ASLUAV.xml
Minor changes only, see commit messages.
> Small extensions to ASLUAV message set

- .gitignore
> ignore *.cproject for eclipse

- message_definitions/v1.0/common.xml
> Add GPS_FIX_TYPE enum

- doc/MAVLink2.md
add advice on MAVLink2 switching
> update MAVLink2 docs

- message_definitions/v1.0/common.xml
This adds a command to set the position of a landing gear.
@LorenzMeier please review.
> Add command for landing gear

- message_definitions/v1.0/matrixpilot.xml
To the mavlink maintainers:-
It's been a few years since we updated upstream our matrixpilot.xml message sets.
We hope to release a new version of [MatrixPilot](https://github.com/MatrixPilot/MatrixPilot) shortly and it would be good if these definitions could be in the master repository at that time.
Best wishes, Pete
Core Developer of MatrixPilot
> Update of matrixpilot.xml message definitions.

- message_definitions/v1.0/common.xml
Continuation of #681. Additional changes: cc5b567
I think this is good go merge. If there are more things coming up during implementation, we can iterate on that.
@DonLakeFlyer @julianoes @LorenzMeier
> Geofence & Rally Point definitions

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/minimal.xml
this merges all the recent XML changes from ArduPilot, including the enum tags and the recent message additions
> ArduPilot merge

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/uAvionix.xml
This allows GCS software to no longer use hardcoded code to intrepret these values
> Added bitmask attributes

- message_definitions/v1.0/common.xml
https://github.com/mavlink/qgroundcontrol/issues/4935
@DonLakeFlyer @WickedShell
> add MAV_LANDED_STATE_LANDING

- message_definitions/v1.0/common.xml
Also, add *flicker* mode to camera settings
> Move Set Camera mode to its own command

- message_definitions/v1.0/common.xml
> add circular area to geofence

- message_definitions/v1.0/common.xml
Required for https://github.com/PX4/Firmware/issues/6940.
@mhkabir @eyeam3 please review.
> UAVCAN node status message

- message_definitions/v1.0/common.xml
* Clarifying what to do with reserved values
* Clarify that a STORAGE_INFORMATION message is sent once formatting storage is completed.
> Better define reserved argument handling and response for Storage Formatting.

- message_definitions/v1.0/common.xml
This adds the protocol to lock the current auto white balance.
> message_definitions: add white balance lock

- message_definitions/v1.0/common.xml
Specify that you need to use the COMMAND_LONG's `target_component` to target a specific component's storage.
> Identify which component's storage is being targeted

- message_definitions/v1.0/common.xml
- scripts/format_xml.sh
Added fields to characterise altitude estimates and velocity estimates.
> Adding GPS meta data fields

- message_definitions/v1.0/common.xml
This mode differentiates a regular Image Capture mode allowing the camera controller to do further settings specific for surveys.
> Add image survey mode.

- .gitmodules
Fetching from https is more frendly to users behind proxy.
> modules: Fetch pymavlink using https

- message_definitions/v1.0/common.xml
> Obstacle Distance Message 

- message_definitions/v1.0/common.xml
@TSC21 it should address your concerns.
@julianoes is it okay?
> Update obstacle distance

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
This brings in the downstream changes that the ardupilot team did in the past months.
All of these changes are in the master branch of ardupilot. None are WIP
> ardupilot downstream changes

- message_definitions/v1.0/common.xml
Update to HIGH_LATENCY.
Overall goal is 50 bytes total as a Mavlink v1.0 packet (8 byte header).
@acfloria @sanderux @TSC21 @philipoe @DonLakeFlyer @envirover
> [WIP] HIGH_LATENCY2

- mavgenerate.py
- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/icarous.xml
- scripts/test.sh
Fixes and adds units attributes
Adds display="bitmask" attribute in some more bitmask fields
> More unit fixes

- message_definitions/v1.0/common.xml
> Add camera Mavlink type

- message_definitions/v1.0/common.xml
> MAV_AUTOPILOT: added AirRails autopilot entry

- message_definitions/v1.0/common.xml
> clarify the field description in obstacle_distance message

- message_definitions/v1.0/ASLUAV.xml
Modification of the ASLs power board messages for supporting the Sensesoar2_V1 power board
> [ASLUAV msg subset] update power board messages

- message_definitions/v1.0/ASLUAV.xml
modify ASLs battery management system messages
> [ASLUAV msg subset] update battery management system messages

- message_definitions/v1.0/common.xml
This is a rebased version of #667.
> ESTIMATOR msgs by James Goppert

- message_definitions/v1.0/common.xml
> add time_usec to odometry message

- message_definitions/v1.0/common.xml
This allows for example: https://github.com/ArduPilot/ardupilot/pull/6842
> common.xml: add MAV_SYS_STATUS_SENSOR_PROXIMITY

- message_definitions/v1.0/ASLUAV.xml
Add a stamped version of the commands to test the command handling system.
> Add stamped commands to ASLUAV

- message_definitions/v1.0/common.xml
- I found and existing typo
- on demand of @DonLakeFlyer I clarified the coordinate frame specification (https://github.com/mavlink/qgroundcontrol/pull/6608)
> [WIP] Orbit command iteration

- message_definitions/v1.0/ardupilotmega.xml
> Tag mag_cal_report orientation

- message_definitions/v1.0/common.xml
> Add a simple enum for POSITION_TARGET_TYPEMASK

- message_definitions/v1.0/common.xml
FYI @hamishwillee @LorenzMeier
> common: update PX4 link, whitespace cleanup

- message_definitions/v1.0/common.xml
https://github.com/ArduPilot/ardupilot/pull/9535
It allows users to change vertical speed in auto mission using DO_CHANGE_SPEED. Users can set param1 to 2 for changing climb speed and set param1 to 3 for changing descent speed.
> common: support changing vertical speed in DO_CHANGE_SPEED

- message_definitions/v1.0/common.xml
Introduction of UTM_GLOBAL_POSITION as discussed in https://github.com/mavlink/rfcs/pull/10.
> UTM_GLOBAL_POSITION message

- message_definitions/v1.0/ASLUAV.xml
fix: add timestamp to the ASLUAV SENS_ATMOS message
> add timestamp to the SENS_ATMOS message

- message_definitions/v1.0/common.xml
Make description of MISSIONPLANNER component more clear, as per https://github.com/mavlink/mavlink/pull/1028#discussion_r237363035
> Clarify MAV_COMP_ID_MISSIONPLANNER description

- message_definitions/v1.0/common.xml
A bunch of links moved. There are redirects, but fixing the link is better.
> Fix up links to protocol/microservices URLs

- .gitignore
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/uAvionix.xml
> Issue 1039 dialect errors

- message_definitions/v1.0/common.xml
Types listed were incorrect. This fixes them.
> common.xml: Correct types for geofence and rally points

- message_definitions/v1.0/common.xml
This field is useful when using distance sensors for collision prevention.
> extend distance_sensor message with field of view

- .travis.yml
> travis.yml: Add python 3.6 and 3.7 to CI

- message_definitions/v1.0/common.xml
Let's keep this PR focused on what it is doing. Removing the "WIP" state of these commands and messages as they are now in production environment and no longer WIP.
> Storage messages are no longer WIP

- message_definitions/v1.0/common.xml
Remove ambiguity from MAV_CMD_NAV_LAND
> Clarify MAV_CMD_NAV_LAND

- message_definitions/v1.0/common.xml
This pulls the difficult part of #917 into its own PR for separate discussion. Details about why this is needed in https://github.com/mavlink/mavlink/pull/917#discussion_r216565966 and https://github.com/mavlink/mavlink/pull/917/files#r244725533
> DISTANCE_SENSOR message: Fix covariance field

- doc/mavlink_gitbook.py
Restructure to highlight difference between common and dialects - as per https://github.com/mavlink/mavlink-devguide/pull/166
> Improve common/dialect intro

- message_definitions/v1.0/common.xml
> DISTANCE_SENSOR: covariance field invalid unused value

- message_definitions/v1.0/common.xml
as per @rmackay9's [post](https://github.com/ArduPilot/ardupilot/issues/10803)
> common.xml: change NAV_SET_YAW_SPEED parameter attributes

- message_definitions/v1.0/common.xml
> common.xml: Fix typo "sixth bit"

- message_definitions/v1.0/common.xml
This integrates the changes in #926 (Add new PWM output message) - I was unable to rebase cleanly.
Dev meeting agreed to merge
> Add Actuator output message

- message_definitions/v1.0/common.xml
Exploring ideas for link monitoring and congestion control at the Mavlink level.
https://github.com/PX4/Firmware/issues/11674
> [WIP]: mavlink link status

- message_definitions/v1.0/common.xml
LINK_NODE_STATUS update units from description to units attribute
> LINK_NODE_STATUS - update units

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
> Move FENCE_STATUS to common

- message_definitions/v1.0/minimal.xml
This is just docs clarifications that went into common, being moved back into minimal.xml.
> Make subset of items in minimal.xml match common.xml

- message_definitions/v1.0/common.xml
Set display="bitmask" for flags field.
> common.xml CAMERA_INFORMATION

- message_definitions/v1.0/common.xml
increment_f allows negative values
also clarified some of the other fields
> msg_obstacle_distance: increment_f allows negative values

- message_definitions/v1.0/common.xml
Fix issue approved without sufficient discussion in https://github.com/mavlink/mavlink/pull/1211
> OBSTACLE_DISTANCE.distances relative to local not body

- message_definitions/v1.0/common.xml
> CAMERA_INFORMATION - url must support mavftp

- message_definitions/v1.0/common.xml
This should resolve issues brought up in https://github.com/mavlink/mavlink/pull/1211
@hamishwillee @magicrub @mrivi
> Add extension to OBSTACLE_DISTANCE specifying MAV_FRAME

- message_definitions/v1.0/common.xml
Follows on from #1205
Just a wording change. No meaning alters.
> common.xml: Tidy IMU temp description

- message_definitions/v1.0/common.xml
Apologies. This should have been WIP until first implementation, and needs some changes.
As this went in only on Friday I'm making changes in breaking way. 
- Mark as WIP
- Include array length
- Shrink array to more realistic length to allow extension if needed. 
- indicate end of tune in char array
- Mark as WIP
> PLAY_TUNE_V2 SUPPORTED_TUNES - WIP and minor fixes

- message_definitions/v1.0/common.xml
> PLAY_TUNE_V2: Fix size below 255

- examples/linux/README.md
QGroundControl 3.5.5 still waiting for vehicle connection even heartbeat received.
> examples: Update linux example README.md

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/minimal.xml
Reserved component id for pairing-manager.
Pairing manager handles pairing (exchange of communication and secutrity parameters) of vehicle and ground control station.
> Add Pairing Manager component id

- message_definitions/v1.0/common.xml
bitmask exist in SUPPORTED_TUNES but not in PLAY_TUNE_V2
> common: Add missing bitmask in PLAY_TUNE_V2

- message_definitions/v1.0/common.xml
A better solution has been proposed and merged in https://github.com/mavlink/mavlink/pull/1295.
> Remove STATUSTEXT_LONG (unused)

- message_definitions/v1.0/common.xml
This fixes some terminology in the trajectory interface and removes WIP (as these are now in production use).
@jkflying Can you please carefully review these messages to confirm that they do actually reflect our expectation.
FYI @auturgy @julianoes
> Trajectory message fix and remove wip

- message_definitions/v1.0/common.xml
The description for some fields were a bit misleading
and more precise information was missing in some.
> common.xml: Clarify some OpenDroneID fields

- message_definitions/v1.0/common.xml
this can help decoders to decide to look for exact value, or mix of bits
> adding bitmask="true" for enums

- message_definitions/v1.0/common.xml
> common.xml: Added lat, lon alt labels

- message_definitions/v1.0/ardupilotmega.xml
Please do not squash before merging. Just "rebase and merge", it better preserves history.
And the commit messages are very clean anyways.
> Ardupilot downstream 20200401

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/minimal.xml
the title says it
takes up https://github.com/mavlink/mavlink/pull/1176#discussion_r302010705
> Deprecate MAV_CMD_REQUEST_* in favor of MAV_CMD_REQUEST_MESSAGE

- message_definitions/v1.0/common.xml
Fixed XML to apply schema rules
Fixed typo 'True' to 'true'
Removed 'wip' element from messgaes that are depricated. both element can't be together
> Fixe Common.xml to be valid to schema

- message_definitions/v1.0/common.xml
Addresses issue #1288 by replacing the impossible pseudo-code encoding description with c code. Credit to olliw42 for helping formulate it.
> Comment Revision for Firmware Versions

- message_definitions/v1.0/common.xml
Adding a yaw angle to CMD_DO_SET_HOME. Implementation for PX4 already done: https://github.com/PX4/Firmware/pull/14810
> Added yaw to CMD_DO_SET_HOME

- message_definitions/v1.0/common.xml
I had not thought of that one before.
> failure_injection: add airspeed sensor to list

- .travis.yml
This also serves as an attempt to fix https://github.com/mavlink/mavlink/issues/1404.
> Travis CI: set virtual build environment to Ubuntu Focal 20.04

- message_definitions/v1.0/common.xml
does https://github.com/mavlink/mavlink/issues/1345
> replace MAV_COMP_ID_USER44 with MAV_COMP_ID_RADIO

- message_definitions/v1.0/common.xml
I am unsure of these and did not look at the implementation to validate it.
> Add missing parameter attributes to MAV_CMD commands (reach 100% documentation)

- message_definitions/v1.0/common.xml
> common.xml: Add new Open Drone ID fields for classification

- message_definitions/v1.0/common.xml
HIGH_LATENCY2 WIP issue is closed
Ref: https://github.com/mavlink/mavlink/issues/831#issuecomment-490351685
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
> common: HIGH_LATENCY2 is not in WIP anymore

- message_definitions/v1.0/common.xml
does https://github.com/mavlink/mavlink/issues/1372
> add estimator_status and landed_state fields to AUTOPILOT_STATE_FOR_GD

- message_definitions/v1.0/common.xml
does https://github.com/mavlink/mavlink/issues/1371
> add taget IDs to GIMBAL_DEVICE_ATTITUDE_STATUS

- message_definitions/v1.0/common.xml
As discussed on the issue https://github.com/mavlink/mavlink/issues/1411
> Updates to GENERATOR_STATUS message

- message_definitions/v1.0/common.xml
Clarifications of MAV_CMD_DO_PARACHUTE - FYI @auturgy @JonasVautherin
> common.xml: Clarify MAV_CMD_DO_PARACHUTE

- message_definitions/v1.0/common.xml
Moved the image tracking work that started within the gimbal api to the camera api while adding missing messages and commands.
> Image tracking

- message_definitions/v1.0/common.xml
Some users have this in production now.
> common.xml: remove wip status from GENERATOR_STATUS message

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
I kept the API the same for backwards compatibility, but I did adjust the descriptions a little bit to make them a bit more clear and concise.
> Move winch and gripper commands from ardupilotmega to common

- component_information/parameter.schema.json
> COMP_METADATA_TYPE_PARAMETER: Update to indexed name support

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
https://github.com/mavlink/qgroundcontrol/issues/8142
> move MAV_CMD_FIXED_MAG_CAL_YAW ardupilotmega -> common

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
> EFI_STATUS move ardupilotmega -> common

- message_definitions/v1.0/common.xml
> Correctly order MAV_CMD_REQUEST_PROTOCOL_VERSION

- message_definitions/v1.0/common.xml
Otherwise the compiler complains.
> gimbal: use char array for strings

- message_definitions/v1.0/common.xml
Requested by @auturgy in this discussion: https://github.com/mavlink/mavlink/pull/1504#issuecomment-705331912
> Add WIP:  back to the COMMAND_ACK extension fields

- message_definitions/v1.0/common.xml
Taken from https://github.com/ArduPilot/mavlink/pull/107
mbar == hPa but is SI unit !
> common: Change mbar to hPa.

- message_definitions/v1.0/common.xml
I think this is what the instance attribute is for, adds it to some more messages, especially the gimbal v2 messages.
There might be few more places there this should have been added; I've done it just where I was kind of sure it's what it should be :)
> Add instance=true to some messages

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
We'll be bringing autotune capabilities to PX4 as well, so to avoid fragmentation I'd like to bring this message to common.
> Move MAV_CMD_DO_AUTOTUNE_ENABLE to common

- .github/workflows/test.yml
add github action since travis shutdown open source support.
> .github: add github action for mavlink

- message_definitions/v1.0/all.xml
- message_definitions/v1.0/python_array_test.xml
- message_definitions/v1.0/test.xml
The numbers shouldn't matter for the test.
I chose these numbers at random; perhaps we should give it a bit more thought.
Replaced #1547
>  Add tests into non-conflicting number spaces; add to all.xml

- message_definitions/v1.0/ASLUAV.xml
This PR udpates the ASLUAV dialect including the two messages
- `SATCOM_LINK_STATUS`: monitor the satcom link status
- `SENSOR_AIRFLOW_ANGLES`: mavlink message for airflow angle sensors 
@acfloria FYI
> Update ASL dialect

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
My bad, the previous version was a misunderstanding on my part.
> Spray moveback

- message_definitions/v1.0/common.xml
somewhat embarrassing but my previous method of using mavgen to find enums which do not have a value field didn't tracked these ones here
hence a 3rd PR along this line :(
> Specify enum values explicitely III

- message_definitions/v1.0/minimal.xml
Addresses: https://github.com/mavlink/mavlink/issues/1589
> minimal.xml: add MAV_TYPE and MAV_COMPONENT entries for Battery

- message_definitions/v1.0/ardupilotmega.xml
Only changes ardupilotmega and has been merged downstream here, https://github.com/ArduPilot/mavlink/pull/196
@amilcarlucas
> ardupilotmega.xml: Vision_Position_Delta add unit to angle_delta and clarify frame descriptions

- doc/mavlink_gitbook.py
> mavlink_gitbook.py - note 5 levels of nesting allowed

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
Added WiFi network info message and enum for WiFi network security types.
> common.xml: added WiFi network info message

- message_definitions/v1.0/common.xml
From https://github.com/mavlink/rfcs/pull/14 (yes it's been a while).
Implemetation for PX4: https://github.com/PX4/PX4-Autopilot/pull/16293
> add messages for events interface

- scripts/update_c_library.sh
Autoquad.xml was removed from library in another PR.
> update_c_library script - remove autoquad generation

- message_definitions/v1.0/minimal.xml
We need to be able to address differently to all the component from the onboard computer
> adding new onboard computer component ids

- message_definitions/v1.0/uAvionix.xml
Jesse Walters (jesse@uavionix.com) said that @magicrub can updating.
> Add bitmask attribute to several enumerations

- doc/mavlink_gitbook.py
This attempts to address confusion around use off all.xml. I've also taken the time to explain external dialects and clear up the meaning of standard, common, minimal. That's a bit aspirational.
> Update explanation of all.xml and dialects

- message_definitions/v1.0/common.xml
RAW_RPM message has implementations in ArduPilot and is expected to be implemented in PX4 at some point. 
Agreed in https://github.com/mavlink/mavlink/wiki/20210901-Dev-Meeting
> RAW_RPM - remove WIP tagging

- message_definitions/v1.0/ardupilotmega.xml
This PR syncs the upstream version to the ArduPilot downstream.
@amilcarlucas @auturgy
> ardupilotmega: Sync to ArduPilot downstream 28-SEPT-2021

- external/dialects/storm32.xml
> Update STorM32.xml external dialect

- message_definitions/v1.0/common.xml
These messages are supported in released builds. Agreed WIP can be removed in dev call [20211013](https://github.com/mavlink/mavlink/wiki/20211013-Dev-Meeting)
> MAV_CMD_SET_CAMERA_ZOOM and MAV_CMD_SET_CAMERA_FOCUS - remove WIP

- message_definitions/v1.0/minimal.xml
This allocates MAV_AUTOPILOT number 20 for our flight controller.
> Add MAV_AUTOPILOT_REFLEX.

- message_definitions/v1.0/common.xml
Proposed enums for HIL_SENSOR and HIGHRES_IMU, as discussed in #1641.
> Added enums HIGHRES_IMU_UPDATED_FLAGS and HIL_SENSOR_UPDATED_FLAGS

- message_definitions/v1.0/common.xml
Split off from https://github.com/mavlink/mavlink/pull/1729
> add actuator test and configuration commands

- message_definitions/v1.0/common.xml
See https://github.com/mavlink/mavlink/pull/1744
> Remove backticks - these do not render as a style so not helpful

- message_definitions/v1.0/common.xml
> GIMBAL_DEVICE_FLAGS_NEUTRAL - note that this can be any angle

- message_definitions/v1.0/ardupilotmega.xml
This syncs the changes to ArduPilotmega downstream.
@auturgy @peterbarker
> ardupilotmega: Sync to ArduPilot downstream 10-JAN-2022

- examples/linux/README.md
This is part of updating #1778
> Update mavlink_udp.c example readme to use mavlink 2

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/minimal.xml
- https://github.com/ArduPilot/mavlink/pull/244
> common: added MAV_CMD_CAN_FORWARD and CAN_FRAME

- component_information/actuators.schema.json
QGC implementation: https://github.com/mavlink/qgroundcontrol/pull/10168
> actuators.schema.json: add optional title and help url

- message_definitions/v1.0/common.xml
And change "current" to "current ... data" to make that clearer.
> PREFLIGHT_STORAGE: use lowercase, don't shout

- message_definitions/v1.0/AVSSUAS.xml
1,deleted some obsolete command
2,added 2 enum data
3,added 3 new message for avss drone
4,modified AVSS_PRS_SYS_STATUS
> AVSS dialect version 2

- message_definitions/v1.0/common.xml
> add enums for mavlink ftp service

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
Added figure eight MAV_CMD to command a figure eight loitering pattern and its related figure eight execution feedback message.
> Figure eight MAV_CMD

- message_definitions/v1.0/development.xml
Just add a note/hint about the rate at which it should be sent.
> development.xml FIGURE_EIGHT_EXECUTION_STATUS - set at low rate

- message_definitions/v1.0/common.xml
Supply voltage to EFI sparking system.
> common.xml: add ignition_voltage to EFI_STATUS

- message_definitions/v1.0/ualberta.xml
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
> Remove gibberish descriptions

- message_definitions/v1.0/common.xml
Removes ambiguity on direction of HOME_POSITION frame. 
@tridge @julianoes OK?
> HOME_POSITION - clarify local frame means NED

- message_definitions/v1.0/common.xml
Change DO_LAND_START from 2D distance (lat, lng only) to 3D (also consider altitude).
> DO_LAND_START to consider altitude (3D distance)

- message_definitions/v1.0/common.xml
omg ... my fault, I'm so sorry :(
https://github.com/mavlink/mavlink/pull/1928#issuecomment-1341373366
> Gimbal manager cap flags: resolve duplication mistake

- message_definitions/v1.0/common.xml
I failed to properly rebase https://github.com/mavlink/mavlink/pull/1912
Discussion in https://github.com/mavlink/mavlink/pull/1912 was concluded, and this PR here takes into account the conclusions/suggestions/comments.
> Gimbal Device: Adding more invalid and bitmask attributes (II)

- message_definitions/v1.0/common.xml
> common.xml: fix typos in AIS_TYPE enumerate

- message_definitions/v1.0/common.xml
Follows on from discussion in https://github.com/ArduPilot/MAVProxy/pull/1149
@peterbarker OK?
> Indicate preference for COMMAND_INT

- message_definitions/v1.0/ardupilotmega.xml
for handling an external position estimate while dead reckoning
See ArduPilot PR https://github.com/ArduPilot/ardupilot/pull/23903
> ardupilot: added MAV_CMD_EXTERNAL_POSITION_ESTIMATE

- message_definitions/v1.0/all.xml
400 ID's reserved to enable deconfliction of a number of vendor mavlink forks into clear address space.
> reserve range in all.xml

- message_definitions/v1.0/common.xml
@rmackay9 @AndKe This PR replaces #1962 with how I think this should look based on our discussions. I am pretty sure it matches what ArduPilot does currently.
Are you OK with this?
> MAV_CMD_CONDITION_YAW - shortest direction v2

- message_definitions/v1.0/common.xml
decoding the old MODE message is a terrible way to do this
ArduPilot PR is here: https://github.com/ArduPilot/mavlink/pull/352
Please do not merge this PR yet, it's for-discussion.
> common.xml: add a command to deal with safety switch

- message_definitions/v1.0/common.xml
from https://github.com/ArduPilot/mavlink/pull/349
Thanks/credit goes to @andyp1per
> Allow individual fences to be enabled and disabled

- message_definitions/v1.0/development.xml
Allow changes of the system id and component id
> common: MAV_CMD_DO_SET_SYS_CMP_ID: Add first version

- message_definitions/v1.0/development.xml
- message_definitions/v1.0/storm32.xml
Suggestion for a new RADIO_RC_CHANNELS message.
The backgorund is given in the issue https://github.com/mavlink/mavlink/issues/1921.
If generally approved, the details of it may be discused here in this PR.
> RADIO_RC_CHANNELS message

- message_definitions/v1.0/common.xml
Fixes #2085
Self merging
FYI only @auturgy @julianoes
> Fix DO_FENCE_ENABLE param wrongly added to PARACHUTE command

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
- message_definitions/v1.0/minimal.xml
- Add MAV_TYPE and MAV_COMPONENT enums for illuminators
- Remove MAV_CMD_ILLUMINATOR_ON_OFF from wip
- Add command to configure illuminator settings
- Add messages to report illuminator status and information
> Add support for illuminators

- message_definitions/v1.0/development.xml
@hamishwillee ID duplicated for FUEL_STATUS. This fixes it and code gets generated.
> development: change FUEL_STATUS id to fix duplication error

- doc/mavlink_xml_to_markdown.py
This updates docs build script to provide a summary of message counts in file/included - rather than the confusing big fat table.
> Remove summary table and replace with overview

- message_definitions/v1.0/common.xml
Elaborated on the use of Orbit yaw behaviour.
see associated PR: https://github.com/PX4/PX4-Autopilot/pull/23358
> Yaw Orbit Behaviour - add an option to select system default

- .github/workflows/fetch_dialect_ardupilotmega.yml
A script to fetch ardupilotmega.xml from ArduPilot/mavlink. Initially as a workflow trigger, but will add schedule later.
> fetch_dialect_ardupilotmega - create

- .github/workflows/fetch_dialect_ardupilotmega.yml
Too hard to cherry pick this stuff. But should make merging possible at some point.
> fetch_dialect_ardupilotmega.yml to include all included dialects

- message_definitions/v1.0/uAvionix.xml
Cherry-picked from ardupilot/master
> uavionix: add ping200x status and control messages

- message_definitions/v1.0/common.xml
This aims to clarify MAV_CMD_DO_LAND_START following the discussion in #2201. @DonLakeFlyer @peterbarker can you check this please?
> MAV_CMD_DO_LAND_START clarifications

- .github/workflows/test_and_deploy.yml
GitHub Actions: Test on the latest Long Term Support versions of Node.js and Python
* https://github.com/actions/setup-node?tab=readme-ov-file#supported-version-syntax
* https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input
> GitHub Actions: Test on LTS versions of Node.js and Python

- message_definitions/v1.0/development.xml
This is not happening, so I'm removing it again.
Interest clearly wasn't there, see: https://github.com/PX4/PX4-Autopilot/pull/21082
Reverts https://github.com/mavlink/mavlink/pull/1948.
> development: remove SET_AT_S param

- doc/mavlink_xml_to_markdown.py
- message_definitions/v1.0/common.xml
Fixed up version descriptions to `(Dev &amp; 0xff) &lt;&lt; 24 \| (Patch &amp; 0xff) &lt;&lt; 16 \| (Minor &amp; 0xff) &lt;&lt; 8 \| (Major &amp; 0xff)` as the pipes were being eaten by vitepress
FYI Julian, two more cases.
> common.xml - fix up bad rendering of version fields

- message_definitions/v1.0/minimal.xml
found a spelling mistake while looking through the `minimal.xml` file
> fix: spelling mistake

- .github/workflows/test_and_deploy.yml
- ruff.toml
* https://github.com/astral-sh/ruff
* https://github.com/astral-sh/ruff-action
> GitHub Actions: Lint Python code with ruff

- message_definitions/v1.0/development.xml
Accompanying 
- https://github.com/PX4/PX4-Autopilot/pull/24391.
> command: MAV_CMD_ACTUATOR_GROUP_TEST

- examples/c/udp_example.c
> C example fixup

- message_definitions/v1.0/common.xml
> MAV_EVENT_CURRENT_SEQUENCE_FLAGS - mark as bitmask
