mavlink/mavlink

pymavlink/generator/C/include_v1.0/mavlink_types.h

Unnamed struct led to compiler warnings.

Named an unnamed struct

---

pymavlink/mavnative/mavnative.c

Hi @tridge - This PR includes fixes for mavnative.  The first problem would only occur if you used 64 bit fields on a 32 bit arch (if running on a 64 bit OS the problem would not appear)

mavnative: Fixes for 32 bit arches and zero length strings

---

message_definitions/v1.0/common.xml

So two messages should now give us full back-to-back ROS-PX4 interoperability :
1. LOCAL_POSITION_NED_COV (this PR)
2. ATTITUDE_QUATERNION_COV
Originating system is expected to send these with same timestamps and receiver publishes them simultaneously, if required, after receiving the last message.

Add acceleration to LOCAL_POSITION_NED_COV

---

message_definitions/v1.0/common.xml

Based on Daniel's PR.  I've made a few modifications:
1. squashed most of the commits down into a single commit
2. removed the target-id and component-id fields because I think this message is more of an informational message to anyone who is interested (most likely just the flight controller) rather than a command that is meant to be sent to just a particular device.
3. minor wording changes.

Alternative LANDING_TARGET message

---

message_definitions/v1.0/common.xml

Adds Vibration message as discussed with Tridge and Lorenz.

common.xml: add VIBRATION msg

---

pymavlink/generator/mavparse.py

Hi,
Current implementation of `merge_enums(xml)` function in mavparse.py does not merge description of enum from parent (included) file which can be confusing if child definition does not provide updated description.
As a result if you generate protocol from `pixhawk.xml` (could be any definition which extends common enums) enum description for `MAV_CMD` (any extended enum without provided description) will be lost.
Not sure whether it is expected behaviour or bug.
Max

mavparse: transfer enums description to child definition while merging enums 

---

CMakeLists.txt

The CMake build was broken because the generateMavlink macro wasn't using the "python -m" style to call the python module.

cmake: fix broken CMake build by calling the module with python -m.

---

message_definitions/v1.0/common.xml

Main reason for this PR is to allow offboard control of takeoff and landing routines in local frame. This is pretty useful so to implement takeoff and landing when no global coordinates are known and also to apply landing target locations to the same routine.
Apllications: no GPS systems; indoor flight; external navigation controllers; others

Add commands to takeoff and land in local position

---

message_definitions/v1.0/common.xml

In many offboard applications, mainly in ROS, these fields may be required:
* Timestamp of the message, so to guarantee sync between offboard app and the FCU;
* Size of target, which can be used for visualization purposes.
I'm not aware if adding these fields can break a firmware application already using them nor if it goes against https://github.com/mavlink/mavlink/pull/394, but right now I'm not aware of this msg being used in any system yet. Right now, I think users will benefit from this adds, and as @rmackay9, serve mainly as a informational message, but to both user and FCU.
**EDIT:** it will also allow to get all info from IRLock driver currently implemented.
@LorenzMeier, @tridge, @rmackay9 your call! Thank you!

LANDING_TARGET: added timestamp and target size fields to msg

---

.gitmodules
pymavlink/generator/javascript/README.md
pymavlink/generator/javascript/package.json
pymavlink/generator/mavgen_javascript.py

The fixed version of jspack is now available through NPM repositories

JS MAVLink: removed jspack submodule since it's not necessary anymore

---

message_definitions/v1.0/common.xml

Ardupilot sometimes has these capabilities, and it is important that the GCS knows when they are supported.

New capabilities

---

pymavlink/tools/mavkml.py

Added more colours for now to prevent an out of index error. Not the most robust solution but should keep things alive for a while.

PX4 now has more mainstate modes than colours available in mavkml.

---

pymavlink/generator/mavgen_c.py

As is easily understood if the ${description} placeholder is a string with newlines, a corrupt header will be generated as the description text will be expanded as probably invalid C because it is not protected by the comment guards.

Messages' field description with a newline corruption correction

---

pymavlink/generator/mavgen_python.py

As reported in #407, the crc computation is still not completely correct. The issue is that the behaviour of chr  diverges between python2 and python3 for crc_extra >= 128 ("extented-ascii").
For example, in python2, chr(240) returns 0xf0 while it returns ð in python3. Once transformed in array in accumulate_str, it gives respectively array('B', [240]) and array('B', [195, 176]). 
The use of struct.pack fix the issue.

[python3] try to compute properly the crc for python3

---

pymavlink/mavextra.py

Importing quaternion when numpy isn't installed throws an error.
Since this is in "mavextra", it seems like we can ignore the message without much concern.

Allows pymavlink to be run without numpy.

---

message_definitions/v1.0/common.xml

@LorenzMeier 
I'd like to get https://github.com/PX4/Firmware/issues/2797 resolved somehow. Instead of adding yet another message with just a single field I changed the VTOL state message, since it's probably not used anywhere yet, into something more general.
Opinions? Is there maybe another way to get the landed state? (I also thought about the reserved bits from custom_mode)
(The only other VTOL related information we talked about was the estimated airflow. That could be added here too.)

TBD: Proposal to expose landed state

---

message_definitions/v1.0/common.xml

ADSB Lat/Lon to use int*1E7 instead of float

ADSB Lat/Lon to use int*1E7 instead of float

---

message_definitions/v1.0/common.xml

Changes:
1) Add a Squawk validity flag.  It is not entirely clear if a squawk value of 0 is invalid per https://en.wikipedia.org/wiki/Transponder_(aeronautics) so use a new validity flag.
2) change altitude from float to int32 and it's unit from meters to mm
3) change hor velocity from float to uint16 and it's unit from m/s to cm/s
4) change vert velocity from float to uint16 and it's unit from m/s to cm/s
5) change index of simulated flag from bit 32 to 64

adsb_vehicle: add squawk flag, convert floats to ints

---

message_definitions/v1.0/common.xml

Commands are type for waypoint, spatial and no coordinate. This allows GCS to show mission appropriately for user commands.
Replacement for Pull #525

Add user defined commands

---

message_definitions/v1.0/common.xml

This is a new MAV_CMD designed to delay execution of the following navigation commands until a specified time has passed or until an absolute time of day has been reached.  It's useful for adding simple coordination of vehicles as shown in this video.
https://www.youtube.com/watch?v=9VK3yjIyCSo
Note that in the video above, I actually hacked the CONDITION_DELAY but really we need a navigation command to do this properly.

Added support for MAV_CMD_NAV_DELAY in common.xml

---

message_definitions/v1.0/common.xml

PX4 NAV_CONTROLLER_OUTPUT implemented here - https://github.com/PX4/Firmware/pull/4363
I'd personally rather have altitude/altitude_sp and airspeed/airspeed_sp instead of altitude/airspeed error. Any objection to adding the actual setpoints to this message as well?

update NAV_CONTROLLER_OUTPUT comment

---

message_definitions/v1.0/common.xml

the new command introduces submodes for manual position control mode.
examples are circle mode or zoom out.
Signed-off-by: Roman <bapstr@ethz.ch>

added vehicle command for position control submodes

---

message_definitions/v1.0/ASLUAV.xml

Cleanup of the ASLUAV message specification, which brings the FW_SOARING_DATA and SENS_POWER_BOARD messages close to their final definition. 
_Note that this is not deployed through the common.xml message specification, i.e. does not affect the standard Pixhawk (&etc.) firmwares and ground stations._

Cleanup of ASLUAV message specification

---

message_definitions/v1.0/common.xml

This is a slight improvement over a previous pull request that wasn't merged. https://github.com/mavlink/mavlink/pull/533
I've recreated it due to new interest.
Looking at the existing mavlink commands I just don't think MAV_CMD_DO_REPOSITION, MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT, etc are quite right. Changing only your altitude while respecting whatever mode you're in is pretty common.
PX4 issue: https://github.com/PX4/Firmware/issues/5001
@superware FYI

add MAV_CMD_DO_CHANGE_ALTITUDE

---

message_definitions/v1.0/common.xml

This replaces Allan's MAV_GPS PR: https://github.com/mavlink/mavlink/pull/555
and addresses Lorenz's (hopefully final concern) that we're missing a time_usec field.

Adding the MAV_GPS message (from allanm84)

---

message_definitions/v1.0/common.xml

done as MAVLink2 only. 
Used by AP_Button library in ArduPilot to support reporting changes to GPIO input states to the GCS

common.xml: added BUTTON_CHANGE message

---

pymavlink/generator/mavgen_cs.py

For example, the MAV_SYS_STATUS_SENSOR enum requires more bits that a ushort provides.

Increase enum size for C sharp generated code

---

README.md

Pretty self-explanatory. I had a colleague who was getting the python error "No module named pymavlink.generator"
When I looked in the pymavlink directory, it was empty. This is because the submodule was not cloned by the simple "git clone https://github.com/mavlink/mavlink"
I'm sure lots of users new to git get bitten by this one. This simple documentation fix should prevent some frustration from newbies.

Update README.md w/ steps for pymavlink submodule

---

message_definitions/v1.0/common.xml

First pass at creating a single message appropriate for Iridium connections.
Based on @LorenzMeier's proposal here - https://groups.google.com/forum/#!searchin/mavlink/iridium%7Csort:relevance/mavlink/hv7zJ5Xdwcc/lHhZ4lXXBwAJ
TODO:
- EKF status?
- bitmap for actuator health?
- max size? Should we aim for 50 bytes?

HIGH_LATENCY message for Iridium connections

---

message_definitions/v1.0/common.xml

This adds an additional comment to the flag MAV_MODE_FLAG_SAFETY_ARMED
which deprecates its use as a command. Instead the command
MAV_CMD_COMPONENT_ARM_DISARM should always be used to change the armed
state like it is already the case for most (if not all) ground sattions.
The reasoning behind the change is that it is:
- not intuitive to change the armed/disarmed state in a "mode",
- it is dangerous if forgotten because the vehicle can fall from the sky
or equally bad suddenly arm,
- it can lead to race conditions because the flag needs to be set using
the base_mode which arrives by the heartbeat (usually at only 1Hz), so
by the time a DO_SET_MODE command is sent, the state might have
changes on the vehicle.

common.xml: ignore FLAG_SAFETY_ARMED in DO_SET_MODE

---

message_definitions/v1.0/common.xml

This is an attempt to improve and extend the mavlink camera and gimbal API.
The command `DIGICAM_CONFIGURE` is deprecated in favor of `CAMERA_INFORMATION`, `CAMERA_CAPTURE_STATUS`, `CAMERA_SETTINGS_1`, and `CAMERA_SETTINGS_2`.
For the camera storage `STORAGE_INFORMATION` and `STORAGE_FORMAT` has been added.
To control the gimbal, the lat/lon fields have been moved to param5/param6 for int32 accuracy, and a `MOUNT_STATUS` is added for the realtime feedback about a gimbal (or other mount).
Please review:
@LorenzMeier, @mcharleb

Camera and gimbal improvements

---

message_definitions/v1.0/common.xml

@LorenzMeier 
We're doing some high-rate state sharing across Mavlink with an offboard estimator, and this PR bumps the timestamp fields to have better resolution, and adds the companion timestamp field which was missing in the ATTITUDE_QUATERNION_COV message.
These messages haven't been adopted anywhere major, so I think this change should be OK.

Better timestamps for offboard messages

---

message_definitions/v1.0/common.xml

Reduce HIGH_LATENCY so that the encoded mavlink message is < 50 bytes to fit within a single RockBlock billing credit.
I know generally we can't change messages after they're published, but this was only recently added and hasn't been implemented yet.
The timestamp would have been nice, but we can get that from RockBlock if the message actually goes through.

HIGH_LATENCY reduce size

---

message_definitions/v1.0/common.xml

We don't actually need all the mount mode and lat/lon/alt information
because it is all set from outside using MAV_CMD_DO_MOUNT_CONFIGURE and
MAV_CMD_DO_MOUNT_CONTROL.
As discussed with @bkueng.
@LorenzMeier please review.

common.xml: simplify mount status

---

message_definitions/v1.0/common.xml

Most times when shooting a picture or recording a video, the full
resolution is what a user wants. It therefore makes sense to inclue this
in the spec and make it easy to do just this.
@AndreasAntener this should be what we discussed, please review.
@LorenzMeier any objections?

Photos/Videos: use -1 for max resolution

---

message_definitions/v1.0/common.xml

@LorenzMeier @tridge there's currently a conflicting setting between APM & PX4: the same value for param6 is used for different calibrations (see diff). Should we add 2 new values to deconflict in addition to the current and make the Firmwares accept both for a period of time?
Like this:
```
<param index="6">1: APM: compass/motor interference calibration / PX4: airspeed calibration (deprecated), 4: compass/motor interference calibration, 5: airspeed calibration</param>
```

PREFLIGHT_CALIBRATION: update descriptions & add temperature calibration

---

message_definitions/v1.0/common.xml

- Establishes that a `CAMERA_IMAGE_CAPTURED` message is sent after each image captured as a result of `MAV_CMD_IMAGE_START_CAPTURE`.
- Clarifies that `MAV_CMD_VIDEO_START_CAPTURE` and `MAV_CMD_VIDEO_STOP_CAPTURE ` means “Recording”.
- Add the ability to request CAMERA_CAPTURE_STATUS messages to be sent automatically during video recording.
- Add a field to `CAMERA_CAPTURE_STATUS` telling the current recording time.
- Add a field to `CAMERA_CAPTURE_STATUS` telling the current remaining storage capacity.
- Changed the `file_path` in `CAMERA_IMAGE_CAPTURED` to `file_url` as this is more appropriate. A local storage path is of limited use. But if the camera supports image requests through an HTTP interface, this can be used to send the URL to obtain the image.

Some tweaks and additions to Video/Photo capture.

---

message_definitions/v1.0/common.xml

This fixes an overflow that occured because the message was 260 bytes
instead of 255 which is the maximum length.
The compiler error was:
```
mavlink_msg_camera_image_captured.h:22:54: warning: large integer implicitly truncated to unsigned type [-Woverflow]
#define MAVLINK_MSG_ID_CAMERA_IMAGE_CAPTURED_MIN_LEN 260
```
We wonder why CI doesn't catch this.

common.xml: hotfix for overflowing message

---

message_definitions/v1.0/common.xml

This specifies that NaN for yaw on these commands means no change in yaw:
```
MAV_CMD_NAV_WAYPOINT
MAV_CMD_NAV_LAND
MAV_CMD_NAV_TAKEOFF
MAV_CMD_NAV_VTOL_TAKEOFF
MAV_CMD_NAV_VTOL_LAND
```
This is the way PX4 Pro works. I believe that for a number of these, ArduPilot does not support the Yaw field. Can this be checked to work on ArduPilot as well. This allows for things like running a survey at a fixed yaw angle (relative to ground, not vehicle) without needing to specify yaw on every single waypoint in the survey as an example.
@tridge Can someone on the ArduPilot side help out with verification?

Add spec for NaN on yaw angle

---

message_definitions/v1.0/common.xml

GPS_RTCM_DATA is used in releases, and is no longer a WIP message.

Remove WIP label from GPS_RTCM_DATA

---

message_definitions/v1.0/common.xml

This makes airspeed calibration use a new param value and deprecates the PX4's conflicting definition.
Follow-up to #673
@tridge fyi, no changes needed for APM
@DonLakeFlyer fyi

PREFLIGHT_CALIBRATION: deconflict APM/PX4 param def for airspeed calibration

---

message_definitions/v1.0/ardupilotmega.xml

This adds a new VISION_POSITION_DELTA mavlink message to the ArduPilot specific messages.
This message could probably be integrated into common.xml but there will be more developments that might lead us to add more fields to this message. Because ArduPilot is the only user for the moment I think it's probably ok to leave it in the ardupilot specific set.
This has been successfully flight tested with ardupilot and a stereo ZED camera.
Here is the equivalent downstream PR: https://github.com/ArduPilot/mavlink/pull/33

ardupilot: add VISION_POSITION_DELTA message definition

---

message_definitions/v1.0/common.xml

This adds more camera settings:
- image quality ID (e.g. for JPG this could translate to 0-100)
- metering mode ID (this is for different metering modes specific to a
camera)
- flicker mode ID (this is for different flicker modes, also specific to
a camera.

mavlink_defs: image quality, metering, flicker

---

message_definitions/v1.0/common.xml

This is to avoid ambiguity.
- Better describe the values for Camera and Storage ID.
- Make their position in the parameter list consistent.
- Added a Camera and Storage count field (within their respective INFORMATION messages). If you have more than 1 camera and/or storage devices, this will tell you how many there are.
For Camera and Storage. When there is a choice of selection, 0 is used to define *ALL*, 1 for the first, 2 for the second, etc.
When a response identifies the source, it will have the respective ID (1 for the first, 2 for the second, etc.)
If command does not explicitly says "0 for all", you must issue one command per device.

Better description and definition of Camera and Storage ID

---

message_definitions/v1.0/common.xml

This adds a field to display the progress in percent from 0 to 100, and
MAV_RESULT_IN_PROGRESS to signal that the command is being executed but
not yet finished.
MAV_RESULT_IN_PROGRESS can be followed by any of the other MAV_RESULTs
depending on what happened.

common.xml: add progress to MAV_RESULT

---

message_definitions/v1.0/common.xml

v1 - https://github.com/mavlink/mavlink/pull/664
Changes:
1. Use separate commands to start/stop video streaming.
2. Use URL instead if IP and port.
3. Add a new capability for video streaming to MAV_PROTOCOL_CAPABILITY bitmask.
Unfortunately, I don’t see a clear and concise way to overcome the issue of dynamically requested camera capabilities. One of the options might be to add new MAVLink messages that request list for every capability. For example:
Command MAV_CMD_REQUEST_CAMERA_RESOLUTIONS requests mavlink message CAMERA_RESOLUTIONS which contains array of C strings with all possible values (i.e. [640x480 1280x720]).
@LorenzMeier @julianoes @dogmaphobic please review

Video streaming improvements v2

---

message_definitions/v1.0/common.xml

This sub-protocol allows to request flight information (start, end, duration, current flight status, distance covered, time remaining) from the autopilot and helps to avoid having a huge state machine in the GCS trying to track the autopilot state.
It consists of the (WIP) request message:
http://mavlink.org/messages/common#MAV_CMD_REQUEST_FLIGHT_INFORMATION
And the (WIP) response:
http://mavlink.org/messages/common#FLIGHT_INFORMATION
I think in particular the response is incomplete in terms of meta information / fields. Suggestions? Note that is is all a proposal and not deployed, so we can be still very creative.
Suggestions for fields that might make sense:
* Battery remaining in time (at current velocity)
* Maximum safe distance (at current battery level and assuming an RTL at cruise …

Add protocol capability bit for flight information

---

message_definitions/v1.0/common.xml

This extends the camera trigger specs to be overall more consistent, in particular for survey missions.

Extend camera trigger specs. From @mhkabir

---

message_definitions/v1.0/common.xml

When a radio or similar device is MAVLink 1 enabled but does not support MAVLink 2 and is connected between two nodes supporting MAVLink 2 it is nontrivial to discover if MAVLink 2 can be enabled: Both ends of the communication channel support it and show their support in the MAV_PROTOCOL_CAPABILITY flags but enabling it would still make the radio fail.
This extension allows to send a MAVLink 2 message as a test to see if it passes correctly through the link. As the request for the message is implemented as a command which should be NACKed as unsupported any node not having added support for this would default to MAVLink 1. This should allow a safe and robust handshake, including command retransmission if required.
This is an attempt to solve the problem described in the commit message. …

Add MAVLink version handshake

---

doc/README
doc/mavlink_gitbook.py
doc/mavlink_to_html_table_gitbook.xsl

Script generates a file message-definitions.md that can be imported into a gitbook. This depends on XSL file being added to master.

Generate common message specs in gitbook format

---

message_definitions/v1.0/common.xml

It turns out, it's a bad idea to have the resolution settings in the
same command as the start recording / capture command. This is because
both, the setting or the action, can fail and the result won't tell
which one did. Also applying a setting can take some time and can delay
the command to take a picture / record a video which should be
instantanteous.

camera: separate commands and settings

---

message_definitions/v1.0/common.xml

Change to comment only. When setting a camera setting, you must define a camera ID rather than allowing *All Cameras*. This is consistent with the remaining `SET_CAMERA_SETTINGS_XX` commands.

Camera Settings must define a camera.

---

message_definitions/v1.0/common.xml

This PR adds full pose of a landing target, besides the angular offsets and distances. This is very useful for targets detected by cameras who are running feature and markers detection algorithms (fiducial, specific shapes, others).
Besides, adds `LANDING_TARGET_TYPE` enumeration, which specifies what type of landing target the system is detecting/landing into.

common: add full pose to LANDING_TARGET; add LANDING_TARGET_TYPE enum

---

message_definitions/v1.0/common.xml

The reason for these changes is to make it way easier to create survey missions which have consistent coverage over a polygonal area. The basic idea is to modify the TRIGG_DIST command such that:
* When you start distance triggering the first image is taken right away (optional) instead of waiting until the first distance passes.
* When turning off distance triggering you can also take one last image at that point (optional).
This makes it possible to simply set up missions which generate transects that have full coverage from the entrance of the survey area to the exit of the survey area. Specifically for the case where images are not taken in the turnarounds. But this also helps when taking images throughout an entire survey. Since it will close up possible holes in the coverage at the …

TRIGG_DIST: Support trigger before/after distance trigger start/stop

---

message_definitions/v1.0/common.xml

The camera status needs to inform if the camera is currently taking a
picture and therefore busy, but also if it is set for an interval.

message_definitions: improve image capture status

---

message_definitions/v1.0/common.xml

PPP GPS's are readily available for use these days, and the fix type can't be communicated to the ground correctly.

Common: Add GPS_FIX_TYPE_PPP

---

message_definitions/v1.0/common.xml

Extending (by creating a new set of messages) the PARAM SET/VALUE messages. This adds an extended set of result ACKs and increases the value payload from float to double. The primary use is for camera settings but nothing stops you from using for something else.

Extended parameter handling

---

message_definitions/v1.0/common.xml

This is in preparation for adding support for a _Camera Definition File_ as discussed in [discuss.px4.io](http://discuss.px4.io/t/mavlink-camera-api-discussion/3278/26).
* Flagging messages and commands that are to be removed
* Adding an URI for fetching the camera definition file (if any) to the `CAMERA_INFORMATION` message
* Adding a revision number for the definition file (to check against an already cached version)
* Adding a capability flag to the `CAMERA_INFORMATION`.
* Adding an enum with a bitmap describing the various capability flags (`CAMERA_CAP_FLAGS`)
* Adding a `device_id` field to the `COMMAND_ACK` message to identify target devices that share a component ID (Camera, Storage, etc.)
@julianoes  Please check and see if the implementation of the `CAMERA_CAP_FLAGS` is correct. …

Camera Definition

---

message_definitions/v1.0/common.xml

Clean up unused camera settings messages and commands.
Remove all references to camera ID (use component ID instead).

Final step in moving camera settings to PARAM_EXT_xxx

---

message_definitions/v1.0/common.xml

Camera count is not longer relevant in CAMERA_INFORMATION. I missed this when removing all dead weight this morning.

Missed one field to be removed.

---

message_definitions/v1.0/common.xml

These 5 commands are used by QGroundControl and it expects param1 to be 0.
```
SET_CAMERA_MODE
IMAGE_START_CAPTURE
IMAGE_STOP_CAPTURE
VIDEO_START_CAPTURE
VIDEO_STOP_CAPTURE
```
Also removing the "WIP" comment given that they are now locked down.

Reserved slot for where camera id used to be.

---

message_definitions/v1.0/common.xml

message_definitions: fix the camera mode enum name

---

message_definitions/v1.0/common.xml

Given that there has been no development with PR #730, I've adding this one message here. It's used for setting an Access Point SSID and its password.
If further progress is done with #730, they can add those message above this one.

Set WiFi SSID and/or password.

---

message_definitions/v1.0/common.xml

It would be nice to have an unequivocal indication to a GCS/operator that the system is performing a commanded flight termination. MAV_STATE_EMERGENCY could be sent for this, but there are other reasons to get into that state, so I'd prefer to have an unambiguous message for termination if that's fine with others.

Add a terminating state

---

message_definitions/v1.0/common.xml

Allow vehicles to request flight authorization before arm.
Government entities like NASA are working in systems to managed the aero space for drones(https://utm.arc.nasa.gov/) but this also can have another uses by private companies.
More information about how it should work:
PX4 implementation: https://github.com/PX4/Firmware/pull/7377
Arm authorizer implementation: https://github.com/01org/mavlink-router/pull/94
I also plan to implement this in Ardupilot after implement in PX4.

Arm authorization messages

---

message_definitions/v1.0/common.xml

This is an attempt to consolidate approaches on vertical landings. I don't know all the methods used but I believe that this currently solved differently across implementations. Possibly someone already has an elegant solution for this problem, if so, please let me know :).
**The problem**: With only one altitude field for a landing mission item we have to decide if the vehicle approaches on that altitude (horizontally) until it's above the landing spot **OR** if that altitude marks the height where we should expect ground (can be used in two step vertical landing or as fallback for a failed distance sensor).
For fixed-wing vehicles doing a glide slope landing these two altitudes are the same in the final phase which is why I'm focusing only on vertical landings right now.
My proposal is …

Common: Ability to specify ground altitude for landing waypoints

---

message_definitions/v1.0/common.xml

Proposal to standardize in which direction the VTOL transitions. This is relevant for VTOL takeoff as well as for the independent transition command.
Basically there are 4 options we use so far (there might me more, please comment):
1) (default) Direction of the next waypoint. This should be expected when planning a mission on the map since we are supposed to track the line from A to B.
2) (only relevant for takeoff) Use the heading of the vehicle on the ground before takeoff, makes sense if the user positions the vehicle consciously into the wind.
3) Use the specified heading.
4) Use whatever heading the vehicle has when getting the transition command (reaching the waypoint), especially useful for takeoff with enabled weather-vaning.

Common: Ability to specify the direction of the VTOL forwards transition

---

.travis.yml
message_definitions/v1.0/common.xml

This allows to control a gimbal in angular rate in degrees/second
instead of just setting a fixed angle. The setting can be chosen for
each axis individually.
Since this interface has already gone into a QGroundControl release and
there has not been any further feedback, it makes sense to remove the
WIP flags and stabilize it.

Mount/gimbal: add angular rate inputs, stabilize API

---

message_definitions/v1.0/common.xml

Before there was no convention on the distance sensor convention.
See also https://github.com/PX4/Devguide/pull/269 and https://github.com/PX4/Firmware/pull/7984
I added it to `MAV_SENSOR_ORIENTATION` as the distance sensor is the only sensor using it so far. If that should stay general we can add the comments to the `DISTANCE_SENSOR` message.

add distance sensor orientation convention

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

The word `waypoint` in messages descriptions was (automatically, I guess) incorrectly replaced by the word `MISSION`. This happened in this commit: https://github.com/mavlink/mavlink/commit/5c0db0af362f006e6273585faacc9ac7235281fd.
Example: 'Navigate to waypoint' [changed](https://github.com/mavlink/mavlink/commit/5c0db0af362f006e6273585faacc9ac7235281fd#diff-74a8341bc36e5b40828d5b6d8a1929b4R338) to 'Navigate to MISSION'.
This fixes it.

Fix incorrect substitution of 'waypoint' to 'MISSION' in descriptions

---

message_definitions/v1.0/common.xml

Newer HW chips provide a 128 bit identifier. To make use of that we extend
the message with a longer uid, and use an uint8 array, so that the byte
ordering is clear.
The new field is 18 bytes, so that 2 bytes can be used to differentiate
between multiple SoC's.

mavlink_autopilot_version_t: add extended uid2 hardware identifier

---

message_definitions/v1.0/common.xml

The new set of extended set of parameters allows for up to 128 bytes. This set of types will allow us to define future complex types such as matrices, coordinates, etc.

Adding extended set of types for the PARAM_EXT set of messages.

---

README.md
message_definitions/v1.0/common.xml

Per request from #general, attached is some clarifying prose regarding mavgen.py and its output.
I've also included an addition of MAV_TYPE_PARAFOIL, in anticipation of some of my ongoing work.

README update for mavgen.py; add MAV_TYPE_PARAFOIL

---

doc/mavlink_gitbook.py

This generates markdown into a folder and names as we wish to use it in docs. The reason for putting into a  folder is that eventually we might generate docs for other message types.

Generate markdown to messages/common.md

---

doc/mavlink_gitbook.py
doc/mavlink_to_html_table_gitbook.xsl

Scripts provide much better interlinking of generated message definitions. The tools are now run over all message definitions, not just the common.xml

Update scripts to generate markdown message definitions

---

message_definitions/v1.0/common.xml

Here is the problem. QGC supports polygonal Structure Scan. Here are some examples:
The current implementation yaws the gimbal 90 degrees in order to keep the camera pointed at the structure during flight using a DO_MOUNT_CONTROL command. The issue is how do you do this when you don't have a gimbal that supports yaw. As far as I can tell the current answer is that there is no way to do this. You end up fighting with the fact that default mission flight path parameter setting is to point to the next waypoint. And you can't change that from a mission.
So this change is to use MAV_ROI_WPNEXT with offsets to get an ROI which can be an offset from the direction to the next waypoint. Using the structure scan as an example I would set the yaw into param 7 to 90 degrees of MAV_CMD_DO_SET_ROI and …

WIP: MAV_CMD_DO_SET_ROI - Add optional offsets to MAV_ROI_WPNEXT mode

---

message_definitions/v1.0/common.xml

This documents the usage of `param2` of `MAV_CMD_NAV_LAND` for precision landing.

precision land: add description for precision land mode

---

message_definitions/v1.0/common.xml

The DIGICAM_CONFIGURE and DIGICAM_CONTROL commands have been replaced
by the Dronecode camera working group, and the implementation of camera
definitions and the new PARAM_EXT_XXX parameters.
For more info, check: https://mavlink.io/en/protocol/camera_def.html
Therefore, this commit deprecates these two commands in order to
encourage adoption of the new interface.
@dagar this was your question in the strategy call last week.

common: deprecate DIGICAM_CONFIGURE/CONTROL

---

message_definitions/v1.0/common.xml

- Use the 2 bytes custom_mode instead of a custom defined flight mode.
- Merge `failure_flags` and `failsafe` into one 2 byte bitfield.
- Change the naming of the `failure_flags` so that it is closer to `MAV_SYS_STATUS_SENSOR` wherever possible.
@dagar @DonLakeFlyer can you check it?

HIGH_LATENCY2 revision

---

message_definitions/v1.0/common.xml

Adds the interface to request starting/stopping the high latency telemetry on the autopilot.

Add MAV_CMD for starting/stopping high latency telemetry

---

message_definitions/v1.0/common.xml

The current yaw field was implemented as a yaw relative to the vehicle's
heading in QGC and is therefore stabilized that way.
However, we sometimes also would like to know the absolute orientation
of a mount/gimbal relative to North, so that's why the field
`yaw_global` is added.

common.xml: add global yaw angle, clarify comments

---

examples/linux/README

This linked to a "more comprehensive example" on defunct mavlink site. (ie that did not exist). Simply removed link. Longer term, need to look at topic and migrate into new devguide.

Remove link to non-existent example

---

message_definitions/v1.0/common.xml

Common.xml had links to old site. This changes links to point to location on new site.

Fix links to old mavlink site in common messages

---

message_definitions/v1.0/common.xml

This raises the channel count possible for RC override channels to 18,
so on par with RC_CHANNELS.
These channels can be used to send RC input via mavlink (e.g. over wifi)
to a drone.

common: extend RC_CHANNELS_OVERRIDE to 18 channels

---

message_definitions/v1.0/common.xml

Nowadays, a lot of companies are developing charging stations for autonomous drones ([\[1\]](https://www.youtube.com/watch?v=MD3cQNd-iSA), [\[2\]](https://www.youtube.com/watch?v=RjX6nUqw1mI), [\[3\]](https://www.youtube.com/watch?v=061Qhkr7XCE)).
MAVLink protocol looks a good choice to make a communication between the drone and charging stations. The automatic charging station can send its telemetry using some standard messages (global position, pressure, etc), its state (open/closed lid, charging/idling) via `HEARTBEAT`'s custom mode, and execute some commands (open lid, start charging) using `COMMAND_LONG`.
Such stations can advertise themselves in MAVLink network as the proposed new device type: `MAV_TYPE_CHARGING_STATION`.

Add MAV_TYPE_CHARGING_STATION

---

message_definitions/v1.0/common.xml

It looks like typo in `MAV_FRAME_LOCAL_NED` and `MAV_FRAME_LOCAL_ENU` definitions: it tells NED is Z-up, ENU is Z-down but in fact the opposite is true.

common: fix MAV_FRAME_LOCAL_NED and MAV_FRAME_LOCAL_ENU definitions

---

message_definitions/v1.0/common.xml

Adresses https://github.com/mavlink/mavlink/issues/721. I added some related Odometry frames to `MAV_FRAME` but we probably should discuss the RFC proposal for local frames of reference in https://github.com/mavlink/rfcs/pull/2.

[WIP] common: add ODOMETRY msg and Odometry related MAV_FRAMEs

---

message_definitions/v1.0/common.xml

Allow the autopilot to optionally publish its:
- estimation of the remaining time in seconds the battery can still be used before it's empty.
This information can be showed to the user or used by an external algorithm to further plan the usage of the battery/vehicle.
- low battery state telling the user or external components to what extent the battery is empty.
This information can be used to update the UI with appropriate warnings and inform external components to trigger energy saving or other risk minimizing behaviour.
FYI @julianoes @dogmaphobic 
**EDIT:** fixes #809

Common: Extend Battery Status with Remaining Time and Low Extent State

---

message_definitions/v1.0/common.xml

Given some position estimation/filters maybe be feeding data into onboard position and attitude estimators, and since IEKF, LPE, EFK2 may use covariance matrices to improve the estimation, this PR allows sending these same covariances through specific messages (vision, mocap).
@jgoppert this may interest you as one can send the odometry data from external sources through these specific msgs and receive feedback though `LOCAL_POSITION_NED_COV` and `ATTITUDE_QUATERNION_COV` respectively.

Add covariance to estimation msgs

---

message_definitions/v1.0/common.xml

Adds an enum for GCS's to use rather then simply hardcoding the values in MAV_CMD_START_RX_PAIR.

Common: Add an enum for RC reciever types

---

message_definitions/v1.0/common.xml

The description of GLOBAL_POSITION_INT mentions the following: "The position is in GPS-frame (right-handed, Z-up)". Now the explanation used for vz is saying "Ground Z Speed (Altitude, positive down), expressed as m/s * 100". One of the two is fault. The simulator is giving Z-up. I.e. the vz description is fault.

Fix typo in explanation of vz

---

message_definitions/v1.0/common.xml

The sequence/ID as a param allows to distinguish if a command was
retransmitted or if actually yet another capture has been requested.
This can avoid double captures but stil allows to retransmit the
command to make sure it arrives over a lossy link.

common.xml: add capture sequence to START_CAPTURE

---

message_definitions/v1.0/common.xml

This reverts commit 69ff05623272fd1d12da6fec807d744d375af0d4.
This was an oversight in the review and is therefore reverted.
This has all been in NED (North, East, Down) for a long time and there
is no point in changing it.
Reverts #775.

Revert "Fix typo in explanation of vz"

---

doc/mavlink_gitbook.py

This is update to the script that auto-generates the text at the top of this page: https://mavlink.io/en/messages/

Clarify custom messages can either replace or extend the common set

---

message_definitions/v1.0/common.xml

FLARM is a cooperative collision avoidance device comparable to ADS-B. It outputs ADSB_VEHICLE packets, like other ADS-B receivers. To distinguish from "real" ADS-B receivers, and to operate both FLARM and ADS-B on the same vehicle, these changes are proposed.

common.xml: Add COMP_ID and MAV_TYPE for FLARM periphery

---

message_definitions/v1.0/common.xml

This is a first draft of the avoidance message according to the [obstacle avoidance interface proposal](https://docs.google.com/document/d/1BQp1a6yszl9f6LDrxrkKUDDGyXxBs5C86BzvJwVbRrU/edit#heading=h.huol20joi641)
The `enum` MAV_TRAJECTORY_REPRESENTATION can still be extended.
The field `field_of_view` probably needs to change a bit as it's currently only possible to have one continuous field of view. A solution would be to have e.g. up to 6 of these (array)?
[RFC](https://github.com/mavlink/rfcs/pull/4)

avoidance msg

---

doc/mavlink_gitbook.py

This just pulls in the doc changes that were approved in https://github.com/mavlink/mavlink-devguide/pull/54
Just needs to be approved/merged

Add deep nesting clarification to docs generator

---

CMakeLists.txt

- This allows people to use mavlink as a submodule if they define the MAVLINK_SOURCE_DIR before entering this script
- Otherwise, falls back to CMAKE_SOURCE_DIR (current behaviour)

Allow external CMakeLists to define mavlink dir

---

message_definitions/v1.0/common.xml

Add a command to make the vehicle orbit around a target position.
The executing code for that task on PX4 is located here: https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/FlightTaskOrbit.hpp
And is currently being transformed from a draft to a supported feature here:
https://github.com/PX4/Firmware/pull/9434
This message allows the UI to access this functionality and provide all the necessary parameters to determine the behaviour like:
- Orbit center latitude, longitude, altitude (with option for local coordinates)
defaults to where the vehicle currently is
- Orbit radius (in meters)
defaults to vehicle configuration e.g. 1m for safety
- Orbit velocity (tangential in m/s, positive CW, negative CCW)
defaults to vehicle cruise velocity or less if the radius is too …

Add vehicle command for Orbit

---

message_definitions/v1.0/common.xml

This is a command version of MISSION_SET_CURRENT. This is useful as one can make sure with an acknowledge that the command arrived on the vehicle and is accepted. MAV_CMD_MISSION_START can not be used as that one is supposed also to start the mission.

Add a MAV_CMD version of MISSION_SET_CURRENT

---

doc/Doxyfile

Updates Doxyfile so it can be used with current (Ubuntu 16.04 version Doxygen) without warnings. 
Conversion performed automatically by toolchain + minor adjustment. Output looks OK.

Update Doxyfile to remove build warnings

---

message_definitions/v1.0/common.xml

This change 1) clearly specifies the frame of an angle to set (body or
absolute) and 2) adds support to set absolute angles.
This is as suggested by @bkueng.

common.xml: support absolute mount/gimbal angles

---

message_definitions/v1.0/common.xml

This makes the generated code more readable (variables get a proper name)
makes the documentation more readable (less indirection)
Saves mavlink bandwidth when transmiting bezier data

common.xml: replace the enum indirection layer, with a second message.

---

message_definitions/v1.0/common.xml

Remove a few additional enums in descriptions. Follows on from #948

Remove units from bitmask descriptions

---

message_definitions/v1.0/common.xml

Replaces the value of 38 to match the ArduPilot usage, which is the only current user that I could find of the enum. Tridge and I looked recently and couldn't find anyone using `MAV_SENSOR_ROTATION_ROLL_315_PITCH_315_YAW_315` in production publicly. If we can change this value to match the current ArduPilot map of rotations that would be quite useful as there are a couple of places we are sending the internal rotations out via MAVLink at the moment, and I'd like to be able to tag them as the enum (and allow GCS's to have proper documentation on the meanings).
I'd also like to note that this enum violates the normal naming rules we have. The enum is called `MAV_SENSOR_ORIENTATION` while the entries are all `MAV_SENSOR_ROTATION_`

Update MAV_SENSOR_ORIENTATION for more entries

---

.gitmodules
message_definitions/v1.0/ardupilotmega.xml
message_definitions/v1.0/common.xml
scripts/test.sh

This allows the pymavlink code generator to optionally drop this messages and
allows the documentation generator to mark this messages in a standard uniform way

Mark messages as deprecated using machine readable xml elements and attributes

---

message_definitions/v1.0/common.xml

Correct kibibyte and mebibyte units
Add support for marking messages as work-in-progress
Correct the XML validation of Mavlink 2.0 extensions
Replace dpixels with dpix for consistency with already existing pix units
mavlogdump: default to mavlink2

Pymavlink updates

---

doc/mavlink_gitbook.py
doc/mavlink_to_html_table_gitbook.xsl

This removes all the inline html styling and classes that aren't used by the gitbook system. The style for text alignment in html is added back as a style block via the python script.
Comments replace the classes that were removed - these don't render in the output.
This reduces the output size significantly, reducing download size. See https://github.com/mavlink/mavlink-devguide/issues/103

Remove all unnecessary html/classes from output

---

doc/mavlink_to_html_table.xsl

This makes the official docs more visible by colouring the heading red

Make make official XML rendered version more visible

---

message_definitions/v1.0/common.xml

Every channel should have the same definition. Ignoring with 0 is just there because it's an extension and extensions are filled with zero if they are not supported. UINT16_MAX is IMHO the far better way to skip the field because it's unambiguous and cannot be set by accident.
FYI @julianoes

RC_CHANNELS_OVERRIDE: ignore value fix

---

message_definitions/v1.0/common.xml

This PR adds the message DEBUG_ARRAY. This is a follow up of #732 with clean history.
I have been using this message for long and it proved really useful to debug large float arrays.
The message is similar to DEBUG_VECT, but with 60 entries instead of 3. It basically fills the maximum payload with a packet size of 263 bytes.
@LorenzMeier I placed it in v2 namespace, using id 350 as recommended by @magicrub. PRs for PX4 Firmware and QGC are coming.

common.xml: added message DEBUG_FLOAT_ARRAY

---

message_definitions/v1.0/common.xml

All messages should have descriptions. This PR adds missing descriptions so that we can start enforcing the requirement (see https://github.com/ArduPilot/pymavlink/pull/215)
I've taken a shot at descriptions. 
- Does anyone know the difference between GLOBAL_VISION_POSITION_ESTIMATE, VISION_POSITION_ESTIMATE, VICON_POSITION_ESTIMATE? They are all very similar. Don't really see why we don't have GLOBAL_POSITION_ESTIMATE and provide a field for the source type.
- These all put position in terms of metres. Where is the origin of this "global" system?

Add missing message descriptions

---

message_definitions/v1.0/common.xml

Previous message description was inaccurate with new message extension fields. 
Use of `position_valid` field unclear.
This fixes docs and adds link to more detailed information in https://mavlink.io/en/protocol/landing_target.html

Clarify LANDING_TARGET description

---

message_definitions/v1.0/ASLUAV.xml
message_definitions/v1.0/ardupilotmega.xml
message_definitions/v1.0/autoquad.xml
message_definitions/v1.0/common.xml
message_definitions/v1.0/matrixpilot.xml
message_definitions/v1.0/slugs.xml
message_definitions/v1.0/uAvionix.xml

Globally we want to use the most "standard" terminology for frames possible. For altitude those are WGS84, MSL and AGL. The use of "Absolute" is redundant.

Use consistent altitude references

---

message_definitions/v1.0/common.xml

The `target_component` refers to "system" rather than "component".
@mhkabir - Can you sanity check this change please.

Fix typo in Ping protocol definition

---

doc/mavlink_gitbook.py
doc/mavlink_to_html_table_gitbook.xsl

Enum schema now allows params to have markup like fields that define possible values, units, and display hints to GCS - e.g.: enum value, max/min/increment, units, label, display with X decimal points.
There is no really clean way to display all these fields in the current layout (see https://github.com/mavlink/mavlink/pull/1019 for best shot).
This PR does two things.
1. It splits MAV_CMD into its own group as a peer of messages and enums
2. It mimics the message format to allow columns for units and values.
But these are only displayed if the fields are defined. If not, it looks like:
The only question is where should label and decimal point fields go. I have currently put them in the description because those two don't matter to all users (they mostly matter to GCS authors).
Is that …

Make MAV_CMDs own section of messages with field markup

---

message_definitions/v1.0/common.xml

References:
- https://github.com/mavlink/mavlink/pull/924 introduced a message to command the vehicle to do an orbit
- QGroundcontrol added support for this command https://github.com/mavlink/qgroundcontrol/pull/6608, https://github.com/mavlink/qgroundcontrol/pull/6711, https://github.com/mavlink/qgroundcontrol/pull/6753 thanks to @DonLakeFlyer 
- On PX4 autopilot the implementation to execute the orbit can be found here: https://github.com/PX4/Firmware/tree/master/src/lib/FlightTasks/tasks/Orbit
New:
This PR adds a message for the vehicle to report the current status, parameters and therefore planned trajectory to the ground control station while flying an orbit to allow the UI to show a live visualization for the pilot.
Use case:
After commanding an orbit the circle in the qgc UI …

common: add orbit execution telemetry message

---

message_definitions/v1.0/common.xml

This clarifies how [MAV_TYPE](https://mavlink.io/en/messages/common.html#MAV_TYPE) should be used for systems and components. 
This is "controversial" because 
- the [HEARTBEAT](https://mavlink.io/en/messages/common.html#MAV_TYPE) message currently only talks about systems, not components.
- it means some of the definitions are wrong and should have been addressed via component ids.
Specifically:
- `MAV_TYPE` should be used to identify a particular type of system (vehicle)
- All components of a vehicle would have this same type.
- Components that need separate addressing should use the correct MAV_COMPONENT id.
Notes:
* The usage reflects how QGroundControl works
* This means that the following definitions are wrong because "Onboard" components must use the system MAV_TYPE.
- …

Clarify how MAV_TYPE should be used.

---

message_definitions/v1.0/common.xml

Follows on from https://github.com/mavlink/mavlink/pull/1022
MAV_TYPES refer to standalone systems, and are consistent across all components in a system. This clarifies the the FLARM, ADSB and CAMERA types are for standalone systems, not these items as components of an onboard system.

Redefine MAV_TYPE_ FLARM CAMERA and ADSB as standalone

---

message_definitions/v1.0/common.xml

The previous definition indicates that the write was temporary and that the setting would not survive reboot. It also indicated that you could send MAV_ACTION_STORAGE_WRITE to write the value to permanent storage, but this value does not appear to exist.
On PX4, PARAM_SET writes the value to RAM and then immediately to permanent storage (a cached write).
This update is to reflect the actual behaviour.

Clarify that PARAM_SET is a permanent write

---

message_definitions/v1.0/common.xml

To monitor individual processes on the companion computer, the component ID enum has to be extended to include the process types which should be monitored over the heartbeat meassage.

add additional component_id fields for obstacle avoidance and VIO

---

message_definitions/v1.0/common.xml

If a camera sets `CAMERA_CAP_FLAGS_HAS_BASIC_ZOOM` in its capabilities flag, it tells us it can handle basic zoom functions and supports the `MAV_CMD_SET_CAMERA_ZOOM` command.
For the `MAV_CMD_SET_CAMERA_ZOOM` command, you either use Step (one step at a time) or continuous zooming (start/stop zooming). For step zoom, you define if its Tele or Wide using `param1` (-1 for wide or 1 for tele). The camera will move the zoom back or forward one step. For continuous zoom, you send the `MAV_CMD_SET_CAMERA_ZOOM` command with `param2` set to -1 to start zooming out (wide) or 1 for zooming in (tele). To stop zooming, you send a new `MAV_CMD_SET_CAMERA_ZOOM` command with `param2` set to 0.
The same idea applies to basic focusing. If a camera sets `CAMERA_CAP_FLAGS_HAS_BASIC_FOCUS` in its …

Work on video streams, camera zoom and focusing

---

message_definitions/v1.0/common.xml

As part of general push to get all common.xml entities documented, this pushes some proposed text for MAV_COMPONENT. The descriptions should cover how and when each value is used, and any exceptions. Ideally we should attempt to restrict use and intent so it is clear how it should be used and extended, and remove ambiguity that might later result in different uses. 
I have put in a bunch of placeholders for discussion. Please highlight anything you think should be more precise, or could cause potential issue.

Add MAV_COMPONENT documentation

---

message_definitions/v1.0/common.xml

The MAVLink frames typically use the WGS84 ellipsoid for horizontal co-ordinates (either scaled for use in INT or not) and and some other altitude reference. The current descriptions were confusing because the initial part of the description did not always mention the altitude was not part of the position frame. ie
> **Global coordinate frame, WGS84 coordinate system**. First value / x: latitude, second value / y: longitude, third value / z: positive altitude over mean sea level (MSL).
This PR changes the first part of the description to always mention the altitude reference:
> Global (WGS84) coordinate frame **+ MSL altitude**. ...
When the inputs are scaled this information is added (allowing the _INT to be differentiated)
> Global (WGS84) coordinate frame **(scaled)** + MSL altitude. …

Clarify global frames

---

message_definitions/v1.0/common.xml

Discussion originates in https://github.com/mavlink/mavlink/issues/929#issuecomment-446777948.
The airspeed in the HUD could be true airspeed, indicated airspeed, airspeed setpoint, etc etc. This clarifies that it is "indicated airspeed". This is definitely the case for ArduPilot, and I THINK it is also the case for PX4 (@dagar ?)
In addition, minor tidy removes units information from descriptions.

Clarify VFR_HUD.airspeed is IAS

---

message_definitions/v1.0/common.xml

This changes the default start index for a partial read/write of a mission from 0 to 1.
My reasoning is that mission sequences are indexed from 1 to count, not from 0 to count. Having 0 here would fetch the zero home value on ArduPilot, but is otherwise confusing because it implies that sequences normally start at zero.

Common.xml:Partial mission read/write startindex=1

---

message_definitions/v1.0/common.xml

There have been requested changes open from #1009. This is the follow up PR to address them as well.
- Add centisecond as unit to update_rate field
- Add missing display tag
Related to ArduPilot/pymavlink#242

Follow up PR for UTM_GLOBAL_POSITION

---

message_definitions/v1.0/common.xml

This adds a field telling the GCS the type of video stream for a given stream. In most cases, you don't "set" anything. The vehicle has a fixed type of video stream and it will tell you what it is. The field allows the GCS to use a proper pipeline for receiving and rendering the video stream.
In addition, I've also added a flag telling if the stream supports zoom. As streams are decoupled from "cameras" (which have their own API), if your system has video stream with zoom support but no other "camera" feature (image/video capture, etc.), there is no way to let the GCS know the stream handles zoom.
@julianoes, another change in the structure. I'm implementing this in QGC (basic, experimental support is already in master).
Note that this is unrelated to #885 as this is only for …

Allow defining stream type.

---

message_definitions/v1.0/common.xml

This provides support for a variant of `MAV_CMD_DO_JUMP` that instead uses relative indexes. The motivation for this is when working with a complex mission a jump may make the most sense in a local contect (IE go back 4 waypoints), and having to remember to edit the jump target on the absolute command when you delete an earlier unassociated waypoint is a problem. Similarly it's not actually clear if a jump index should automatically be adjusted by a GCS in this scenario either. By allowing an explicit relative mode of jumping a user can plan for this case easily.
This could have been a flag on the existing jump command, but it was thought to be easier to drop into most GCS/UI's more easily as a seperate command, allowing a distinct visual styling. (It also allows a way to ensure that a …

common: Add a relative jump command

---

message_definitions/v1.0/common.xml

The WHEEL_DISTANCE is the first of a set of rover messages intended to allow easier integration of ground vehicles.

Add rover message to common.xml

---

.travis.yml

Fixes #1051
Tests are failing on Python 3.3 due to lxml dependency no longer supporting that version. IMO 3.3 is a legacy test platform superseded by Python 3.5 - there is no real need to continue to support it.

Remove tests on Python 3.3

---

message_definitions/v1.0/common.xml

This adds MAV_MISSION_OPERATION_CANCELLED to allow a system to report that the current operation has been cancelled. This might be returned as a response to any request.
I've tidied up the rest of the enum text too. 
Note, this is irrelevant to ArduPilot which does not support cancellation (just times out). It is relevant to PX4 and other systems, which will otherwise return a spurious error.

Add MAV_MISSION_OPERATION_CANCELLED

---

message_definitions/v1.0/common.xml

I've moved the video streaming commands and messages into the fold of the camera API. What that means is that now a "camera component" is responsible for video streaming handling. The existing video streaming commands and messages are somewhat the same but now they are targeted to a camera component ID.
If a camera supports video streaming, it tells you by settings `CAMERA_CAP_FLAGS_HAS_VIDEO_STREAM` in its capabilities flag. When the GCS detects this flag, it will send a `MAV_CMD_REQUEST_VIDEO_STREAM_INFORMATION` command to the camera. From then on, all video streaming discovery and setup is done automatically.
A vehicle may contain 0 to many cameras (the total will depend on component ID availability as each camera has its own component ID). Each camera may contain up to 255 video …

Video streaming is now part of the camera API

---

message_definitions/v1.0/common.xml

I learned today that the VTOL takeoff command includes the transition to forward flight. Let's document that.

common: improve description of VTOL_TAKEOFF cmd

---

message_definitions/v1.0/common.xml

The mode field of HIL_ACTUATOR_CONTROLS is used by eg px4_sitl as a bit mask, and should be defined as such. 
Ref https://github.com/tstellanova/rust-mavlink/issues/1

Mode field of HIL_ACTUATOR_CONTROLS is commonly used as a bitmask 

---

message_definitions/v1.0/common.xml

This updates description of the port field used to differentiate between "banks of servos/channels" in RC_CHANNELS_SCALED, RC_CHANNELS_RAW, SERVO_OUTPUT_RAW to recommend particular values for the known ports on Pixhawk. It does not attempt to define for other systems.
Specifically 
- it removes the comment "Most MAVs will just use one, but this allows for more than 8 servos." (not necessarily true, but only the bit "allows for more than 8 servos potentially useful".
- Adds "Flight stacks running on Pixhawk should use: 0 = MAIN, 1 = AUX." - I think common for PX4 and ArduPilot
OK @auturgy @bkueng ?

SERVO_OUTPUT_RAW et al port mapping clarification

---

message_definitions/v1.0/common.xml

I propose adding a charging state of the battery.
This enum value would be useful for systems with automatic charging stations.

Add MAV_BATTERY_CHARGE_STATE_CHARGING

---

examples/linux/mavlink_udp.c

You're passing uninitialised memory to recvfrom() this is very bad, as this can cause the packages to be cut off.
From [man recvfrom](https://linux.die.net/man/2/recvfrom):
> The argument addrlen is a value-result argument, which the caller should initialize before the call to the size of the buffer associated with src_addr, and modified on return to indicate the actual size of the source address. The returned address is truncated if the buffer provided is too small; in this case, addrlen will return a value greater than was supplied to the call.

Use of uninitialised memory

---

message_definitions/v1.0/common.xml

As discussed in https://github.com/mavlink/mavlink/pull/917#issuecomment-460896776 the DISTANCE_SENSOR.covariance variable need to be reverted.
Fixing this up properly should be done in https://github.com/mavlink/mavlink/pull/1047

Revert DISTANCE_SENSOR.covariance

---

message_definitions/v1.0/common.xml

This implements the messages/enum discussed in #988.
Minor delta since then 
- now have both `capacity_full` and `capacity_full_specification`
- The messages are marked `wip`
@LorenzMeier
- You indicated there might be more faults to [include from the spec](http://sbs-forum.org/specs/sbdat110.pdf)? These can be added as needed to the enum, which has plenty of spare space
- You also suggested `cell_offset`, `battery_id` might be changed to `uint16_t` so that voltage array will be ordered last, and may be truncated if empty. Is this something you still want?
Anyone else got any feedback?

SMART_BATTERY_* messages: Added

---

message_definitions/v1.0/common.xml

This adds a mavlink command to request a particular message back from a system (as suggested by @peterbarker here: https://github.com/mavlink/mavlink/pull/1073#discussion_r254929733). This is intended to request information that is occasionally needed/doesn't need to be streamed. It is like a one-shot version of MAV_CMD_SET_MESSAGE_INTERVAL.
Alternative is to update MAV_CMD_SET_MESSAGE_INTERVAL with a new parameter that does the same thing - but I don't think that is as clean.

Add MAV_CMD_REQUEST_MESSAGE

---

message_definitions/v1.0/common.xml

Minor modification to MAV_COLLISION_THREAT_LEVEL_HIGH message description.
-Fixed typo panicing -> panicking

Fixed typo

---

message_definitions/v1.0/common.xml

Update RSSI values in  [RC_CHANNELS](https://mavlink.io/en/messages/common.html#RC_CHANNELS), [RC_CHANNELS_RAW](https://mavlink.io/en/messages/common.html#RC_CHANNELS_RAW), [RC_CHANNELS_SCALED](https://mavlink.io/en/messages/common.html#RC_CHANNELS_SCALED) to same definition discussed in #1027 (note, RADIO_STATUS already updated).
Fixes #1027
@LorenzMeier @auturgy Please confirm you are happy with this. @auturgy as discussed, this will need to be updated in both PX4 and ArduPilot.

Update RSSI values to 0-254, 255=not used

---

message_definitions/v1.0/ASLUAV.xml

Add a message to transmit the useful information about the status of the SatCom link.
Currently this is only added to ASLUAV because we need to merge it quickly. However, if such a message would be useful for others we could add it as a v2 message to common.

Add SATCOM_LINK_STATUS status to ASLUAV

---

message_definitions/v1.0/common.xml

This is to enable support for deeper integration of external VIO/SLAM pipelines in real-world situations where they may reset and/or the estimate jump while in flight. (e.g when a SLAM system detects a loop-closure). 
The onboard estimator needs to know a reset occurred and appropriately handle it for robust flight control.
Please let me know if anyone can think of anything else we should add here. We have been flying with an equivalent change in a custom dialect, and I believe this is highly needed upstream to make VIO/SLAM a default feature.

common : Add reset counter to external estimation messages

---

message_definitions/v1.0/common.xml

[**don't merge**]
There has frequently been a mention of "Smart RTL" and similar things, where the drone does not only return based on battery capacity, but also the distance to home. I'm not working on smart RTL, but a feature that estimates the time to perform RTL and LAND actions given the current location. This can then be used to trigger RTL in time, in case the drone is far away from home. 
In my tests, the drone publishes a uorb message at 1Hz for the RTL/Land time estimates. 
Now, for a GroundStation to be able to display the remaining effectively remaining flight time, which is "battery-based remaining flight time" minus "RTL time estimate", we need to convey the data via mavlink. And I am not sure where it best belongs. 
The estimated time to perform RTL would in my opinion best …

[WIP] Added fields for RTL and LAND time estimates

---

message_definitions/v1.0/common.xml

This allows GCSs to parse the .xml files directly and extract all info required to present a GUI to the users.
No more need to manually update some (guessed) information on some local files specific to each GCS.
The information is now explicit and central in the XML files. No duplication, no guesswork!!!!
This should greatly improve the user experience on MissionPlanner and QGC. And reduce the workload for GCS developers, no need to add new code when a new message gets added, just re-parse the .xml flie and regenerate the .exe.

Common.xml: Add attributes to all MAV_CMD parameters

---

scripts/test.sh

we don't need bash, so I remove it.
It allow to work on default alpine docker images

scripts: remove bash dependency on test.sh

---

.travis.yml
scripts/test.sh

skip useless pymavlink installation.
Pymavink already get its autotest.
Moreover this prevent failure without message when .xml aren't valid as pymavlink try to build then for install.
At least, it allow docker build to use much small image as pymavlink gcc dependency isn't need anymore (save a lot of space, so that is greener ! ;-P )

script: skip pymavlink install

---

message_definitions/v1.0/common.xml

Follows from Slack discussion with @DonLakeFlyer @auturgy @LorenzMeier that there is no way to set that desired yaw setpoint is unchanged in current definition. This change is consistent with WAYPOINT command.
This is a WIP while we resolve how ArduPilot handles this case.

common.xml:Loiter* MAV_CMD set NaN for unchanged yaw

---

message_definitions/v1.0/common.xml

Following a [conversation here](https://github.com/mavlink/qgroundcontrol/issues/7434), I've added an enum to indicate the status of the (camera) storage. One more status was added: ~**None**~ **Not Supported**. That indicates that storage should be ignored (the camera is capable of functioning without it).
I've also added a description telling this message is not only sent in response to a request but also whenever the status of the storage changes. This is for notifying the GS of events such as microSD card inserted/removed, storage formatted, etc.

Adding an enum to storage info.

---

message_definitions/v1.0/common.xml

This adds a mission changed broadcast which a vehicle should send whenever the mission (or geofence or safe points) have changed.
Closes #1134.

common: add mission changed broadcast

---

message_definitions/v1.0/common.xml

This MAVLink v2 extension packet allows for flexible obstacle detection from multiple sensors of varying resolution while still being backwards compatible.
increment_f (to override increment):
When forced to send exactly 72 samples, having an integer spacing just didn't make sense. Needed to be float so that the correct angular range was understood
angle_offset:
Same as, and adds to, param "[PRX_YAW_CORR](http://ardupilot.org/rover/docs/parameters.html#prx-yaw-corr-proximity-sensor-yaw-correction)" in ArduPilot. However, if you have two sensors this woudl now allow you to send multiple messages covering different areas (at varying resolutions). For example, a 360 degree spinning lidar + long-range forward radar/lidar + wide angle sonar(s).
With multiple messages, we can aggregate a better …

OBSTACLE_DISTANCE: add higher angle resolution and angle offset

---

message_definitions/v1.0/common.xml

Units were missing. These are clearly bytes, so I will self merge.

LINK_NODE_STATUS.rx_parse_err: Clarify units

---

message_definitions/v1.0/common.xml

This PR assumes that overflows are measured in bytes. Please confirm.

Clarify LINK_NODE_STATUS.tx_overflows and .rx_overflow

---

message_definitions/v1.0/common.xml

Clarifies/cross links MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES and AUTOPILOT_VERSION.
This is what PX4 appears to do, and is also logical.
FYI @auturgy

Common.xml: Clarify MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES

---

message_definitions/v1.0/ASLUAV.xml
message_definitions/v1.0/common.xml

Based on the comments on  [PR #1106](https://github.com/mavlink/mavlink/pull/1106) I:
- renamed the SATCOM_LINK_STATUS to ISBD_LINK_STATUS (ISBD = Iridium Short Burst Data)
- gave it an id in the MAVLink2 range
I think it would be nice to have this message in common because it would represent the status of the iridiumsbd driver which is in pixhawk master and thus potentially be helpful for other people outside ASL.
However, I am open to suggestions and if you think it should not be in common we can leave it in the ASLUAV dialect.

Add ISBD_LINK_STATUS in common

---

message_definitions/v1.0/common.xml

Found a minor typo while looking through some message definitions: I assume "_Being_ following a target" should be "_Begin_ following a target". (https://mavlink.io/en/messages/common.html#MAV_CMD_DO_FOLLOW)
I felt it would be overkill to open an issue for this so there is no connected issue to this PR.

Fix typo in MAV_CMD_DO_FOLLOW description

---

message_definitions/v1.0/common.xml

This PR adds the ability to add the type associated with each waypoint e.g. land, takeoff.... 
This information is available also in the mission item however the two messages aren't synchronized in ROS.

add waypoint type extension to TRAJECTORY_REPRESENTATION_WAYPOINT

---

message_definitions/v1.0/minimal.xml

As discussed in https://github.com/mavlink/mavlink/issues/1175 , [PROTOCOL_VERSION](https://mavlink.io/en/messages/common.html#PROTOCOL_VERSION)  (and hence [MAV_CMD_REQUEST_PROTOCOL_VERSION](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_PROTOCOL_VERSION)) are mandatory to implement for a MAVLINK2 system.
Therefore they should be in minimal.xml. 
This PR is created to test this assumption. 
Notes/questions
- PROTOCOL_VERSION is marked wip in common - should this be removed?
- that the next step would be to strip the messages out of common.xml and include dialect in common. Any reason why not to do this?
- Would it be better to put the protocol methods in protocol_version.xml and include that?

Add PROTOCOL_VERSION and friends to minimal.xml

---

message_definitions/v1.0/common.xml

A non-flight controller component should have `HEARTBEAT.autopilot` and `HIGH_LATENCY2.autopilot` set to MAV_AUTOPILOT_INVALID.

common.xml: Set MAV_AUTOPILOT_INVALID for non-autopilots

---

doc/mavlink_to_html_table_gitbook.xsl

This moves the param lablels next to the index, if they exist. This is much more readable, and helps users see what the index is for. 
The old way is below. In this case all "GCS display hints" are displayed together.

MAV_CMDs - put param labels next to index

---

message_definitions/v1.0/common.xml

MAVlink message which allows a component to send specific, non-standardized data to another component. Addresses #1159 (Proposal for an opaque, tunnel message). 
In comparison to the proposal and/or the V2_EXTENSION message, I've made some changes:
* broadcast is not forbidden, but should be discouraged and not the normal use case
* I removed the target_network field, simply because I don't know what its use would be. If there is some use, it of course could/should be added,.
* I've changed the handling of the code for the encoding, i.e. payload_type, somewhat. Fundamentally only a registered number is required, so I've made it an enum. This also makes coding for implementers simpler since the enum is then already in the header ready to use. Since there is no example it isn't totally …

Opaque Tunnel message

---

message_definitions/v1.0/common.xml

at least I found the description of the MESSAGE_INTERVAL interface unclear (and in fact had implemented it incorrectly, in comparison to how it is used in ArduPilot). This PR attempts to make the description more clear.
If the suggested improved descriptions do not correctly describe how that interface is supposed to work, please advice.

MESSAGE_INTERVAL interface, improve description of its usage

---

message_definitions/v1.0/common.xml

Add five new Mavlink messages to match the content of the
Open Drone ID messages.
This will make it easy to transmit the relevant data for
Open Drone ID implementations, instead of sending
multiple Mavlink messages that only partly contains the
necessary data fields.
See also https://github.com/opendroneid/opendroneid-core-c

Add OpenDroneID messages

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

@edwinhayes @auturgy This replaces #1077 with an actual range of components in both common.xml and minimal.xml. Using individual IDs ensures that the range can't be used by accident in the same library build as common.xml or minimal.xml.
I'm OK to merge this. Any final thoughts?

Reserving component IDs for private components

---

message_definitions/v1.0/common.xml

Fixes #1179
Original unit of mT not usable for this purpose - any measured field would be of order of  0.065[mT], so would be rounded to zero. 
This changes to mgauss, which provides a value range of  (-2000 to + 2000) for common sensors. We could use nT as well as it is an SI unit but decided to use mgauss because it is a well understood unit that is used internally by ArduPilot already. The argument that nT give better resolution is true in theory, but in practise that resolution unlikely to be visible given likely noise.
@auturgy @julianoes As discussed in dev meeting. You OK to merge?

SCALED_IMUn: x,y,zmag units from mT to mgauss

---

message_definitions/v1.0/common.xml

Fixes #1187
As stated by @jlecoeur the `OPTICAL_FLOW.flow_comp_m_x` and `flow_comp_m_y` must either be velocity units or an integration time unit is required so that flow can be determined from these. Given there is no such integration unit it is very likely that people are assuming m/s OR that it is not being used. Either way, the "best" fix is to clarify m/s.
Still waiting for confirmation on linked item from @auturgy.

OPTICAL_FLOW.flow_comp_m_(x/y) units to m/s

---

doc/mavlink_to_html_table_gitbook.xsl

Fixes #1191
Adds links at start of body text which makes it easier to tell that something is a command or message.
If you click the link, you get taken to the top of the section. For commands you get some advisory text that explains that commands are not messages (the note below):

Add highlighting of item type

---

message_definitions/v1.0/common.xml

This clarifies that `MAV_TYPE` (`HEARTBEAT.type`) is the vehicle type for an FC and the component type for other components. 
This makes it easier for components, as they don't have to know at firmware build time what system they are used in. This will have no impact on QGC, and "should" not adversely impact other GCS.
Discussion here: https://github.com/mavlink/mavlink/issues/1152
Assuming this goes in, there is follow on work in the docs for [heartbeat protocol](https://mavlink.io/en/services/heartbeat.html).

Clarify MAV_TYPE usage

---

message_definitions/v1.0/common.xml

As discussed in #1179 and dev call, it is useful to be able to report multiple RAW_IMU. Rather than having separate messages (as for SCALED_IMUn) this adds the identity as an extension field.
Systems that do not understand the field will interpret a message as being for IMU1 even if it is from another IMU. We're expecting systems to update before this becomes a problem. 
@auturgy @julianoes As discussed in dev call. Is this OK to merge?

RAW_IMU: Add id extension to support multiple IMU

---

message_definitions/v1.0/common.xml

we would like to add a mavlink message for hardware status of system components. Mainly this would concern the companion computer. This message would enable monitoring the cpu usage, temperature etc. on the system. On the ground station side, such a message would allow to print warnings if the companion reaches a critical state. On the autopilot side the corresponding failsafe actions could be implemented. The message was named quite generically on purpose, such that it could also be used for other components, e.g. for a camera to report the storage situation or similar.

[WIP] add a message for component status reports

---

message_definitions/v1.0/common.xml

External pose as well as odometry information is almost never aligned with
earth's north and east directions. This adds a two new frames that are labeled with
FRD and FLU. With this we get rid of the ambigious usage of ENU and NED.
Additionally, this commit reduced the number of frames for external pose/odometry information.
The source for the information is now handled by an additional field in the odometry message.
The estimator type is extended to cover mocap and autopilot (fcu).
@TSC21 @mhkabir

Add non NED/ENU frames for external position

---

message_definitions/v1.0/common.xml

This improves wording of GPS_GLOBAL_ORIGIN and SET_GPS_GLOBAL_ORIGIN  (which I found a little confusing).
It also states what happens if setting the origin might fail - i.e. GPS_GLOBAL_ORIGIN should be sent even if setting a local origin failed (for whatever reason). This might not be agreeable to all users, but it is generally good practise. I created it so that we can remove ambiguity.
@auturgy @julianoes @nsteele

common.xml:GPS_GLOBAL_ORIGIN clarify when emitted

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

does two simple things
1. corrects the MAV_TYPE enum entry for a servo type to MAV_TYPE_SERVO (was SERVO, which looks like an obvious mistake to me)
2. grabs the occasion and makes the MAV_TYPE enum entries in minimal.xml match those in common.xml

Correct MAV_TYPE entry for servo

---

message_definitions/v1.0/common.xml

addresses #1220
EDITED (HamishW). The tunnel message is WIP, and Ollie is the person who championed it and is first implementer. This change makes sense and is not affecting stable messages.
EDIT (OlliW): Thx for the edit! I should have realized that it's important info that changing the message now won't do damage.

Tunnel message: add length field

---

message_definitions/v1.0/common.xml

adding component IDs for gimbal #2 to #6 is part of the PR [New gimbal messages](https://github.com/mavlink/mavlink/pull/1174), #1174, which however will very likely take some more time to be finalized and merged. 
It would be useful to have these additional gimbal component IDs being defined ASAP, so they could be used ASAP, hence this PR which takes that part out of #1174.

Gimbal Component IDs for Gimbal #2 to #6

---

message_definitions/v1.0/common.xml

This is useful information for the GCS and safety reasons. The main question I have is do we want a DNU value for this? (IE `INT16_MIN`) The downside to using a DNU is that if you don't have the extension you get 0, which is inband. We could also just declare 0 to be the DNU, and if you send a value of 0, then just add 1 to it, and accept the slight error.

Allow IMU's to convey their temperature

---

message_definitions/v1.0/common.xml

This integrates the non-controversial changes to clarify the terms without breaking any semantics. Ie the "bug fixes" in #1182.
@julianoes @auturgy As discussed in dev meeting yesterday.

SYS_STATUS - clarify value invalid voltage

---

message_definitions/v1.0/common.xml

Percentage not required in description (is in units). Changed DNU to clear description of "not used"

HIGH_LATENCY2: Tidy description

---

message_definitions/v1.0/common.xml

@dogmaphobic:
I think this was a typo. Can you confirm?
In addition, in https://groups.google.com/forum/#!msg/mavlink/9KrPARAMe1c/LRW6IPBHBAAJ there is a question:
> I would like to pass the focus distance in meters to the camera. But would this be focus type number 2, or maybe a new one?
My take is that we don't support this. Do we want to?

FOCUS_TYPE_RANGE: Typo

---

message_definitions/v1.0/common.xml

This adds a new value to the FENCE_BREACH enum, 'FENCE_LIMIT' = 4. 
This is to report when the autopilot is having to take action to prevent a fence breach, typically by limiting the velocity component in the direction of the fence.

common.xml: Add FENCE_LIMIT to FENCE_BREACH enum

---

message_definitions/v1.0/common.xml

Add FOCUS_TYPE_METERS and ZOOM_TYPE_FOCAL_LENGTH to respective enums, as discussed in 
https://github.com/mavlink/mavlink/pull/1224#issuecomment-531091300
This does not add messages to get the focal range/zoom/etc from a camera. IMO that probably should be done - because otherwise IMO the mechanisms for setting these outside of parameters may not be worth having at all. And while I understand this could quickly get complicated, adding ranges for video and camera does not seem too scary (and addresses the 80% of likely use).
If you agree can you add range-getting messages either in their own PR or this one?

FOCUS_TYPE_METRES - add

---

message_definitions/v1.0/common.xml

kindly asks to register 10 tunnel payload codes for the STorM32 gimbal controller project.
Follows the suggested rules for registration outlined here: https://github.com/mavlink/mavlink/issues/1225#issuecomment-529075395
<strike>In contrast to the suggested rules, which suggest a default block of 25 codes, I here ask for only 10 codes. Main reason is that I don't want to blow up the documentation web page with a that long enum. </strike> EDIT: default size was settled to 10

Register 10 tunnel payload codes for STorM32

---

message_definitions/v1.0/common.xml

adds a default component ID for a tunnel communication partner node.
For the rational pl see https://github.com/mavlink/mavlink/issues/1225#issuecomment-529074833.

Add component ID for a TUNNEL node

---

CMakeLists.txt

In https://github.com/mavlink/mavlink/pull/835 the 0.9 message files were already removed. This PR cleans up the CMakeLists.txt as otherwise you get this error message while building:
```
Scanning dependencies of target test.xml-v0.9                                                 
[ 11%] Generating test.xml-v0.9-stamp                                                         
Validating /home/dummy/Development/mavlink/message_definitions/v0.9/test.xml    
Traceback (most recent call last):                                                            
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code               
exec code in run_globals …
```

removed 0.9 messages from cmake

---

message_definitions/v1.0/common.xml

Multiple changes to the message fields and new messages were added in version 0.8 of the OpenDroneID specification. This PR aligns the Mavlink messages.
The OpenDroneID specification is basically frozen but you never really know so let's keep the WIP tags for the time being.

Update OpenDroneId messages to match version 0.8 of the specification

---

message_definitions/v1.0/common.xml

Generalised forced arm/disarm.
The current text is confusing because it refers mainly to enabling in-flight disarming. I believe this is a better interpretation - essentially that the magic number simply forces arming/disarming irrespective of other checks.
This may make some flight stacks only partially compliant. For example, I know that PX4 implements force disarm in flight, and that will still be valid. But this requires that it also supports force arm even if preflight checks fail, so might not be compliant in that sense.
Discussion comes from https://github.com/mavlink/qgroundcontrol/issues/6624#issuecomment-537243404

MAV_CMD_COMPONENT_ARM_DISARM: Clarify forced arm/disarm

---

message_definitions/v1.0/common.xml

Follows on from https://github.com/mavlink/mavlink/issues/1244
0 ids are use to indicate broadcast address and should not be used as the source address of a component. If you did this a component could not be separately addressed as all systems would think the message was intended for them. In addition, if such a component sent a command the ACKs would go to all other systems.

MAV_COMPONENT: Clarify broadcast ID only used for targets

---

message_definitions/v1.0/common.xml

[GLOBAL_VISION_POSITION_ESTIMATE](https://mavlink.io/en/messages/common.html#GLOBAL_VISION_POSITION_ESTIMATE) and [VISION_POSITION_ESTIMATE](https://mavlink.io/en/messages/common.html#VISION_POSITION_ESTIMATE) are identical. It seems likely that `VISION_POSITION_ESTIMATE` is actually intended for local estimates. 
@jkflying @TSC21 Can you please confirm this was the intention - and that therefore this change can be merged.

VISION_POSITION_ESTIMATE is local estimate

---

message_definitions/v1.0/common.xml

There was a question about whether [ACTUATOR_OUTPUT_STATUS](https://mavlink.io/en/messages/common.html#ACTUATOR_OUTPUT_STATUS) is actuator feedback. This clarifies that it is PWM outputs, and that it supersedes the earlier message `SERVO_OUTPUT_RAW`.

common:ACTUATOR_OUTPUT_STATUS: Clarify is PWM outputs

---

message_definitions/v1.0/common.xml

[edited]:
The new field is a rotation offset by which the attitude quaternion and angular speed vector should be rotated for user display (quaternion with [w, x, y, z] order, zero-rotation is [1, 0, 0, 0], send [0, 0, 0, 0] if uneeded).
This field is intended for systems in which the reference attitude may change during flight. For example, tailsitters VTOLs rotate their reference attitude by 90 degrees between hover mode and fixed wing mode, thus repr_offset_q is equal to [1, 0, 0, 0] in hover mode and equal to [0.7071, 0, 0.7071, 0] in fixed wing mode.
Related issues:
- https://github.com/mavlink/qgroundcontrol/issues/3849
- https://github.com/PX4/Firmware/issues/5291 
- https://github.com/PX4/Firmware/issues/9179
- https://github.com/PX4/Firmware/issues/10405
Matching PR for PX4 and …

Extend ATTITUDE_QUATERNION for correct display of attitude with tailsitters

---

message_definitions/v1.0/common.xml

This adds new definitions:
- play a tune: PLAY_TUNE_V2.
- query what tune formats are supported: SUPPORTED_TUNES
- enum for known tuneformats QBasic 1.1 and Modern MML
It also deprecates PLAY_TUNE
With this a GCS/SDK can query a to work out what tune/tunes. Default format is assumed to be QBasic 1.1.
Fixes https://github.com/mavlink/mavlink/issues/1251.

PLAY_TUNE_V2: New tune messages

---

message_definitions/v1.0/common.xml

This clarifies the meaning of possible results ([MAV_RESULT](https://mavlink.io/en/messages/common.html#MAV_RESULT)) of a command (in a [COMMAND_ACK](https://mavlink.io/en/messages/common.html#COMMAND_ACK)) to remove ambiguity on which should be used in what circumstance.

MAV_RESULT: Clarify exactly what the possible results mean

---

message_definitions/v1.0/common.xml

Fixes #1248.
As discussed in #1248 many messages are intended to be broadcast and if you request them, they will be broadcast. However some messages have target address in them so can either be broadcast or sent to a specific target.
This update repurposes parameters such that a user can explicitly specify that the target address of the response is broadcast or the address of the component that requested the message/stream. 
By default the message will be sent with 0, which is "whatever the flight stack wants to do".

Clarify target address for requested message/stream

---

message_definitions/v1.0/common.xml

This is a change to the new fence mitigation enum to include Unknown mitigation action, this came about after a discussion on the ArduPilot dev-call about my ArduPilot PR to make use of the new extension.
https://github.com/ArduPilot/ardupilot/pull/12536
https://github.com/ArduPilot/mavlink/pull/108

common.xml: update extended fence status message

---

message_definitions/v1.0/common.xml

Extends param index 3 of `MAV_CMD_DO_ORBIT` with a new option for the heading behaviour in Orbit mode that allows the vehicle to keep its heading forward while executing the flight following the orbit circle. Will follow a PR to PX4 with support for it. QGC to come later.
@dayjaby FYI.

common: MAV_CMD_DO_ORBIT: add new option for heading behaviour (param index #3)

---

message_definitions/v1.0/common.xml

This adds a AIS message and the relevant enums. This message is an attempt to cover the two most common AIS messages. Position reports and Static and Voyage Related Data, see: https://gpsd.gitlab.io/gpsd/AIVDM.html 
I have attempted to only include the information from these messages that would be useful, there is quite a bit left out, such as vessel destination and ETA. I have, for the most part left the values in the units they arrive in over AIS, ie knots not m/s (could easily be persuaded to change this). I have added bits to the flags enum for magic values. For example in AIS turn rate is quite complex: 
- 0 = not turning
- 1…126 = turning right at up to 708 degrees per minute or higher
- 1…-126 = turning left at up to 708 degrees per minute or higher
- 127 = turning right at more …

common.xml: add AIS message

---

message_definitions/v1.0/common.xml

- MAV_CMD_REQUEST_COMPONENT_INFORMATION added, mirrors MAV_CMD_REQUEST_CAMERA_INFORMATION
- COMPONENT_INFORMATION message added, mirrors CAMERA_INFORMATION to a large extend, but has also a hardware version field. COMPONENT_CAP_FLAGS are currently not defined.
- both were given the tentative ids 700

COMPONENT_INFORMATION

---

message_definitions/v1.0/common.xml

This PR replaces the RGB version proposed in #1272  that got way out of hand for the use-case I'm targeting.
This is supposed to be a light-weight command to turn a light on board of an MAV on or off. No more, no less

Add illuminator on/off command

---

message_definitions/v1.0/common.xml

This adds a couple of additional ADS-B flags. These have been shipping with uAvionix hardware for awhile, so this meaning is already present and deployed in the field, and the validity flags have a lot of value to be receiving either way.

Update ADS-B flags

---

message_definitions/v1.0/common.xml

For MAV_CMD_DO_REPOSITION the scaling depends on whether it is being sent as a
COMMAND_LONG or COMMAND_INT, so it should not be mentioned explicitely.
FOr MAV_CMD_DO_MOUNT_CONFIGURE the same applies. Important here is to update the implementation in PX4, as param1-3 are being used there for longitude/latitude/altitude.

Remove the mentioning of 1E7 scaling

---

message_definitions/v1.0/common.xml

This allows us to request messages using MAV_CMD_REQUEST_MESSAGE where the value of the returned message can be conditional on values passed to the target system.
In most cases message don't depend on parameters and the new params should be set to zero. In cases where parameters are expected, the values of the params must be specified in the message that is requested.

MAV_CMD_REQUEST_MESSAGE: Define that parameters can be used

---

CMakeLists.txt

- Mavlink 2.0 is built from v1.0 folder
- Build both MavLink 1.0 and Mavlink 2.0 C libraries
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

CMakeLists: Allow mavlink v2.0 build and installation

---

message_definitions/v1.0/common.xml

Follows on from https://github.com/PX4/px4_user_guide/pull/642
Waypoints yaw to specified param4 value. Previously docs stated that NaN means unchanged, but in practice flight stacks actually have a typical behaviour and NaN reverts to it. This clarifies that the NaN behaviour is system dependent.

common: Missions obey system yaw behaviour on Nan

---

CMakeLists.txt

Hi,
Can we set MAVLINK_SOURCE_DIR to PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR so that building as a subdirectory works? Otherwise MAVLINK_SOURCE_DIR incorrectly points to the top level project directory instead of the mavlink directory and cmake fails.
- Jacob

PROJECT_SOURCE_DIR for MAVLINK_SOURCE_DIR

---

message_definitions/v1.0/common.xml

This has already been merged into ArduPilot's `common.xml`.
The three PRs mentioned below have been merged (or an equivalent merged in the case of the ardupilot mavlink PR).
GCS-developers announcement:
```
All,
We look to be merging some mavlink2 extensions into ArduPilot's STATUSTEXT message.  The extensions allow a GCS to (optionally) reassemble a very long message from the autopilot into a single logical message.
The PR into ArduPilot is here: https://github.com/ArduPilot/ardupilot/pull/13039
The PR into ArduPilot's mavlink repository is here: https://github.com/ArduPilot/mavlink/pull/118
The PR into MAVProxy to add support for the extensions is here: https://github.com/ArduPilot/MAVProxy/pull/718
If a message would entirely fit within 50 characters then on-wire there's no changes …
```

common.xml: add chunks for statustext

---

message_definitions/v1.0/common.xml

Currently, there are two ways to report battery voltage over MAVLink: `SYS_STATUS` and `BATTERY_STATUS`. `SYS_STATUS` only has one field for each battery value, so if there are multiple batteries in a system, there is ambiguity. There is discussion about this in https://github.com/mavlink/mavlink/pull/1182.
To solve this ambiguity, a vehicle can send multiple instances of `BATTERY_STATUS`, with different values for `id`. This is how PX4 currently does it.
In `BATTERY_STATUS`, there is the `voltages` field for sending individual voltages of each cell of the battery. This is useful for 'smart batteries' and other power monitors that can monitor individual cells. However, many power monitors cannot do this; they can only measure the overall voltage of the battery. 
This PR updates the …

Edit documentation to handle case where cell voltages are not measured

---

message_definitions/v1.0/common.xml

This change would allow to report the healthiness and use of different avoidance components from the fight controller to the ground station with a single message. For example in PX4 we have the Collision Prevention working in manual modes and Obstacle Avoidance working in auto modes. This message would report to the ground station if any of the avoidance systems is functional in the flight mode the vehicle currently is. The ground station can simply check the SYS_STATUS message to display the information to the user.

add avoidance sys_status

---

message_definitions/v1.0/common.xml

Fixes #1286 
This attempts to address #1286 by clarifying that `NaN` and `INT32_MAX` may be used in MAV_CMD params to indicate optional/default values - e.g. a taking yaw from vehicle position rather than the specified value. 
I cover `MISSION_ITEM`, `MISSION_ITEM_INT` and `MAV_CMD`.
I don't cover the implication that if you explicitly specify INT32_MAX for param 5 (say) you are mandating the command is only use in an integer-based message. 
Do we need to update COMMAND and COMMAND_INT?
@auturgy FYI

common: NAN and INT32_MAX for default param values

---

message_definitions/v1.0/common.xml

We would like to use a flag marked for future use to indicate that lockstep is being used. This means that simulators can be configured automatically instead of needing a config argument.
This was first proposed by @lovettchris in https://github.com/PX4/Firmware/pull/13442.

Add flag to indicate simulation with lockstep

---

message_definitions/v1.0/common.xml

This is the follow up to the [discussion on the dev call](https://github.com/mavlink/mavlink/wiki/20190515-Dev-Meeting#call-1) where the overall opinion was to deprecate the existing mount/gimbal messages and come up with a new/consistent set.
I also had further helpful discussions with @olliw42, for details see #1130 and #1135.
**This PR/proposal has evolved quite a bit over time. There is a [document for the high level description](https://docs.google.com/document/d/16pekKRXLN2FhlL9YNFP983cjfBKAsDwN0gOSks8USo4/edit?usp=sharing).**

New gimbal messages

---

message_definitions/v1.0/common.xml

I did the final smaller edits needed to align the message definitions with the final ASTM Remote ID standard.
I have uploaded some documentation here:
https://github.com/mavlink/mavlink-devguide/pull/220
Once that PR is approved and merged, I assume we should be able to remove the Work in Progress marks as well?

Update according to the final ASTM Remote ID standard and remove WIP

---

message_definitions/v1.0/common.xml

The NONE flag is required to stop a previously set command. This somehow got lost previously but came up when writing the docs of the new gimbal protocol.

gimbal: add missing flag to stop previous command

---

message_definitions/v1.0/common.xml

In order to test failsafe mechanisms it would be nice to be able to inject failures using a command.
Note that for safetey and security, autopilots should only accept such a failure injection command if this has been specifically enabled using e.g. a parameter or even a flag set at build time.
This commit is just a first suggestion how this could look like and in no means exhaustive.

Add failure injection command with enums

---

message_definitions/v1.0/common.xml

Removes `bitmask="true"` attribute from the FAILURE_UNIT and FAILURE_TYPE enums as noted in https://github.com/mavlink/mavlink/pull/1331

common> FAILURE_UNIT / _TYPE are not bitmasks

---

message_definitions/v1.0/common.xml

the GIMBAL_MANAGER_SET_ATTITUDE messsage is missing a parameter to specify gimbal device ID, this PR adds it.

Add gimbal device id param to gimbal_manager_set_attitude

---

message_definitions/v1.0/common.xml

It seems like this rotation is missing.
These are equivalent:
ROLL_270_YAW_180
PITCH_180_ROLL_270
YAW_180_ROLL_90
FYI @jinchengde @nicovanduijn.

common: add missing SENSOR_ORIENTATION

---

message_definitions/v1.0/common.xml

As discussed in the Dev call, these messages are duplicates of existing frames that have the origin component in the name. This is not how MAVLink works - if origin is needed this should come from a component id (and ideally the information should be formatted so that the origin is not even relevant).
Action is to mark these as reserved and deprecated.

MAV_FRAME:Deprecate component-specific frames

---

message_definitions/v1.0/common.xml

Shouldn't have any end user implications.

Fix typo: MAV_COMP_ID_USE16 > MAV_COMP_ID_USER16

---

.github/stale.yml

The stale bot is great to remind us to follow up but I think the stale bot should not auto-close issues and PRs because:
- We might miss important things that were closed.
- We can no longer find issues that we remembered to be there because they have been closed but not actually resolved.
- It creates a lot of noise in the comments because we have to keep deleting the stale bot's comments or shout against the bot.
Instead, I think, it is good to have the stale label as a reminder when it appears the first time and also as a way to search for old issues to go through them and close them if it makes sense.
Also, this PR reduces the time for something to be stale to 2 months.

Stalebot: don't auto-close issues

---

message_definitions/v1.0/common.xml

There was previously no formal way to markup reserved parameters and define their default. The definition is now such that:
- if you omit a parameter then it is considered reserved with a default of zero
- you can mark up a parameter as reserved with a default of NaN using: `<param index="3" reserved="True" default="NaN" />`
This PR updates the small number of params that previously just stated "all params are NaN".
Note, params 5,6 also marked as reserved/NAN. This means the message can ONLY be sent in the float variant of the command, because obviously you can't have a NaN in an int field.

Markup reserved values with NaN default values

---

message_definitions/v1.0/common.xml

@DonLakeFlyer This fixes #822, making it possible for an autopilot to report if the mission has too many items - such that the stored mission might not match the uploaded mission. What you wanted?
@auturgy FYI, this should be good for ArduPilot, which I understand may just overwrite the last item if it runs out of space.

Add MAV_MISSION_TOO_MANY_ITEMS

---

message_definitions/v1.0/common.xml

This was just added, but appears to duplicate the purpose of MAV_MISSION_NO_SPACE. Removing. Can re-add if justification provided

Remove MAV_MISSION_TOO_MANY_ITEMS

---

message_definitions/v1.0/common.xml

Hi, I would like to add new MAVLINK message for RPM data. This message is related to TFRPM01A sensor implemented in PX4 PX4/Firmware#14018. It can be used with other RPM sensors or for broadcasting RPM from some CAN ESC.
RAW_RPM
```
uint64 timestamp
float32 indicated_frequency_rpm       # indicated rotor Frequency in Revolution per minute
float32 estimated_accurancy_rpm       # estimated accurancy in Revolution per minute
```
Plese, I'm not sure about message ID.

Add RAW_RPM message

---

message_definitions/v1.0/common.xml

Adding wip tag until this has an associated implementation. Allows us to change if it proves we didn't think about this clearly.

Add wip to RAW_RPM

---

CMakeLists.txt

Ubuntu Focal Fossa no longer ships a `python-future` package, which motivates a switch to Python3
This PR adds a CMake option (USE_PYTHON3) for enabling building using Python3 for mavgen.
- set it default USE_PYTHON3=ON for versions of CMake that have find_package(Python3) and USE_PYTHON3=OFF for older versions

Add option to use Python3 in CMake

---

message_definitions/v1.0/common.xml

This specifies how to answer to LOG_REQUEST_LIST if there is no log available. Without this response to signal that there is no log file the requester has to assume there was a timeout and try again and again.
This is already the implementation in PX4 and from code inspection ArduPilot seems to do the same.

common: fix ambiguity in LOG_REQUEST_LIST

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

Old verions, param 2 was "hard coded" to use for index. This change it to be a "hint" that it should be used for index, but can be used for anything.
This breaks nothing, and allows more natural use of param2

MAV_CMD_REQUEST_MESSAGE: param 2 is multi-use too

---

message_definitions/v1.0/common.xml

The "airspeed" field in VFR_HUD should be equal to the calibrated airspeed (CAS) if available, as that is corrected for sensor/pitot and placement errors. If no CAS is available IAS (indicated airspeed) can be used.

VFR_HUD: edit airspeed comment to also allow CAS if available instead of IAS

---

message_definitions/v1.0/common.xml

The message should be ignored by multicopters etc. This was discussed in #1377 and agreed in todays dev call.

CMD_NAV_VTOL_TAKEOFF: Clarify message only for VTOL (not MC)

---

message_definitions/v1.0/common.xml

This clarifies that if a vehicle supports multiple modes (e.g. like a VTOL quadplane) then the takeoff command should do so in the current mode. The alternative is that it should switch to the VTOL/multicopter mode everyt time before takeoff. This behaviour is I believe the "standard" for both ArduPilot and PX4.
We should similarly define how  vehicles should behave for MAV_CMD_NAV_VTOL_TAKEOFF. We could define as:
- should only be used on vehicles that support both vtol and fixed wing flight.
- can be used on any vtol vehicle, but ignore transition heading parameter.
- can be used on any vehicle but ignore irrelevant parameters (heading and yaw). 
Note, the specific behaviour we choose not as important as consistent experience for GCS users.
Thoughts? @auturgy @julianoes ?

TAKEOFF - clarify behaviour on VTOL

---

message_definitions/v1.0/common.xml

This undos the deprecation and rename of MAV_FRAME_BODY_FRD in #1112, for the reasons given in the comment: https://github.com/mavlink/mavlink/pull/1112#issuecomment-625050092. 
Essentially this is still needed and should not have been marked deprecated. I am self merging to get this in.
@FYI @kamilritz @julianoes

Remove deprecation/rename of MAV_FRAME_BODY_FRD

---

message_definitions/v1.0/common.xml

I want to add a message for doing telemetry messages used for on board electrical generators such as alternators, generators, fuel cells, solar cells.
I tagged it WIP for now, not sure if this is the right thing to do.

common: added generator status message

---

message_definitions/v1.0/common.xml

resolves https://github.com/mavlink/mavlink/issues/1384
since it's an oversight I deprecated retrospectively

deprecate DO_MOUNT_CONFIGURE

---

message_definitions/v1.0/common.xml

this is rain-check to see if the changes are acceptable, what was done is:
* Adding labels for lat/lon/alt params
* rename params description to unify names ('RESEREVED' to 'Reserved', 'Reserved, send 0' to 'Reserved (set to 0)', 'sysid' to 'System ID', etc)
more changes can/should be done, like:
* adding units to the metadata, 
* add labels to all of the params
* adding units, minValue, maxValue, enum, increment
and so on

some MAV_CMD metadata updates

---

message_definitions/v1.0/common.xml

Problem:
- there is no way to determine the current image count that could be used if any [CAMERA_IMAGE_CAPTURED](https://mavlink.io/en/messages/common.html#CAMERA_IMAGE_CAPTURED) messages were lost.
- camera_index field in CAMERA_IMAGE_CAPTURED specifies that image count is reset at arming. This doesn't allow implementation of a persistent photo log that could be produced combining several flights.
This PR adds image_count field to CAMERA_CAPTURE_STATUS message. Implementation of camera manager can use this field to implement persistant photo log and remotes can request missing entries with MAV_CMD_REQUEST_MESSAGE.
Persistent photo log image count can be reset with added parameter for  MAV_CMD_STORAGE_FORMAT command.
Definition of image_index was changed so that arming is not mentioned …

Add image count field to CAMERA_CAPTURE_STATUS message.

---

message_definitions/v1.0/common.xml

If one wants to simulate multiple GPS inputs from simulation, and using the same messaging structure, i.e., `HIL_GPS` messages, we need a field that identifies the sensor source so it can be properly handled and logged in the autopilot side.
An alternative could be use `GPS_INPUT` instead of `HIL_GPS`, but then we would be using messages which purpose is not really to be used as simulation in/outputs.

common: HIL_GPS: extend with an ID field

---

message_definitions/v1.0/common.xml

Other then for the MAV_CMD_NAV_LOITER_ALT, for MAV_CMD_NAV_LOITER_TIME there was no possibility to add a "heading wait" requirement. In my opinion this field should be consistent for both of these loiter types.

MAV_CMD_NAV_LOITER_TIME: add Heading Required field

---

message_definitions/v1.0/common.xml

This change is a follow up on PR: https://github.com/mavlink/mavlink/pull/1362
The change adds an additional mode `WIFI_CONFIG_AP_MODE_DISABLED` to the WiFi Mode enum `WIFI_CONFIG_AP_MODE`.

Add additional WIFI_CONFIG_AP_MODE that allows to disable WiFi

---

message_definitions/v1.0/common.xml

This clarifies what exactly is meant by "reset image count" in MAV_CMD_STORAGE_FORMAT to mean both the CAMERA_CAPTURE_STATUS.image_count and CAMERA_IMAGE_CAPTURED.image_index [you have to do both, or subsequent captures will result in a mismatch].
This is needed because otherwise the words "image count" mean very little in the context of this message.
FWIW it does feel a bit odd to use this message to reset a count value, but I don't have a better option to offer.
@MatejFranceskin Can you confirm this matches your intent?

MAV_CMD_STORAGE_FORMAT - clarify reset of image count

---

message_definitions/v1.0/common.xml

It seems to me that there is no EKF_STATUS message anymore, but that it has been replaced with  ESTIMATOR_STATUS. So the description in ESTIMATOR_STATUS_FLAGS would be wrong.
Pl double check if I'm not just running wild. :)

Correct description in ESTIMATOR_STATUS_FLAGS

---

message_definitions/v1.0/common.xml

Adds a relevant field to the `distance_sensor` message, representing the quality of the sensor signal. If the sensor is external to the flight controller, meaning, not a device connected to the flight controller board and having the reading processed in a driver, but instead connected to a companion computer, even more relevant it becomes to have a way of sending this data, considering we are to process the raw data in the flight controller side. The inverse direction stream, meaning from the flight controller to a ground station for example, is also relevant for sensor debugging. For the simulated sensors, which data is being streamed using MAVLink, this is also a relevant field.
Solves https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L719.

common: distance_sensor: add signal_quality field

---

doc/mavlink_gitbook.py

mavlink_gitbook: fix typo in generated output

---

message_definitions/v1.0/common.xml

Updates for new COMPONENT_INFORMATION support

---

message_definitions/v1.0/common.xml

Fixes overly long param label reported here: https://github.com/mavlink/mavlink/pull/1390/files#r443375793

Fix up MAV_CMD_STORAGE_FORMAT.param3 label

---

message_definitions/v1.0/common.xml

Fixes #1285
To progress this, have created PR. Docs will have to be updated too. Original description below
----
As it currently stands there is a hole in the mavlink spec with respect to _INT usage. There is a capability bit on the vehicle side. But there is no clear way to know whether the GCS side will support uploads of MISSION_ITEM_INT items. The only sideways sort of way to do that would be for the vehicle to remember if the GCS did a MISSION_REQUEST_INT. To both deal with that and remove complexity from the mavlink spec I propose a breaking change to only allow support for the _INT variants of the protocol.
* This would mark MISSION_ITEM, MISSION_REQUEST and MAV_PROTOCOL_CAPABILITY_MISSION_INT as deprecated.
* A gcs is required to support the _INT based protocol sequence.
* If a …

Deprecate all non MISSION_*_INT usage

---

message_definitions/v1.0/common.xml

@julianoes @auturgy This adds message to cancel a long running command, as suggested by @LorenzMeier 
The message just takes a target sysid and compid, and the command being cancelled (not strictly needed if concurrency not supported, but a good check to make).
I don't have to implement this, so important you check the logic.
Essentially the sequence continues with progress updates until it completes - with one of acceptance, failure or cancellation. If the cancel message was sent, received and obeyed the flow would look like this.
[![](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtO1xuICAgIHBhcnRpY2lwYW50IEdDU1xuICAgIHBhcnRpY2lwYW50IERyb25lXG4gICAgR0NTLT4-RHJvbmU6IENPTU1BTkRfTE9ORygpXG4gICAgR0NTLT4-R0NTOiBTdGFydCB0aW1lb3V0XG4gICAgRHJvbmUtPj5HQ1M6IENPTU1BTkRfQUNLKHJlc3VsdD1NQVZfU …

Add COMMAND_CANCEL - message to cancel long running commands

---

message_definitions/v1.0/common.xml

@TSC21 I've been having a discussion with @julianoes on long running operations here: https://github.com/mavlink/mavlink-devguide/pull/243#discussion_r435564953
This changes the behaviour on the upgrade message based on the result of that discussion. Essentially it says that:
-  if you cancel a message the system should respond with MAV_RESULT_CANCELLED
- restarting shouldn't be allowed - you'd cancel the operation and then run a new update. 
This provides a far more predictable behaviour for the state machine for the generic case.
Julian, does not need to merge immediately - I did this now so that Nuno is aware of change before implementation done.

MAV_CMD_DO_UPGRADE: Align with thinking on long running ops

---

message_definitions/v1.0/common.xml

does https://github.com/mavlink/mavlink/issues/1376
for the units in GIMBAL_MANAGER_SET_TILTPAN I have chosen rad and rad/s. This is in contrast to the units in the MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN command, which uses deg and deg/s. 
Since GIMBAL_MANAGER_SET_TILTPAN is also a "high level" API like MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN one might argue that deg would be better than rad, but I went with rad here since rad is used also in the GIMBAL_MANAGER_INFORMATION message.
in MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN I also did some changes in the descriptions in the field,to make things more uniform across the series of GIMBAL_XXX messages/commands.

add GIMBAL_MANAGER_SET_TILTPAN, rename MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN

---

message_definitions/v1.0/common.xml

Currently there is no mavlink message to enable configuring cellular modems.
This message is required to configure the cellular model information.
The information includes
- APN
- PIN numbers
- Puk codes
- enabling /disabling pins
- enabling /disabling roaming
- black listing bands

Define cellular config messages for configuring Modems

---

message_definitions/v1.0/common.xml

The current definition of mavlink fails to provide sufficient information to make use of cellular communications as a datalink. This PR improves the `CELLULAR_STATUS` message to improve monitoring / diagnoising  cellular modems.
The summary of the improvements include
- Extension of enum of `CELLULAR_STATUS_FLAG` to better represent the cellular status
- Switched unit of cellular quality from -dbm to percent
- Added `failure_status` flag in message to represent failur status when `CELLULAR_STATUS_FLAG` is in `CELLULAR_STATUS_FLAG_FAILED` state
- Added field of band with enum `CELLULAR_NETWORK_BAND` to represent band usage for cellular networks 
A lot of the enumerations and definitions are inspired from the definitions of [ModemManager …

Improve cellular status mavlink message

---

message_definitions/v1.0/common.xml

This PR adds 2 commands for controlling auxiliary actuators (primarily designed for servos). MAV_CMD_DO_SET_ACTUATOR_AUX replaces MAV_CMD_DO_SET_SERVO, being less ambiguous and more flexible. MAV_CMD_DO_CYCLE_ACTUATOR_AUX replaces MAV_CMD_DO_REPEAT_SERVO but adds more functionality.
@bkueng @hamishwillee let me know if these messages make sense. I have gone a little extra with the CYCLE_ACTUATOR_AUX command, but let me know if you're fine with it or would prefer not to have this message. I think it could be useful in many cases, potentially even my own payload drop mechanism.
Note: For the PX4 implementation, if control group 3 is used, only the first 3 values will be mapped to actually do anything. I am simply adding 7 for future proofing/because I can :joy:

Add auxiliary actuator commands

---

message_definitions/v1.0/common.xml

This PR adds ESC_INFO and ESC_STATUS messages for slow changing and fast changing ESC information respectively. An ESC_CONNECTION_TYPE  and an ESC_FAILURE_FLAGS enum were also added for this purpose. Each message can house data for up to 4 ESC and by using the index field each message can be used repeatedly up to a maximum of 64 ESC.
Signed-off-by: Ricardo Marques <marques.ricardo17@gmail.com>

Add ESC_INFO and ESC_STATUS mavlink messages

---

message_definitions/v1.0/common.xml

This replaces https://github.com/mavlink/mavlink/pull/1412, which for some reason Github will not allow me to update or merge.
@muramura Thanks for this. I have had to recreate the PR and commit to get the change to allow me to edit it. Can you please check that this is still correct. The main change is to clarify that since 0 now means "not supported" they have to send 1 to mean "0mV".

BATTERY_STATUS.voltage_ext: add cells 10 to 14

---

message_definitions/v1.0/common.xml

This is a follow-up PR on PR: https://github.com/mavlink/mavlink/pull/1421
It contains the following changes:
* Add `CELLULAR_CONFIG_BLOCKED_PUK_REQUIRED` response code to `CELLULAR_CONFIG_RESPONSE`. This response code is needed to indicate that the PUK code is required to unblock SIM card.
* Add field `enable_lte` to CELLULAR_CONFIG message. This field is needed to enable/disable LTE on the vehicle.
* Add field `new_pin` to `CELLULAR_CONFIG` message. This field is needed when changing the PIN.
* Reduce length of the message fields for PIN and PUK to 16.
* Some minor message field description changes.

Update cellular config and message

---

message_definitions/v1.0/common.xml

Lately we have created several mavlink messages to set some settings on the vehicle (eg. the wifi credentials message and the cellular config message. 
In mavlink we already have a parameter protocol that could be used although it currently has some limitations. The three main limitations are the following:
- We cannot set multiple parameters at the same time. Every parameter is set in a separate mavlink message and is applied as soon as it's received. For settings such as wifi SSID and password we would like to first set both parameters before applying them for obvious reasons.
- Currently we would need to use the PARAM_EXT to set such strings. The PARAM_EXT has a value field that is 128 bytes long and even if not all these bytes are used there is no trimming therefore we are always …

extend param_ext protocol by adding messages to start and commit a parameter transaction

---

message_definitions/v1.0/common.xml

It turns out that PARAM_EXT messages were not trimmed as we thought they would be. The fields of a message are ordered by the size of the type, however it does not matter if the type is an array or not.
This means that char[128] is not at the end of the message and therefore not automatically trimmed.
This patch introduces new messages called _TRIMMED which has the param_value as part of the extension meaning that it will be at the end and trimmed correctly.
I'm open to other suggestions on how to do this or better naming suggestions.
FYI @DanielePettenuzzo.
Closes #1168

common: fix PARAM_EXT trimming

---

message_definitions/v1.0/common.xml

Adds a second temperature field to SCALLED_PRESSURE to allow sending back of the air temp from the airspeed sensor. This is often quite different to the baro temp due to location. 
https://github.com/ArduPilot/mavlink/pull/142

common: SCALLED_PRESURE: add press diff temperature

---

message_definitions/v1.0/common.xml

Terrain protocol now documented in  https://mavlink.io/en/services/terrain.html and reflects the two known implementations - ArduPilot and PX4.
This updates the messages to match and link to the docs (and implementation), including deprecating the TERRAIN_CHECK message. Original discussions in docs PR https://github.com/mavlink/mavlink-devguide/pull/259

Terrain protocol: deprecate TERRAIN_CHECK and link to protocol docs

---

message_definitions/v1.0/common.xml

As far as I know the concept of camera ID was abandonded and this is just a leftover that should be removed.

common: remove camera ID

---

message_definitions/v1.0/common.xml

This is a continuation for the parameter transaction protocol design. I added a field to the commit message to decide whether we want to commit or cancel the transaction. The reason for this is for bigger sets of parameters. In QGC we could open a transaction when the user opens a new view in the UI and set the parameters as the user is inserting them and then just send the commit when the user presses on the submit button. In this way we avoid sending all parameters at the end making the submit action slower. If we want to do this we should also be able to cancel a transaction in case a user changes some parameters but then goes to another view. 
FYI @dogmaphobic

common: add param_action to param transaction commit

---

message_definitions/v1.0/common.xml

This message enables a ground station to present the field of view of the camera in the map view.
The alternative to this new message would be to add the required fields to CAMERA_CAPTURE_STATUS.
FYI @jkflying @mrivi @batinkov

common: message to present camera field of view

---

message_definitions/v1.0/common.xml

This PR adds a new WINCH_STATUS message for use with the Daiwa winch. https://ardupilot.org/copter/docs/common-daiwa-winch.html
I have a PR which will improve AP's driver to make use of the telemetry connection from the winch and send it to the ground station using this message.
The equivalent PR to add this message to ArduPilot's fork of common.xml is here: https://github.com/ArduPilot/mavlink/pull/144
All feedback welcome!

Common: add WINCH_STATUS message

---

message_definitions/v1.0/common.xml

This undoes renaming PARAM_EXT_TRIMMED to PARAM_V3 and suggest a possible upgrade path.
As discussed on the call @LorenzMeier @DanielePettenuzzo.

Undo param v3, add EXT_TRIMMED

---

message_definitions/v1.0/common.xml

This pr solves 2 issues with parameter transactions and also introduces a new generic component ID for a mission computer (companion computer). I saw that there was already some discussion about this component id here: https://github.com/mavlink/mavlink/issues/1344. The component IDs we currently have for the mission computer are very specific. In my case I have a process on the mission computer that handles various types of mavlink parameters and interacts with a few other processes that are not exposed via mavlink. This is the reason why I would like to have a generic comp id and also reserve 3 more ids for other mission computer related components in the future.
Instead, regarding the parameter transaction protocol I extended with two fields:
- transaction_id: this was a proposal from …

Improve param transactions

---

message_definitions/v1.0/common.xml

This is not an error per se but something that could be happening and a flag would explain why the gimbal is not working properly as it is calibrating.
FYI @olliw42

common: add "error" flag for calibration state

---

message_definitions/v1.0/common.xml

it is a very good improvement to optimize the PARAM_EXT messages to better benefit from zero byte truncation. However, I think this could have been pushed a bit more. 
This PR reorders the fields such that param_id is right before param_value. That way also param_id is truncated if the value happen to be zero. 
This for sure will not happen extremely often, but a zero value might not be too uncommon (might the default) as well as param_id less than 16 chars, so it may happen often enough to be worthwhile given how simple the change is.

PARAM_EXT_TRIMMED: move fields to even more optimize for zero byte truncation

---

message_definitions/v1.0/common.xml

This PR adds a yaw field to the `HIL_GPS` message.
This is needed in order to simulate GPS sensors that provide yaw information in HITL / SITL simulations. 
This is added as an `extention` and is a identical field with the yaw field https://mavlink.io/en/messages/common.html#GPS_INPUT
- yaw is in cdeg which indicate the yaw from north.
- North is marked as 36000 and yaw=0 invalidates the field.

Add yaw to HIL_GPS messsage

---

component_information/parameter.schema.json
component_information/version.schema.json

* I've run these through https://www.jsonschemavalidator.net and the schema is clean/correctly formatted
* I also tested the schema against the test metadata I am using in QGC and it validates the metadata to be correct against the schema
* Related to #1346

Json schema for COMP_METADATA_TYPE_VERSION, COMP_METADATA_TYPE_PARAMETER

---

component_information/parameter.schema.json

* Parameter name can be in format `FOO<#>_BAR` which will match `FOO1_BAR`, `FOO_6_BAR` and so forth
* Reduces duplication and file size

COMPONENT_INFORMATION: Parameter meta data - Support indexed naming

---

message_definitions/v1.0/common.xml

I"m going to start work on figure out the metadata which specifies the commands a vehicle supports. This allows  gcs to at a minimum know what commands to show when creating missions. It could end up being more than that but I'm going to start simple.
Once this passes CI I'm going to merge so I can start implementation in QGC and work my way through it.

COMPONENT_INFORMATION:COMP_METADATA_TYPE_COMMANDS (WIP)

---

message_definitions/v1.0/common.xml

This PR adds a ID field as an extension to the `HIL_SENSOR` message. This enables streaming multiple instances of `HIL_SENSOR` data so that we can simulate in HIL/SITL multi IMU/Airspeed/Barometer sensor scenarios.
I believe simulating multiple sensors have become of interest for various reasons and PX4 already has support for multi airspeed sensors. For me it doesn't make sense that this cannot be simulated because the message definition is unable to represent multiple instances, hence the extension.
The same approach is already being utilized in the `HIL_GPS` message for simulating multiple GPS sensors.
**Alternative approach**
An alternative approach would be to actually redefine the `HIL_SENSOR` message so that we have separate messages for each sensors. However, I think this might …

Add ID field to HIL_SENSOR for multisensor  support

---

message_definitions/v1.0/common.xml

QGC is using NaN rather than 0 to indicate "not valid" in [MAV_CMD_IMAGE_START_CAPTURE.param4](https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_START_CAPTURE) (sequence number) when param3 != 1. This works with PX4 and as it is clearly an invalid value I would expect a system getting this to handle it. 
What this change does is explicitly allow the NaN case. 
I also took opportunity to mark up the other parameters as reserved with an NaN value using the expected syntax.

MAV_CMD_REQUEST_CAMERA_IMAGE_CAPTURE: clarify param4 values

---

message_definitions/v1.0/common.xml

As discussed in the dev call, `MAV_CMD_NAV_FENCE_RETURN_POINT` predates the use of rally points and is superseded by them. This change deprecates the command, and further clarifies that if a rally point is defined as well then that rally point would be used instead. 
FYI @DonLakeFlyer ,@meee1 
- We wont be removing this arbitrarily because we never remove things arbitrarily :-). But in particular, because this is still being used by some ArduPilot systems that won't update. 
- PX4 appears to support setting this through QGC, but it also appears to ignore the setting. Worth removing as an option in the UI IMO.

MAV_CMD_NAV_FENCE_RETURN_POINT - deprecate

---

message_definitions/v1.0/minimal.xml

I've updated the source and added a 10-rotor helicopter type.
Before:
#1479

common: Add a DECAROTOR type

---

CMakeLists.txt

Looks like this XML has been removed over time. I'm just wondering why nobody noticed that it is missing.
Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com> (github: thopiekar)

CMake: Removing slugs.xml

---

message_definitions/v1.0/common.xml

Hamiltonian convention is nonsense, it's Hamilton convention, or Hamilton's convention, or whatever
(Hamiltonian is the Hamilton function or Hamilton operator, or related mathematical constructs, nothing to do at all with quaternions)
I also grabbed the opportunity to move the two target fields to the front. A simple search through common.xml shows that this is so for all other messages (except one which has a network thing).

AUTOPILOT_STATE_FOR_GIMBAL_DEVICE: it's Hamilton

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

MAV_CMD_REQUEST_PROTOCOL_VERSION should never have been in minimal, as it is not part of the minimal subset of mavlink required to establish mavlink communication.  As it is deprecated in any case, shifting it back to common where it can quietly see out it's days.

minimal: shift deprecated MAV_CMD_REQUEST_PROTOCOL_VERSION to common.xml

---

message_definitions/v1.0/common.xml

This fixes a error I introduced in https://github.com/mavlink/mavlink/pull/1429
The change is to send zero for not available as its a extension.

common: correct scaled pressure extension not available value

---

message_definitions/v1.0/common.xml

This PR adds a field hardware_version to the GIMBAL_DEVICE_INFORMATION message.
I can't see any rational for why the message should carry info such as vendor name, model name, and software version but not also reveal info about the hardware. (I had brought it up also in #1370, and at this time it seems this point wasn't disputed but not acted on because of the general faith of the message)
Given the apparently contentious nature of the topic, as it appears to be from recent prs and issues, I've put it into this separate pr.

Gimbal Device Information: Add hardware version field

---

message_definitions/v1.0/common.xml

This is a collection of changes/improvements on the initial gimbal v2 spec.
The changes mostly come out of the discussion with @olliw42 in #1419 and through experience after some implementation of the v2 protocol.
Basically, we found that the deconfliction/prioritization rules were not very clear and not covering more than a few specific cases. After some more iterations on how this could be done, @olliw42 and I gave up on such a design partly because we couldn't agree on the specifics and partly because it seemed to get very complex for not much benefit. We therefore went back to a similar approach as it was before with a configure message, although somewhat different. Instead of setting up the mode of the gimbal, we now set the sysid/compid of the component in control. The component can …

Gimbal v2 changes

---

message_definitions/v1.0/common.xml

#1466 has reverted #1488, which I suspect (hope :)) was unintentional. This PR corrects this.
Just as comment: The last sentence in the description could probably need better wording, I couldn't come up with a few words change, so I left it as is :).

it's Hamilton, move target to front again

---

message_definitions/v1.0/common.xml

These can't be WIP after so much time. The explanations also a little ambiguous.

COMMAND_ACK - remove WIP on extensions. Clarify use

---

message_definitions/v1.0/common.xml

This includes a few follow up changes for gimbal:
- include roll limits
- use roll/pitch/yaw instead of bank/tilt/pan
- remove hardware roll/pitch/yaw rate limits as they are likely/realistically not going to be used
- consistent ordering of min/max
@olliw42 I would appreciate you review.

gimbal: include roll limits, roll/pitch/yaw instead of bank/tilt/pan

---

message_definitions/v1.0/common.xml

I missed these in earlier changes.

gimbal: fix wrong deprecated references

---

message_definitions/v1.0/common.xml

HIGH_LATENCY2 is already marked as a new version. We are using deprecated flag to indicate superseded-by.

Mark HIGH_LATENCY as deprecated by HIGH_LATENCY2

---

message_definitions/v1.0/common.xml

I'd like to also mark these as not used, or at least confirm that someone uses them and how:
- `COMMAND_INT.current` - false:0, true:1
- `COMMAND_LONG.confirmation` - 0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
According to @julianoes the `confirmation` is not used https://github.com/mavlink/mavlink-devguide/pull/217#issuecomment-547283478 by PX4, and I suspect not by ArduPilot. 
@auturgy Do you know anything about these two?

COMMAND_INT.autocontinue - clarify not used

---

message_definitions/v1.0/common.xml

When displaying storage status (within the UI), this allows to identify which storage the data refers to.

Adding storage name to storage info message.

---

message_definitions/v1.0/common.xml

This removes the NONE flag and adds two special values to configure control. For more details check the commit messages.
@olliw42 I would appreciate your feedback.

Gimbal: CONFIGURE improvements

---

message_definitions/v1.0/common.xml

I went through the MAVSDK source and removed all WIP notes/flags in common for messages that are already implemented and released.
Regarding the gimbal v2 messages I would personally leave them WIP a few weeks longer, for the rest it should be fairly clear.
This is in response to the request by @LorenzMeier in the [last dev call](https://github.com/mavlink/mavlink/wiki/20201028-Dev-Meeting#notes). The same would have to be done for PX4.

Remove WIP for messages implemented in MAVSDK

---

message_definitions/v1.0/common.xml

[COMMAND_INT.current](https://mavlink.io/en/messages/common.html#COMMAND_INT) doc just says it is a value of true or false (boolean). I searched PX4 and ArduPilot and I'm pretty sure it is not used. This makes sense because I think it is a hold over from whoever copied MISSION_INT (and in that context it meant "current mission item).
@auturgy @julianoes OK?

Mark COMMAND_INT.current as not used.

---

component_information/parameter.schema.json

The syntax for an `array` was not correct.
Not yet reformatted, so the diff is clear.
In addition:
- adds `bitmask`
- allows '.' and '-' as part of the param names. PX4 has some of those that come from uavcan. Probably not strictly required.
Questions:
- how should the [uid](https://github.com/mavlink/mavlink/blob/master/component_information/parameter.schema.json#L13) be filled in? If it's a CRC of the file it's impossible to add it.
- how does the [scope](https://github.com/mavlink/mavlink/blob/master/component_information/parameter.schema.json#L17) work? I would expect the scope can be applied to a (sub-)set of parameters. Is that incorrect?

component_information: fix parameter.schema.json array type

---

message_definitions/v1.0/common.xml

**Problem**
A solution commonly used to increase the coverage and efficiency in mapping surveys is to have multiple cameras at oblique angles to capture a wider areas per flight line, this also has potential benefits of capturing more data from facades and tall objects. However, adding cameras increase cost, weight and complexity of the equipment, on the other hand, mapping cameras are generally capable of shooting multiple frames per second and are usually triggered about once every two seconds or less frequently in mapping missions. We could better use the hardware capabilities if we moved the camera mount between shots while decreasing the shooting distance to keep the overlap settings.
**Solution**
I decided to implement a solution that uses the already existing …

add command 260 for Oblique Survey

---

message_definitions/v1.0/common.xml

Fixes #1448 
This removes the `wip` tagging on `VIDEO_STREAM_STATUS`, [VIDEO_STREAM_INFORMATION](https://mavlink.io/en/messages/common.html#VIDEO_STREAM_INFORMATION), `MAV_CMD_VIDEO_START_STREAMING`,
`MAV_CMD_VIDEO_STOP_STREAMING` that was added with the PR in https://github.com/mavlink/mavlink/pull/1060
Generally WIP has been mis-used. Previously we've added it to common.xml to indicate "we're about to implement this". What should happen is that the message with wip gets added when there is a complete but untested implementation - essentially as a shakedown phase. It should have a date and be removed when that date has passed. 
PS.
@dogmaphobic 
1. These are part of [camera protocol](https://mavlink.io/en/services/camera.html) right? Were you planning on adding to docs or should I?
2. …

common: Remove WIP on video streaming

---

message_definitions/v1.0/common.xml

This adds a `Inclusion Group` number to fence polygons and circular inclusion zones. The vehicle must stay within ALL zones of a single group, this is the current behavior in AP. The vehicle can be within one group OR another, this would be new behavior. 
The goal being to enable one to configure a few fences for typically flying locations and be OK to fly so long as you were inside one of them.
https://youtu.be/_IkjcgyQbRI

common: Add 'Inclusion Group' to fence for 'OR' fences

---

message_definitions/v1.0/common.xml

While the type masks in the `SET_ATTITUDE_TARGET` and `ATTITUDE_TARGET` message are well defined in the mavlink spec, by not defining them as enums make it cumbersome to use the type masks.
On the contrary, type masks are defined properly defined as enums for position setpoint messages(e.g. `SET_TARGET_POSITION_LOCAL_NED`).
**Solution**
This commit defines the bitmask of attitude target type masks into enums

Define Attitude Target type mask as enums

---

CMakeLists.txt
message_definitions/v1.0/common.xml

If neither mavgen nor mavgen.py have been found as executables in $PATH, then we will fallback to the hardcoded location (submodule).
Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com>

CMake: Using find_program to find mavgen(.py)

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

As discussed in [20201124-Dev-Meeting](https://github.com/mavlink/mavlink/wiki/20201124-Dev-Meeting) this is not required for a MAVLink minimal system. This should therefore move back to common.
@auturgy You OK with this to be merged (i.e. sanity check).

Move MAV_CMD_REQUEST_MESSAGE to common.xml

---

message_definitions/v1.0/common.xml

Some smart batteries have serial numbers with a alpha numeric serial number. I would propose to extend the serial number from an integer to a array of ASCII characters

smart_battery_info extend serial number

---

message_definitions/v1.0/common.xml

Equivalent PR into mavlink repo is here: https://github.com/ArduPilot/mavlink/pull/180
PR to ArduPilot to use these changes is here: https://github.com/ArduPilot/ardupilot/pull/15065
Allows for a mechanism for a GCS to release channels back to the RC; at the moment the lower channels allow for instant-release to RC but the higher don't.
Also clarify the descriptions by putting all of the user's options in one place.

common.xml: UINT16_MAX-1 on RC_CHANNELS_OVERRIDE means return-to-rc-radio

---

message_definitions/v1.0/common.xml

Updates PARAM_SET docs to separate use in parameter protocol from use in transactions. Follows on from discussion inhttps://github.com/ArduPilot/mavlink/pull/177#discussion_r543763460

common.xml: PARAM_SET - separate out transactions

---

message_definitions/v1.0/common.xml

It turns out that supporting the _TRIMMED message set for PARAM_EXT is not as straightforward as it should be:
- Having to implement both variants of the messages ends up being a bit of code/binary bloat.
- When doing a param set without previously having done a get or request list is tricky because it is not clear whether TRIMMED can be used. This means that retransmission is required in case the wrong one is picked which makes it more brittle and can add some latency. I realized all this once I move to the implementation for MAVSDK.
Furthermore, the changes have not actually been adopted anywhere that I'm aware of, and they are not documented yet either.
I therefore came around and changed my opinion and vote to get rid of these changes again.

common: abolish PARAM_EXT_*_TRIMMED again

---

message_definitions/v1.0/common.xml

This was deprecated because there was no indication it was used anywhere (in response to request emails etc). Now reverting because we know it is used by MAVProxy https://github.com/ArduPilot/mavlink/pull/158#discussion_r530189745 and by Mission Planner: https://github.com/ArduPilot/mavlink/pull/158#issuecomment-737058136

Remove deprecation of TERRAIN_CHECK

---

message_definitions/v1.0/common.xml

Changes cycle_count to an int32 to allow for -1 if not available

common.xml: smart_battery_info fix cycles not available to UINT16_MAX

---

message_definitions/v1.0/minimal.xml

this specifies the values for all entries of the MAV_STATE enum
they are currently auto-generated by the code generator(s). I filled them in with what mavgen is auto-generating.
It may be seen as just a matter of convenience, but I actually think that this is not good practice, i.e., a specification should not have to rely on whatever code generator is doing, but rather be explicit and specify what the specification is to be. So, I actually also think that all the code generators should rather throw an error instead of auto-generating enum values...
COMMENT: This appears to also apply to the enum definitions in the ualberta.xml dialect ... but this is not a standard dialect, so I haven't touched that.

MAV_STATE enum, specify values explicitely

---

scripts/update_c_library.sh

two corrections to update_c_library.sh
* slugs.xml isn't existing anymore
* minimal.xml doesn't need to be explicitly be generated, it in fact must not be explicitly be generated. First off, what was generated by generate_headers minimal $1 is later overwritten by generate_headers standard $1, as can be clearly proved by the fact that the IDX in minimal.h is 2 and not 0. Furthermore, generate_headers standard $1 must in fact be called as last since otherwise the library would not work, since IDX'es would be wrong as well as the MAV_CMD enums. Hence the generate_headers minimal $1 is superfluous.
comment: I couldn't manage to run the script itself, but I made me a win batch file which I strongly believe deos do exactly the same. So, I do have this experimental evidence. But the mentioned …

update update_c_library.sh script

---

message_definitions/v1.0/common.xml

Depends on https://github.com/ArduPilot/pymavlink/pull/479 and requires some user consultation for deployed systems.
Background is in the pymavlink PR, but basically this aligns the mavlink EFI_STATUS message flow and consumption units with uavcan v0 (https://github.com/UAVCAN/public_regulated_data_types/blob/c043498eacfe90a56e3246d4c2e4ae81aad13082/uavcan/equipment/ice/reciprocating/1120.Status.uavcan#L165) and ArduPilot AP_EFI (https://github.com/ArduPilot/ardupilot/blob/8561f5239d4bc10424e4bfe69ad69dfbdd7c5cc9/libraries/AP_EFI/AP_EFI.cpp#L128).  The change in units results in reporting volumetric flow and consumption, rather than mass flow and consumption (specific gravity of the fuel being the conversation factor if needed).
Both volumetric and mass flow are likely to be encountered …

Change EFI_STATUS flow units from g to cm^3

---

message_definitions/v1.0/ASLUAV.xml
message_definitions/v1.0/autoquad.xml
message_definitions/v1.0/ualberta.xml

does https://github.com/mavlink/mavlink/pull/1552#issuecomment-763305515
Adds values to all enum entries which didn't yet had a value.
Procedure:
I ran mavgen for C for each and every xml file, and checked for the "An enum value was auto-generated: xxx = yy" print outs. I thus did not only check and corrected the xmls covered by all.xml, but all.
Comment:
For autoquad.xml this resulted in MAV_DATA_STREAM_PROPULSION = 13, which IMHO just shows how 'dangerous' the autogeneration is, since this value would have changed if the MAV_DATA_STREAM enum in common.xml would have changed, breaking implementations...

Enums: Specify values explicitely in all enums

---

.github/workflows/test.yml
.github/workflows/test_and_deploy.yml
scripts/format_xml.sh
scripts/test.sh
scripts/update_c_library.sh
scripts/update_generated_repos.sh

This is an attempt to add the deploy step to https://github.com/mavlink/c_library_v2/ and https://github.com/mavlink/c_library_v1/ back in which was removed in https://github.com/mavlink/mavlink/pull/1544.

CI improvements, add deploy to c_library_v1/2 back in

---

scripts/format_xml.sh

this attempts to improve the script format_xml.sh, also making it to work as it is saying itself:
* It cannot be run with a filename argument, i.e., it cannot be applied to one specific file. That's particularly weird, since when run with option -c it is saying "run ./scripts/format_xml.sh $f" when a file needs formatting! This has been corrected by removing all options from the arguments list and filling xml_files with the first argument if there is an argument. (lines 27 - 37).
* It could not be easily applied to a specific directory, such as (the potentially upcoming) mavlink/external/dialects. Currently it would process ALL xml files it finds in the tree of subfolders from which the script is run. This has been overcome by a new option -d, which sets the $(find ...) accordingly.
* It …

improve format_xml.sh script, tab to spaces

---

message_definitions/v1.0/common.xml

This removes the units from the HDOP, VDOP (fields are generally named eph, epv) on messages: `HIL_GPS`, `GPS2_RAW`, `GPS_INPUT`. Fixes #1572
This is correct technically; however some systems may have somehow "interpreted" the old units.
I did not update [HIGH_LATENCY2](https://mavlink.io/en/messages/common.html#HIGH_LATENCY2) eph, epv fields as these are not described as HDOP/VDOP fields - i.e. I think they really are distances.
@julianoes @auturgy FYI

Removes units on messages with hdop, vdop

---

message_definitions/v1.0/common.xml

The entries of CAMERA_TRACKING_MODE were missing the _MODE suffix which is not consistent and might to mix up with CAMERA_TRACKING_STATUS_FLAGS and CAMERA_TRACKING_TARGET_DATA.

common: make tracking mode enum consistent

---

message_definitions/v1.0/common.xml

GCS and/or companion computers can then warn the user or take automated action

common.xml: Add a status flag for generic motor malfunction

---

message_definitions/v1.0/common.xml

@auturgy As discussed the deprecation of MAV_CMD_NAV_FENCE_RETURN_POINT was removed. I've proposed new wording in the description that captures when this should be used vs rally points - essentially IF rally points are supported they should be trusted instead. 
I think this works for systems that support the point (ArduPlane), systems that don't (ArduCopter, PX4) and things that support both (none that I know of, though possibly ArduPlane will do so in when updated to support rally points).
What this means though is that if a system supports both, then it must use the rally points, if enabled.

Clarify MAV_CMD_NAV_FENCE_RETURN_POINT vs rally points

---

message_definitions/v1.0/common.xml

This would be more consistent.

common: make tracking target data enum consistent

---

message_definitions/v1.0/common.xml

Linked to https://github.com/PX4/PX4-Autopilot/pull/16691.
I would like to add the ability to trigger a QuadChute from an external command over MAVLINK (in our case using MAVROS). Our main motivation for it is to be able to react and stop the drone as fast as possible e.g. if it is about to breach a Geofence in FW mode.
The new field would also allow to send additional info on the drone's state in https://mavlink.io/en/messages/common.html#EXTENDED_SYS_STATE so that any offboard control is aware that there was a quadchute.

Add MAV_VTOL_STATE_QC field

---

message_definitions/v1.0/common.xml

I believe that the HDOP/VDOP values are generally scaled by 100 and we should therefore document it that way.
PX4:
*.01f when the UBX values are read:
https://github.com/PX4/PX4-GPSDrivers/blob/c278eb48e1b57e6b789242324e28581caf9ccf96/src/ubx.cpp#L1815-L1816
*100 before the values are sent out:
https://github.com/PX4/PX4-Autopilot/blob/5bbc66f3afe99e75852e9b3660a5de4d2fc0b902/src/modules/mavlink/mavlink_messages.cpp#L1393-L1394
ArduPilot:
It seems to be *100 everywhere without conversion from UBX:
https://github.com/ArduPilot/ardupilot/blob/ecf928d68ba497dd2502ab56037f6aaa1bc298e2/libraries/AP_GPS/AP_GPS_UBLOX.cpp#L1280-L1281
And sent out as is:
https://github.com/ArduPilot/ardupilot/blob/ecf928d68ba497dd2502ab56037f6aaa1bc298e2/libraries/AP_GPS/AP_GPS.cpp#L1238-L1239
I left GPS_INPUT …

common: fix HDOP/VDOP unit scaling

---

message_definitions/v1.0/common.xml

This PR extends `MAV_BATTERY_FAULT` with two new fault types:
- Battery firmware incompatible: when the smart battery has a too old/new firmware compared to the autopilot.
- Battery model incompatible: when the battery model (e.g 2s1p, 2s2p,...) is not compatible with the vehicle

Add battery faults flags for wrong firmware and battery models

---

message_definitions/v1.0/all.xml
message_definitions/v1.0/development.xml

Fixes #1172
Replaces #1172
Under the new governance model xml definitions don't get accepted into standard set until they have been prototyped on one flight stack and at least one other key stakeholder stacks have agreed to implement them. To ease development this PR creates `development.xml` (includes `standard.xml`) and imports it into all.xml. This is where proposals to the standard set should be added before being implemented and proposed.
In addition, this adds the `MISSION_CHECKSUM` message which was agreed in #1172. 
As discussed in devcall - @auturgy @LorenzMeier @julianoes 
FYI @IamPete1 @holmnikolaj @amilcarlucas

Create development.xml and seed with MISSION_CHECKSUM

---

message_definitions/v1.0/common.xml

With recent development of fully actuated systems and more complex actuation being available on VTOL vehicles, we need a way to conveniently set 3D thrust setpoints on vehicles. 
This adds a 3D thrust setpoint in the SET_ATTITUDE_TARGET to support fully actuated vehicles
The reference implementation is provided in https://github.com/PX4/PX4-Autopilot/pull/16994

Extend SET_ATTITUDE_TARGET message for 3D thrust setpoints

---

message_definitions/v1.0/common.xml

If the camera does not keep track of recording time (or doesn't know it), set the `recording_time_ms` field to 0. The `CAMERA_CAPTURE_STATUS` is only sent periodically so the GCS keeps track of recording time on its own any way. But when the camera does support reporting of the recording time, the GCS will update its internal timer to reflect what the camera tells it.

Document recording time within CAMERA_CAPTURE_STATUS message.

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

Proposed message for AIRSPEED_SENSOR instances, as discussed in #1584. Assumption is sending rate would be low - 1 or 2 Hz, and probably something streamed on request using MESSAGE_INTERVAL rather than "by default".
Has 
- instance: id
- airspeed (IAS)
- temperature
- differential pressure
- static pressure. 
Points for discussion
- Are there any other fields needed? Sensor type?
- Are these the right units? (I copied similar fields in other messages)
FYI @dagar @sfuhrer @RomanBapst @julianoes @auturgy @LorenzMeier 
PS Under current rules I assume we don't merge until there is an implementation, but we can at least approve the design

Common.xml: AIRSPEED message

---

message_definitions/v1.0/common.xml

This adds new param metadata to motor test command. I'm hoping to clarify the operation and document the service. 
Some assumptions - can anyone confirm:
- This is a simple command protocol message MAV_CMD_DO_MOTOR_TEST. There are no other messages involved other than the ACK/NACK.
- This cannot/must not be used in missions.
- ACK is returned with progress updates, and with success and on completion. Otherwise if test can't be run or if it fails NACK returned.
- There are two modes - single motor test and sequential motor test.
- Single motor test uses param 1 and tests just the specified motor
- Sequence uses param 5 to indicate a count of motors to test, with sequence specified in other params.
- I assume this is expected to work such that the user either tells GCS to start one motor or …

MOTOR_TEST service updates to common.xml

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

MAVLink has a [FENCE_ACTION](https://mavlink.io/en/messages/common.html#FENCE_ACTION) that defines a number of possible actions on geofence breach. This is currently used only by ArduPilot to define the values for the system action on fence breach (it is used directly in a parameter).
This PR generalises the action, and defines a command that can be included in a geofence definition (as many times as you like) to allow the geofences in a plan to have separate actions assigned.
The message can also be used via the command protocol to set the global/system-default fence action.

Command to allow geofence action to be set per-fence

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This reverts commit 66520310ec21ba55dcd006e8f5d8f433bc2f3fcf.
There's a problem with the C library generator:
The addition of MAV_CMD to development.xml led to the removal
of MAV_CMD in common.h. This breaks build for everyone using that enum
and including 'common.h' or 'standard.h' (and probably others).
See https://github.com/mavlink/c_library_v2/commit/992871ba04b721dac6ef8a851dbe9df3b6c22e2d
@hamishwillee agreed to revert this until we have a correct fix.

Revert "Command to allow geofence action to be set per-fence (#1482)"

---

message_definitions/v1.0/common.xml

so here now the clean up PR
I've only touched standard.xml and includes, which boils down to only common.xml
* replaces 255 by UINT8_MAX in message fields which have an 'invalid' attribute
* replaces 65535 by UINT16_MAX in message fields which have an 'invalid' attribute
* in two cases the invalid is 0, but in the message description 65535 appears for another situation, I have replaced these also by UINT16_MAX (see messages GPS_RAW_INT and GPS2_RAW)
there are now no 65535's anymore
there are still a couple of 255's in message field descriptions, but these are valid values. I generally found the description more readable with the 255's, so I systematically left those as they are.
This PR should be totally NFC
Not done: As discussed in the original PR, the attribute 'invalid' refers to a …

Invalid attribute: Replace 255 by UINT8_MAX and 65535 by UINT16_MAX

---

doc/mavlink_gitbook.py

This improves the generated mavlink docs:
- The addition of the external dialects was throwing an error as the dialect doc was not being generated. My take is that we should not build these non-standard dialects, so the update changes the include from a link to just plain text.
- The development.xml and all.xml are new. This also adds header docs explaining what they are for.

Fix external links and dev/all dialect docs

---

external/dialects/storm32.xml

the title says it
updates external dialect STorM32.xml to make use of the invalid attribute, and adds a new enum field
THX

external STorM32.xml: Add invalid attribute, add QSHOT home targeting

---

message_definitions/v1.0/common.xml

This restores the FENCE_ACTION changes that were added in #1482 and reverted in #1626. These ones did not need to be reverted but were part of a bigger commit that did. I plan to add back the other changes too, but only when I have worked out how to do so safely.

Add FENCE_ACTION update for per-fence actions

---

message_definitions/v1.0/common.xml

This adds a few fields to the smart battery info. message that characterize the pack.
- `num_cells`
- `charging_maximum_voltage`
- `discharge_maximum_current`
- `discharge_burst_current`
- `manufacture_date`
Downstream PR https://github.com/ArduPilot/mavlink/pull/181

common.xml: add fields to smart_battery_info

---

message_definitions/v1.0/common.xml

This is a simple feature extension on orbit mode that allows the implementation of a very simple finite state machine structure in autopilot software. Normally orbit executes indefinitely, however the use-case I'm currently working on requires a finite orbit behavior for a certain amount of angles. 
Following is a diagram of the added states when the orbit is requested to happen only for 360 degrees.
Based on use-cases, this state machine can be populated with more fine-grained states. Nevertheless this alone enables many capabilities.

Add simple FSM support to ORBIT_EXECUTION_STATUS message in common.xml

---

message_definitions/v1.0/common.xml

Copied this note out of MISSION_ITEM_INT:
> NaN or INT32_MAX may be used in float/integer params (respectively) to indicate optional/default values (e.g. to use the component's current latitude, yaw rather than a specific value)
This essentially exists for the same reason - to remind people that they can't use NaN for param 5,6 if sending in the COMMAND_INT.

common.xml - COMMAND_INT - add note about using Nan/INT32_MAX for default params

---

message_definitions/v1.0/minimal.xml

It would be nice to have a component ID for a safety device such as a parachute module.
FYI @MaEtUgR

minimal: add compid for safety

---

message_definitions/v1.0/common.xml

It appears that all ArduPilot vehicle types send this message, not just the fixed-wing ones. All vehicle types implement `send_nav_controller_output()` which send this message.

common.xml: remove fixed-wing wording from `MAV_CONTROLLER_OUTPUT`

---

message_definitions/v1.0/common.xml

Allows other mavlink nodes to request that prearm checks be run immediately.
Closes a problem where to work out whether a system is armable you have to try to arm it.

common.xml: add MAV_CMD_RUN_PREARM_CHECKS

---

message_definitions/v1.0/common.xml

This was originally agreed in dev call and is now supported in a released version of PX4. I have therefore removed the WIP tagging.
@auturgy Any comments before merging?

common: MAV_CMD_DO_SET_ACTUATOR - remove WIP

---

message_definitions/v1.0/development.xml

1. Adding a new message about atmosphere data;
2. The atmosphere data include temperature and humidity, they come from a hygrometer ,such as SHT3X sensor.
3. The hygrometer communicate with flight(ardupilot and PX4) controller with uavcan protocol;
4. The humidity and temperature can display on Mission Planner and QGroundcontroll.
5. The hygrometer is use to detect other sensor's running status.

add a new message about atmosphere

---

message_definitions/v1.0/common.xml

Add new MAV_CMD_DO_ADSB_OUT_IDENT to trigger an ADSB/ModeA/C/S Transponder IDENT.
The number 10001 was chosen because the uAvionix.xml file uses 10000-10099 but there's no MAV_CMDs in there. This was originally in that file but I pulled it out to common.xml. I think the same number is still OK to use though since it's not a msg_id.

add MAV_CMD_DO_ADSB_OUT_IDENT 

---

message_definitions/v1.0/common.xml

The original doc said the field was a scheduled action for waypoint. That was misinterpreted by a user as "how do I encode the whole command in that array": https://github.com/mavlink/mavlink/issues/1666
It should now be clear that each index in all the arrays is for a particular waypoint, and this particular field represents the command ID of the associated waypoint's MAV_CMD.
This was confirmed by @TSC21

common.xml: TRAJECTORY_REPRESENTATION_WAYPOINTS.command - is command id

---

message_definitions/v1.0/common.xml

- MAV_CMD_OBLIQUE_SURVEY - known implementations in APM and PX4.
- MAV_CMD_INJECT_FAILURE - known implementation in PX4, 
- SUPPORTED_TUNES - MAVSDK and PX4 implementation.
- TUNNEL - Storm32 gimbal implementation
- WINCH_STATUS - APM implementation

Remove WIP on some implemented common commands/messages

---

message_definitions/v1.0/common.xml

This removes WIP on COMMAND_ACK extension fields. This is implemented in deployed systems. Agreed in dev call.

Common.xml - remove the WIP markup on COMMAND_ACK

---

message_definitions/v1.0/common.xml

This PR changes the temperature range of ESC_INFO to allow negative temperatures.

common: allow negative temperatures for ESC_INFO message

---

message_definitions/v1.0/common.xml

Certain vehicles are capable of simultaneous control of 6dofs, but are unable to use the functionality because the existing form of the MANUAL_CONTROL message limits us to 4 axes with joystick control.
Support for additional buttons has been requested by several QGC users, particularly since some existing game controllers support more than 16 buttons (e.g. PS4, PS5, and [Logitech X56 H.O.T.A.S.](https://www.logitechg.com/pt-br/products/space/x56-space-flight-vr-simulator-controller.945-000058.html)). We also have users developing custom controllers for industrial clients, who frequently want to include several additional inputs beyond the base 16.

Add additional axis to Manual control, support additional buttons.

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

WIP message `MISSION_CHANGED` is designed to support partial mission updates, but is not implemented in any stack. As per governance rules, moving it into the development.xml until there is an implementation somewhere, and firm commitment to implement it in other stack.
Discussed in dev call: https://github.com/mavlink/mavlink/wiki/20210901-Dev-Meeting

MISSION_CHANGED moved to development.xml

---

scripts/update_c_library.sh

This updates the build script to generate the C library for **development.xml** first, rather than last. This will allow us to add commands to development.xml without breaking the common.xml or ardupilot.xml builds. This is logically safer, and has been verified by testing.
Note that it doesn't "fix" the problems with enum generation. It just means that the issues with enum generation are fixed by the later build.
The short version is that since later builds swamp generated dialect folders of earlier builds, building development.xml first means that it cannot break anything that happens afterwards.
----
The TLDR of this is that when you build an XML file, all the dialects it includes are built as well. In theory the order should not matter because the generator is supposed to create the …

update_c_library - build devfirst

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

Depends on #1692 - DO NOT MERGE until this goes in.
Parameter transactions change "related parameters" atomically/together. This enables, among other benefits, in-flight changes that would otherwise be dangerous/impossible.
This PR moves the implementation to development.xml pending an implementation being demonstrated/prototyped. 
Discussed in dev call: https://github.com/mavlink/mavlink/wiki/20210901-Dev-Meeting

Param protocol transaction items to development.xml

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

#1482 added command to development.xml so that geofence action could be set per-fence. However this was reverted in https://github.com/mavlink/mavlink/commit/a2786691aaa06f7e6ff076538188bee0f4bea976 due to problems with the C library build. The library build problem was worked around in #1692 so this adds the command back to development.xml.
Further, this removes WIP from the development.xml. This was previously discussed with @auturgy et al, but the first version did not strip these tags. However it makes sense to do so, because:
- WIP is implied by presence in development.xml
- Makes it easier to copy from development to common on acceptance.
Merging on CI pass as this is effectively pre-approved by previous submission

Re-add comment so geofence action can be set per-fence

---

message_definitions/v1.0/common.xml

@LorenzMeier These messages are problematic: [MAV_CMD_PAYLOAD_CONTROL_DEPLOY](https://mavlink.io/en/messages/common.html#MAV_CMD_PAYLOAD_CONTROL_DEPLOY), [MAV_CMD_PAYLOAD_PREPARE_DEPLOY](https://mavlink.io/en/messages/common.html#MAV_CMD_PAYLOAD_PREPARE_DEPLOY), [MAV_CMD_NAV_PAYLOAD_PLACE](https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_PAYLOAD_PLACE)
- It is not clear how they would be used.
- They would be hard to implement or use in a "generic" way because this refers to an arbitrary payload.
- They aren't designed as we would now as "primitives" but are instead somewhat monolithic - ie in the same way you did not particularly like the orbit command.
- They do not appear to have been used in ArduPilot or PX4. They were added by you in https://github.com/mavlink/mavlink/pull/235 …

common.xml: Deprecate MAV_CMD_NAV_PAYLOAD_* [Proposal]

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This moves WIP CELLULAR_CONFIG message and associated enums to development.xml
I **think* this was agreed in the dev call [20210901](https://github.com/mavlink/mavlink/wiki/20210901-Dev-Meeting) as there appears to be no public implementation. @julianoes @auturgy Was that what you remember?
FYI @DanielePettenuzzo

Move CELLULAR_CONFIG to development.xml

---

message_definitions/v1.0/common.xml

Fix bug in global frames definition - integer representation is multiplied by degrees*1E7 not degrees*1E-7

Global int frames - degrees*1E7 not E-7

---

message_definitions/v1.0/common.xml

The ASTM F3411 Specification for Remote ID and Tracking has
been updated to version 1.1. Change the related MAVLink messages
to be compliant.
- Add new Basic ID type for Specific Session ID
- Support using 0xFFFF as indicator of invalid timestamp value
- Support new System field for Operator Geometric Altitude
- Support new Authentication features
- Add new authentication type for specific authentication
- Allow up to 16 pages of authentication data
- Rename PageCount to LastPageIndex
- Decrease maximum message pack size

Update OpenDroneID messages to be compliant with ASTM v1.1

---

message_definitions/v1.0/common.xml

My fastMavlink parser was smart enough to catch this bug:
For the ESC_INFO message, the invalid attribute of the temperature field was incorrect. Since it is an array field the invalid attribute must be of the form [] too. We had determined and fixed the "rules" for how they must look like somewhere else in a thread I couldn't find that quickly. 
PS: it seems it's all in this long thread, https://github.com/mavlink/mavlink/pull/1614, maybe one should write them up:
if field is not an array then invalid="value"
if field is an array then 
* invalid="[value]" means all array elements
* invalid="[value,]" means the first array element, but no invalid for all the rest elements
* invalid="[value1,value2,value3]" means array has 3 elements and each element has the respective invalid attribute
* …

ESC_INFO: invalid invalid attribute

---

message_definitions/v1.0/common.xml

I forgot to update the Authentication message description to match the changes done for the ASTM spec v1.1.

Fix OpenDroneID authentication message description

---

message_definitions/v1.0/common.xml

Instead of having hard-coded params to reboot a camera or gimbal/mount specifically, this change allows to reboot any (or all) components based on the MAVLink component ID.
Previously param3 and param4 were marked WIP, and I doubt they have been implemented anywhere.

common: allow any compid to be rebooted

---

message_definitions/v1.0/common.xml

This attempts to better match MAV_FRAME descriptions to the conventions used in the [proposed RFC](https://github.com/mavlink/rfcs/pull/2), as discussed in #1685. This requires careful review to ensure I have not changed the meaning of any of the frames from their intent.
There are notes inline about some sections.
Anyone else we can/should get to review? The RFC authors? @Jaeyoung-Lim ? @TSC21 ?

MAV_FRAME - better match descriptions to RFC

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This PR adds mission items grouping commands. Groups are defined by START/STOP items and 64bit unsigned integer ID. A group can be nested inside another group. When control reaches MAV_CMD_GROUP_START or MAV_CMD_GROUP_END it emits GROUP_START message with group ID and current timestamp.
Task requirements and what kind of problem are we trying to solve:
We want to be able to associate data acquired by the vehicle (f.e. photos) with groups of mission items.
For example: user wants to inspect 2 bridges and creates a flight plan with several way points in proximity of each bridge.
With the proposed solution we would group mission items in 2 groups. For each photo we will add current group id and group timestamp to image metadata. This metadata will be later used to f.e. filter out only photos …

Mission item grouping commands and messages

---

message_definitions/v1.0/development.xml

This updates the `MISSION_CHECKSUM` definition to clarify exactly how the `MAV_MISSION_TYPE_ALL` is calculated - my understanding is that the order in which you parse the mission, geofence and rally point part of the plan matters!
I also took the opportunity to make it _more_ clear that if you update just the mission (say) then the checksum you get is the mission checksum, not the `MAV_MISSION_TYPE_ALL` checksum. 
@IamPete1 @MatejFranceskin @julianoes This makes sense? Pete, I am assuming you did not do the "all" case in another order? If so, we can modify to match you.
Guys, this also counts as an introduction. Pete is implementing this on ArduPilot/Mission Planner. Matej will do on PX4 and (presumably) QGC and Julian will do on MAVSDK. If you have concerns about this, or suggestions for …

Clarify how MAV_MISSION_TYPE_ALL checksum is calculated

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

`MAV_CMD_DO_UPGRADE` was added in #1382 as WIP but appears to have no implementation in PX4.
We are trying to clean up common.xml of WIP features, and more generally of those that do not comply with the [governance model](https://docs.google.com/document/d/1Bb0qF_ldeqGpy3OqtECclrKm00TB1rjZNXCmRopgmio/edit). Work for this is being tracked in https://github.com/mavlink/mavlink/issues/1669
NOTE I have confirmed from @TSC21  that this is not yet in PX4, and may not even be in use by customers upstream of PX4. I am therefore merging this to move it into development. 
I am also going to create another PR to remove it from development.xml - I don't want to break upstream but this message is not great.

[WIP] Move MAV_CMD_DO_UPGRADE to development.xml

---

message_definitions/v1.0/common.xml

CELLULAR_CONFIG is no longer WIP as discussed in dev call.

CELLULAR_CONFIG - remove wip tagging

---

message_definitions/v1.0/common.xml

As mentioned in #1730 , there is no GLOBAL_POSITION anymore, so it makes sense to remove any references to it or replace them with GLOBAL_POSITION_INT.

common: remove references to GLOBAL_POSITION

---

message_definitions/v1.0/common.xml

Concept: include a board ID from the `board_types.txt` in the mavlink stream to help GCSs out.  Can be useful when verifying parameters are correct.  Can be useful when working out whether there's a firmware upgrade for a board.
The WIP ArduPilot PR to use this is here: https://github.com/ArduPilot/ardupilot/pull/19001/files
I'm a bit leery of tying mavlink definitions to specifications not-actually-mavlink, but this would be really rather useful, I think.  OTOH, the existing "silicon-id" kind of already makes assumptions which might not be valid depending on implementation.

common.xml: use top 16 bits of AUTOPILOT_VERSION.board_version for board-id

---

message_definitions/v1.0/ASLUAV.xml
message_definitions/v1.0/all.xml

The ASLUAV was not included in the `all.xml` dialect due to a message id conflict with ardupilot `GIMBAL_CONTROL` messages.
- This PR moves the ASLUAV dialect into `all` dialect by moving conflicting message IDs in the ASLUAV dialect
- `SATCOM_LINK_STATUS` message is using one of the ardupilot dialect's mavlink 1 IDs as was discussed in the mavlink dev call some weeks ago
@tstastny @acfloria

Include ASLUAV into all dialect

---

doc/mavlink_to_html_table_gitbook.xsl

The definition file format allows you to specify that [parameters are reserved](https://mavlink.io/en/guide/define_xml_element.html#reserved) and have a default value like this:
```xml
<param index="3" reserved="true" default="NaN" />
```
This change adds docs for the parameter like `Reserved (set to NaN)` for the above, where reserved is set to to true. 
Note, that if _no parameter_ is defined for a particular index, MAVLink defines this to mean the same as
```xml
<param index="3" reserved="true" default="0" />
```
This works properly for generated libraries but not for the docs - the parameter will simply be omitted from the docs. The reason is that the generator uses XSLT to process nodes. IF there is no node, then nothing is done.

Auto generate docs for reserved params if explicitly specified

---

message_definitions/v1.0/common.xml

Following changes:
- corrected the identical amount of bits for `GIMBAL_[MANAGER|DEVICE]_CAP_FLAGS` and `GIMBAL_[MANAGER|DEVICE]_FLAGS`.
- made the documentation for the reference frame in `GIMBAL_DEVICE_ATTITUDE_STATUS` more explicit

gimbalv2: improved documentation

---

message_definitions/v1.0/common.xml

This adds a way to request multiple CAMERA_IMAGE_CAPTURED messages. This solves the problem where it takes a long time to request all of the messages if there are many pictures in storage.
For instance to request around 1000 pictures, it can easily take several minutes depending on the link roundtrip time.
This PR is mostly to start the discussion around how to deal with that problem. Maybe extending this request/message is not the right way but there and this should be done differently.

common: request multiple CAMERA_IMAGE_CAPTURED

---

message_definitions/v1.0/common.xml

The terminology we were using to indicate the invalid value for an array where the first element value sets that the whole array is invalid was inconsistent. The terminology for this case has changed to `[value:]` in https://github.com/mavlink/mavlink-devguide/pull/404

Update invalid attribute for arrays where first element sets whole array as invalid

---

external/dialects/storm32.xml

to account for change in invalid attribute format, https://github.com/mavlink/mavlink-devguide/pull/404

storm32.xml: use [value:] invalid attribute format

---

message_definitions/v1.0/common.xml

The current SET_FOCUS_TYPEs are mainly useful for controlling the camera focus via remote control (FOCUS_TYPE_STEP or FOCUS_TYPE_CONTINUOUS) or for specific control of the focus (FOCUS_TYPE_METERS). With this PR we are adding some auto focus types, which most of the modern cameras have:
- FOCUS_TYPE_AUTO: Full automatic focus
- FOCUS_TYPE_SINGLE (aka AF-S): Good for still pictures
- FOCUS_TYPE_CONTINUOUS (aka AF-C): Good for dynamic scenes

common: add FOCUS_TYPE_AUTO

---

doc/mavlink_gitbook.py

@hamishwillee Some hyperlinks are not being created if the mavlink message/command is not preceded by a space char, e.g. `(STORAGE_STATUS_READY)`. With this, we catch at least some additional cases, like parentheses and grave accents.

docs: catch more hyperlinks

---

message_definitions/v1.0/minimal.xml

In the heartbeat/connection protocol (https://mavlink.io/en/services/heartbeat.html) it is very nicely described that the type of the component should be identified through MAV_TYPE and not through its component id.
A necessary implication is that any type present in the MAV_COMP_ID list must also be present in the MAV_TYPE enum (i.e., that for each default MAV_COMP_ID there must be a suitable type available in the MAV_TYPE enu), but not vice versa.
For some types reflected in MAV_COMP_ID there is however no matching MAV_TYPE. This PR attempts to resolve this. (I actually wonder how it could happen that e.g. GPS isn't there).
For some MAV_COMP_ID it appears pretty clear what the MAV_TYPE should be, but for some it is actually not so clear to me. Hence this PR may not be the final answer …

Adding some missing MAV_TYPEs

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This moves the existing but unesd COMPONENT_CAP_FLAGS enum from common.xml to development.xml.
This came up because a gimbal manufacturer would like to have an easy way to know if a system (drone or camera) supports the v2 gimbal protocol.
The alternative is sending a MAV_CMD_REQUEST_MESSAGE for GIMBAL_INFORMATION which might work for this case but not well for any case, e.g. MAVLink FTP or params. The challenge when trying to detect these protocols is usually whether a timeout means it's not supported or whether the link was bad at the time we wanted to find out (e.g. at the beginning when you get a lot of initialization traffic).
This brings back part of what was removed in https://github.com/mavlink/mavlink/pull/1408.

dev: add new message for component capability

---

message_definitions/v1.0/common.xml

`MAV_SYS_STATUS_SENSOR_*` bit field last bit to be used to indicate the health of a parachute system.

SYS_STATUS: Extend system status flags, and add flag for recovery system

---

message_definitions/v1.0/development.xml

title says it
if there is a gimbal v2 protocol flag there should be also a camera protocol flag, shouldn't it?

Component Information Basics: add camera cap flag

---

message_definitions/v1.0/common.xml

Flight stacks routinely allow autotuning of specific axis. Both PX4 and ArduPilot support this (for FW only) using parameters. This PR allows a GCS to set the relevant axis to tune without having to know what those axis are - essentially making it easier for a GCS to support an unknown flight stack.
Note that the default value of 0 means "do whatever you would normally do". A receiving system that has not been upgraded to understand the value should reject non-zero values with an error "as standard", but it may not. Either way though, in this case the specific axes setting will be ignored.
The command simply enables and disables autotuning.
[ArduPilot implements](https://ardupilot.org/plane/docs/automatic-tuning-with-autotune.html#automatic-tuning-with-autotune) as a FW mode (only). 
- …

Add ability to specify axis to autotune

---

message_definitions/v1.0/common.xml

Fixes typo in this value found by @amilcarlucas in https://github.com/mavlink/mavlink/pull/1759/files#r777763295
No one will have implemented this yet, so I am self merging.

common.xml: AUTOTUNE_AXIS_YAW - fix value to correct one for bitmask

---

message_definitions/v1.0/common.xml

- Added additional flags to `status` of the **WINCH_STATUS** message. 
- Added additional actions to the **WINCH_ACTIONS** enum for the **MAV_CMD_DO_WINCH** command.
- Renamed **MAV_WINCH_STATUS_*** to **WINCH_STATUS_*** and actions **WINCH_*** to **WINCH_ACTION_***
This PR is specifically to enable support for a smart winch which implements the new winch status flags and actions. I worked with @julianoes on this solution as to avoid using custom messages/commands in our product. The only quirk with this solution is that states are being encoded into the field meant for status flags, which aren't quite the same thing (states are mutually exclusive while flags are not) -- but I feel this is only a minor flaw.

Extend WINCH_STATUS_FLAG and WINCH_ACTION

---

examples/linux/mavlink_udp.c

This fixes the compile error of mavlink_udp.c.
I added extended bits added by #1751.

add extended sensor status bits to MAVLink UDP example

---

message_definitions/v1.0/common.xml

[MAV_PROTOCOL_CAPABILITY_PARAM_UNION](https://mavlink.io/en/messages/common.html#MAV_PROTOCOL_CAPABILITY_PARAM_UNION) was described as :
> Autopilot supports the new param union message type.
- There does not appear to be any message that might conceivably be this "param union" message.
- There is no mention or appearance it on search of mavlink/mavlink, other than this issue raised by OllieW #1153 which I should have properly addressed at the time.
- Grep shows this bit is not set in the PX4 or ArduPilot codebase.
My assumption is that whatever it was intended for never happened. Now I could just deprecate this, but I think it can actually be safely reused. I have therefore indicated that in this change.
@auturgy @julianoes You OK with this?

MAV_PROTOCOL_CAPABILITY_PARAM_UNION - never implemented

---

message_definitions/v1.0/common.xml

`MAV_PROTOCOL_CAPABILITY_MISSION_FLOAT` indicates support for the deprecated `mission_item` message. This update marks it as deprecated.
I believe the plan is actually to delete these flags at some point, when they are not being set by active systems.

MAV_PROTOCOL_CAPABILITY_MISSION_FLOAT - deprecate

---

message_definitions/v1.0/common.xml

`MAV_PROTOCOL_CAPABILITY_FLIGHT_INFORMATION` indicates support for the flight information protocol but that is not documented. Looking into this, all it means is that [FLIGHT_INFORMATION](https://mavlink.io/en/messages/common.html#FLIGHT_INFORMATION) an be emitted on request, using `MAV_CMD_REQUEST_MESSAGE`
That's a waste of a capability bit. You can just send `MAV_CMD_REQUEST_MESSAGE` to determine if it is supported, which has no problematic side-effects. Further, it is just as likely that if you trust this capability bit you will be wrong. For example, I believe PX4 emits this message but does not set the bit. 
As no one sets the bit and it serves no useful purpose, I have marked it as reserved.
@auturgy @julianoes OK with this? If not I can make the text to "Autopilot supports the …

MAV_PROTOCOL_CAPABILITY_FLIGHT_INFORMATION - mark as reserved capability

---

message_definitions/v1.0/development.xml

I think it might make sense to re-use the existing capability flags from AUTOPILOT_VERSION also for COMPONENT_INFORMATION_BASICS. Otherwise, we have weird parallel flags that conflict with the existing ones.
If/when we run out of these 64 flags, we can extend both messages, AUTOPILOT_VERSION, and COMPONENT_INFORMATION_BASICS with another 64 bits of MAV_PROTOCOL_CAPABILITY_2.
@hamishwillee,@olliw42, @auturgy what do you think? Good idea or bad idea?

component_info: re-use protocol capabilities

---

message_definitions/v1.0/common.xml

~The component information has been implemented in the latest QGC 4.2.0, therefore it makes sense to stabilize this and remove the WIP tag.~ We'll leave it there a bit longer until we are confident this is good to go.
Also, this adds an explanation of why we have general and peripherals URLs, as well as that there can be more files inside the general metadata file.

Component information: add note

---

message_definitions/v1.0/minimal.xml

This enables a component to identify as a winch.

minimal: add MAV_TYPE_WINCH

---

message_definitions/v1.0/development.xml

EDITED. This has been updated to match the proposed [RFC 0016 - Mavlink Standard Modes #17](https://github.com/mavlink/rfcs/pull/17) as of https://github.com/mavlink/rfcs/pull/17/commits/0df3db8075447418fc886a651d96a8117c9a6eaa
It provides the four parts agreed in the RFC:
- A simple and agreed set of common modes. 
- A way to set those modes
- A way to get the current mode
- A way to determine what modes are supported - ideally both standard and custom.
This proposal attempts to keep everything the same for existing systems - it is a pure addition. It allows you to discover the available modes and the mapping between them. A GCS can  therefore choose to just support standard modes, or it can detect and use any other mode it likes without having to know the underlying system.

Proposal: Support for common flight modes

---

message_definitions/v1.0/AVSSUAS.xml

4ee1eeb changed the `<include>` directive of AVSSUAS and added a directory prefix that is now useless, since all dialects were moved into the same folder.
This is causing problems with generation of external libraries.
This PR fixes the issue.

fix common.xml include in AVSSUAS

---

message_definitions/v1.0/common.xml

[MAV_PROTOCOL_CAPABILITY_FTP](https://mavlink.io/en/messages/common.html#MAV_PROTOCOL_CAPABILITY_FTP) currently says:
> Autopilot supports the new FILE_TRANSFER_PROTOCOL message type.
This changes that to mean "supports FTP protocol v1 as documented in the devguide" (and now supported by PX4, ArduPilot, QGC, MAVSDK and possibly more). If you don't support this version you don't set it.
The justification for this is that it provides us a clear link to the actual protocol implemented by all these cases, so that if we make this better in future (please!) we have an upgrade path. We should define a bit for this, and I'd prefer it was this bit so that none of the existing systems need to do anything to be compliant. 
**Further, this removes the discussion of "opaque/private" implementations.** …

[Discuss.] MAV_PROTOCOL_CAPABILITY_FTP - supports FTP protocol not specific message

---

message_definitions/v1.0/common.xml

`MAV_PROTOCOL_CAPABILITY_FLIGHT_TERMINATION` this explicitly names the supported command. That both removes any ambiguity about the command (were there to be one in future) and also creates a link in the documentation. 
Note that we probably shouldn't have wasted a protocol bit on this. It isn't needed - you could just sent the command with param1=0 and the vehicle should not terminate, but should ACK to indicate that it understand the command.

MAV_PROTOCOL_CAPABILITY_FLIGHT_TERMINATION - improve linking to command

---

doc/mavlink_gitbook.py

This updates the docs generator to remove the core dialects/external dialects separation from the dialects page (https://mavlink.io/en/messages/ ) since this distinction isn't supported any more by the infrastructure.
This fix further restructures the entry point page to be about "message definition files" with sections for standard, dialects, test XML.

Remove external dialect doc and improve dialect pages

---

message_definitions/v1.0/common.xml

This tidies the description of the `COMPONENT_INFORMATION` message to be a little more precise, and in particular to link to the documentation about it.
@bkueng FYI only,

Component info - tidy descriptiosn

---

message_definitions/v1.0/common.xml

This way it's much easier to deal with these message as the last char can just be set to '\0' before handing it. Otherwise the string needs to be copied first.

camera/component information: URI zero termination

---

message_definitions/v1.0/common.xml

Parameter values may be of many types, e.g. int32. These are sent by the parameter protocol in message fields of type `float` either cast directly into the float or byte-wise encoded in the "underlying data" of the float. 
These two approaches are incompatible, and there is no way to infer which is being used. For this kind of thing the normal approach is to use a protocol bit.
As discussed in the dev call [20220216](https://github.com/mavlink/mavlink/wiki/20220216-Dev-Meeting) this PR proposes to use `MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_BYTEWISE` and `MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST` for this purpose, renamed from `MAV_PROTOCOL_CAPABILITY_PARAM_UNION` and `MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT` respectively. This will allow a GCS to detect the encoding used without having to …

Rename and document parameter encoding protocol bits.

---

.gitignore

When I build the docs locally these show up in git. This is to prevent that happening.

Tell git to ignore the doc/messages folder

---

message_definitions/v1.0/common.xml

This change
- moves `MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST` from id `2` to id `131072` 
- reverts the value of id `2` to `MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT` (changed in #1799) and marks it deprecated.
The change in #1799 was made under the incorrect assumption that `MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT` was not set by any flight stack and hence could be renamed and documented to properly explain its meaning - i.e. parameter values are encoded using a C-cast.
In fact BOTH PX4 and ArduPilot set this. What this means is that ID2 cannot be used for `MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST` because a false signal would be sent by PX4 in old versions, which defeats the purpose.
As neither PX4 or ArduPilot have updated yet, this is an urgent fix to update the signals correctly. Things …

Param protocol bits: revert float, move c_style

---

message_definitions/v1.0/common.xml

This removes the functionality to do a speed change in a relative way (e.g. 5 m/s slower) rather than an absolute way (10 m/s).
This option in param4 had been [added in 2016](https://github.com/mavlink/mavlink/commit/320f616179d5088ce3a37147aa79a81d07ea848a) but neither implemented in PX4 nor ArduPilot from what I can tell.
While this option might be a good idea, there is - at this point - no safe option to add the functionality. If we were to start using the
option, then it might not work correctly if the autopilot does not actually check param4.
Additionally to the fact that we can't start using it, the API is also odd in that a negative speed (or at least -1) is generally ignored, so a relative change that is slower (negative) would likely not work either.
I think the safe bet is to …

common: remove option for relative speed change

---

message_definitions/v1.0/minimal.xml

There is no MAV_TYPE for the vehicle known as a quadplane or standard vtol - a vehicle that takes off and lands on its belly, which has fixed separate rotors for vertical flight.  Commonly `MAV_TYPE_VTOL_RESERVED2` has been used for this.
This PR un-reserves `MAV_TYPE_VTOL_RESERVED2` (22) replacing with:
>  `MAV_TYPE_VTOL_FIXEDROTOR` - VTOL with separate fixed rotors for hover flight. Takes off and lands on belly.
While doing this I realised that naming is pretty adhoc, so I propose a naming convention: 
- `MAV_TYPE_VTOL_<TYPE>[_ROTORS]`, where:
- `TYPE`: TAILSITTER | FIXEDROTOR | TILTROTOR:
- `ROTORS` is string for numbers of "propulsion units" - rotors, fans, whatever.
This is optional - my assumption is that a GCS doesn't do anything special based on the number of rotors. If it did you …

VTOL - define MAV_TYPE for belly-sitting non tiltrotor

---

message_definitions/v1.0/AVSSUAS.xml

This space breaks pymavlink generation

AVSUAS: correct MODE_M300_FORCE_AUTO_LANDING enum entry

---

message_definitions/v1.0/common.xml

We're moving to the generic requester for most commands. This adds deprecation for this case too.

Deprecate MAV_CMD_GET_MESSAGE_INTERVAL for generic MAV_CMD_REQUEST_MESSAGE

---

message_definitions/v1.0/minimal.xml

This PR update the names of the enum values:
- `MAV_TYPE_VTOL_DUOROTOR` to `MAV_TYPE_VTOL_TAILSITTER_DUOROTOR`
- `MAV_TYPE_VTOL_QUADROTOR` to `MAV_TYPE_VTOL_TAILSITTER_QUADROTOR`
This update matches the values to the naming convention discussed in https://github.com/mavlink/mavlink/pull/1808#issue-1157921604 
The change follows on from #1808 and in particular the discussion https://github.com/mavlink/mavlink/pull/1808/files#r823318681
It is in a separate PR because anyone who uses these values will need to update their code on next build with new library. Note however that code that is not rebuilt will continue to work (the change is forward compatible.

MAV_TYPE_VTOL _DUOROTOR and _QUADROTOR renamed to new format

---

message_definitions/v1.0/common.xml

The ASTM specification has been updated to include the
following additions:
- Add new Timestamp field to the System message
- Define additional enum values:
- MAV_ODID_STATUS_REMOTE_ID_SYSTEM_FAILURE
- MAV_ODID_DESC_TYPE_EMERGENCY
- MAV_ODID_DESC_TYPE_EXTENDED_STATUS

Update OpenDroneID messages to be compliant with protocol v2

---

message_definitions/v1.0/common.xml

[MAV_CMD_PREFLIGHT_STORAGE](https://mavlink.io/en/messages/common.html#MAV_CMD_PREFLIGHT_STORAGE) only has an option to reset all parameters. While some parameters hold "config" values, other params may contain values that are not meant to be configured manually. 
For example in PX4, there is  "LND_FLIGHT_T_" which containst the accumulated flight time of the system, or "COM_FLIGHT_UUID" which is a monotonically increasing flight number for a specific vehicle. These values are set by the system and are not meant for a user to configure.
This PR changes the meaning of the existing command (2) to only reset "config" values, while adding a new option (4) to completely wipe everything. 
PX4 implementation: https://github.com/PX4/PX4-Autopilot/pull/19409

Option to not reset non-configurable params in preflight storage

---

message_definitions/v1.0/common.xml

This replaces https://github.com/mavlink/mavlink/pull/1787
Add radius, and a bit flag to utilize it, to DO_REPOSITION so it's much more useful for planes in guided modes
See https://github.com/ArduPilot/mavlink/pull/240 for a matching Ardupilot/mavlink PR

Add radius to DO_REPOSITION v2

---

message_definitions/v1.0/common.xml

[WIND_COV](http://mavlink.io/en/messages/common.html#WIND_COV) (wind covariance) message set units of `horiz_accuracy` and `vert_accuracy` to `m`. However these are not covariances - they are standard deviations of the speed, so should have the same units (m/s)
This updates the units of those fields.
Fixes #1838

WIND_COV - accuracy units are m/s

---

message_definitions/v1.0/common.xml

Was superseded by GPS_RTCM_DATA around 2017 https://github.com/mavlink/mavlink/commit/8e940ab45b10a2ea26463d55320e7f1966f372d8
As discussed in https://github.com/mavlink/mavlink/issues/1557#issuecomment-1117014996 this is not used in PX4 or ArduPilot.

Deprecated GPS_INJECT_DATA

---

message_definitions/v1.0/common.xml

This should clarify the meaning of the wind variability and wind accuracy a bit.
Also, it describes the values to signal when a value is unknown.
In my opinion it is fine to change the meaning of the variability slightly as it is hard-coded in PX4, and not implemented in ArduPilot (since ArduPilot uses WIND, not WIND_COV).
As suggested in https://github.com/ArduPilot/ardupilot/issues/4230#issuecomment-222572110.

WIND_COV: clarify description and unknown value

---

message_definitions/v1.0/common.xml

The home position is set at/after takeoff (and may also be set later using MAV_CMD_DO_SET_HOME - though if this is done before it is set on takeoff the value will be over-written). It is defined as the default position that the vehicle will return to.
This was explained primarily in deprecated messages (not current messages) and also there were cases where the term "home location" was used.
This PR updates all the HOME_POSITION related commands and messages to clearly explain what the position is and cross link to each other. It also turns instances of home location into home position.
This is a consistency change across the related content, and should have no impact. @auturgy @julianoes

Clarify and cross reference home position everywhere

---

message_definitions/v1.0/ardupilotmega.xml

This adds a new ArduPilot specific NAV_ATTITUDE_TIME command which allows the user to specify an attitude they would like the vehicle to maintain for a specified period of time during.  This can be useful if a user wants to, for example, specify that a copter should drift with the wind for 10 seconds (they could set roll, pitch and climb_rate arguments to zero).
This has [already been merged into the AP specific mavlink](https://github.com/ArduPilot/mavlink/pull/272) but if there's interest in other teams using this message I'm happy to move it to common.xml instead.
This has been tested successfully in SITL using AP.

ardupilotmega: add nav_attitude_time command

---

CMakeLists.txt

This adds an option for cmake to skip the pymavlink install. Without this option a local install will still try to install pymavlink system-wide which is not required in my use case, and would also require root privileges.

cmake: add option to disable pymavlink install

---

message_definitions/v1.0/common.xml

This attempts to better capture a comment from @MaEtUgR in https://github.com/mavlink/mavlink/pull/1651#issuecomment-1150885749 that he wasn't entirely clear that MAV_CMD_RUN_PREARM_CHECKS  was needed for the case where prearm checks are run at fairly low rate, or not run when things happen that might cause the armable state to change.
What I've done is added that information. I also noted that SYS_STATUS is one way the results might be reported. MAVLink doesn't actually specify anything about this, but PX4 will doubtless use EVENTS in future (and I suspect ArduPilot may too).
@MaEtUgR @peterbarker is this acceptable?

MAV_CMD_RUN_PREARM_CHECKS - capture intent better

---

message_definitions/v1.0/common.xml

This adds an optional quality percentage to the ODOMETRY message. In some cases we don't have usable covariances (or any at all).

common: ODOMETRY add optional quality field

---

component_metadata/actuators.schema.json
component_metadata/parameter.schema.json
doc/mavlink.php
doc/mavlink_gitbook.py
examples/linux/mavlink_udp.c
message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml
message_definitions/v1.0/matrixpilot.xml
message_definitions/v1.0/storm32.xml
message_definitions/v1.0/uAvionix.xml

This PR applies automatic edits done with the following command:
codespell --summary --ignore-words-list mot,ned,parm,parms,upto --skip cmake --write-changes
Except the changes in component_metadata/actuators.schema.json all edits are done in texts means for humans, such as descriptions and comments.

Fix spelling errors

---

message_definitions/v1.0/common.xml

this is required for the pre-arm check that the transmitter is ready
and passing tests
message ID chosen so as not to conflict with PR #1865

common: added OPEN_DRONE_ID_ARM_STATUS

---

message_definitions/v1.0/common.xml

this is a bandwidth efficient way to update the OPEN_DRONE_ID_SYSTEM message data when there is limited uplink bandwidth. Testing on real vehicles shows that with RFD900x radios at an air data rate of 125kbit/s with OPEN_DRONE_ID messages with 1Hz update (as required by FAA RemoteID standard) that there is significant impact on the ability of the GCS to give commands to the flight controller. For example, I got a high degree of packet loss in downloading parameter pre-flight, and many/most in-flight commands failed from the GCS.
By using this message we can use the minimum required bandwidth for updating operator location while remaining FAA RemoteID standard compliant
MAVProxy implementation here: https://github.com/ArduPilot/MAVProxy/pull/1098
ArduPilot MAVLink PR: …

common: added OPEN_DRONE_ID_SYSTEM_UPDATE message

---

message_definitions/v1.0/common.xml

The message MISSION_CURRENT is a bit limited as it sends the current mission item sequence but no context.
My proposition would be to include the total as well as the status of an ongoing mission.
Related to https://github.com/mavlink/mavlink/pull/1868.

common: extend MISSION_CURRENT

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This proposed message is no longer required as the plan is to implement MISSION_CHECKSUM instead.

development: remove MISSION_CHANGED

---

message_definitions/v1.0/common.xml

Autocontinue field can be set true or false. If true when the mission item is "achieved" it will start executing the next item. If false, it will pause until explicitly commanded to proceed using MAV_CMD_DO_PAUSE_CONTINUE or MAV_CMD_OVERRIDE_GOTO.
This makes it clear how the command should be used - since it wasn't clear what values would cause what behaviour.

Mission item - document values for autocontinue

---

message_definitions/v1.0/common.xml

The MAV_ODID_ARM_STATUS entries did not following naming convention.
This fixes them. 
This is a breaking compile-time change, but does not break existing systems. So "OK".
@tridge @ThomasDebrunner

MAV_ODID_ARM_STATUS entries update to naming convention

---

message_definitions/v1.0/common.xml

This removes wip tagging from the current set of OpenDroneID messages
Note that there was an open question in the dev call about whether `OPEN_DRONE_ID_ARM_STATUS` should/could be represented by a [HEARTBEAT.system_status](https://mavlink.io/en/messages/common.html#HEARTBEAT) of [MAV_STATE_STANDBY](https://mavlink.io/en/messages/common.html#MAV_STATE_STANDBY) (and maybe also [MAV_STATE_ACTIVE](https://mavlink.io/en/messages/common.html#MAV_STATE_ACTIVE)).
The argument being that the semantics are correct and this would (if possible) save unnecessary steaming of a whole additional message.
- James pointed out benefit of having the whole interface together and obvious, not hidden away in heartbeat
- Tridge argues the reason field in  `OPEN_DRONE_ID_ARM_STATUS` is needed.
- Those arguments …

common: OpenDroneID messages no longer WIP

---

message_definitions/v1.0/common.xml

This changes one of the unused params in `MAV_CMD_DO_SET_MISSION_CURRENT` so that it can be used to reset a mission "fully".
Prior to this the command would just update the current mission item.
- if the mission was completed it would stay complete, with no way to restart other than re-uploading the mission or landing and taking off again (which triggers mission reset).
- if the mission was active you could go back to the start point but the mission would not reset jump counters. 
With this change you can optionally specify that setting the current mission item also clears any "completion status" and makes the mission active again, and that the mission counters are reset.
This effectively means that  `MAV_CMD_DO_SET_MISSION_CURRENT` can be used as a hypothetical "reset mission" command by …

MAV_CMD_DO_SET_MISSION_CURRENT - allow mission resetting

---

message_definitions/v1.0/minimal.xml

This is my attempt to avoid some confusion around MAV_COMP_ID_SYSTEM_CONTROL. Essentially, it shouldn't be used anymore.
Replacing it with MAV_COMP_ID_ALL only makes sense as a target though, and not as a source.
@hamishwillee let me know what you think. I had someone confused about this the other day but I can't remember the specifics. What I do remember is making a todo to make it less confusing, and this is my attempt to do so.

minimal: try to make component ID less confusing

---

message_definitions/v1.0/common.xml

This adds documentation to the TIMESYNC message including information about timestamp units (ns) and format, and the message sequence.
As discussed in https://github.com/mavlink/mavlink-devguide/pull/433 the original message was broadcast. That means that,  in the case that there might be multiple components requesting timesync, it is not possible to tell if a response is to a particular request. 
ArduPilot encode the system id in the request timestamp (ts1), which is perfectly "safe". However this is not 100% reliable because it is more common to sync multiple _components_ within a single system, so you still can't be sure if a response is intended for a particular component.
Therefore this adds extension fields for `target_system` and `target_component`, which allows robust …

common.xml:TIMESYNC docs and extensions

---

message_definitions/v1.0/common.xml

Clarify that the lifetime of [MAV_CMD_DO_CHANGE_SPEED](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_SPEED) is until over-ridden or a mode change.
This matches ArduPlane and what is expected for PX4 Plane. Discussed in https://github.com/PX4/PX4-Autopilot/issues/20159#issuecomment-1240619736 and

DO_CHANGE_SPEED - clarify lifetime of speed setting

---

message_definitions/v1.0/common.xml

MAV_FRAME_BODY_FRD is actually implemented in ArduPilot and PX4 as a body-aligned local frame, and this is what users would expect.
@tridge @julianoes @dakejahl Are we OK with this wording?

MAV_FRAME_BODY_FRD - match to implementations and sanity

---

message_definitions/v1.0/common.xml

DO_CHANGE_SPEED is useful for temporarily overriding flight speeds, but when you are done with an override the only way I can see to either know the default tuned speed (which means reading vehicle parameters/have specific flight controller knowledge), or to change flight modes and then change back, and hope that your flight controller chooses to reset the target speed (which might just be an ArduPilot undocumented behavior). These are obviously both terrible solutions, because one requires specific knowledge about the flight stack, the other requires undocumented behaviour, requires more commands to be sent, and can result in changing more then desired.
This just adds a special case of -2 to be resume the default tuned value for the speed, allowing a very easy end to any speed override. …

Support a return to default speed for DO_CHANGE_SPEED

---

message_definitions/v1.0/all.xml
message_definitions/v1.0/ardupilotmega.xml
message_definitions/v1.0/cubepilot.xml

This PR adds mavlink messages used by Cubepilot hardware, and also reserves IDs for future use. This has already been merged in Ardupilot/mavlink fork.

add vendor specs for cubepilot

---

.github/workflows/test_and_deploy.yml

This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/mavlink/mavlink/actions/runs/3148604498/jobs/5119313621#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflow:
- test_and_deploy.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-fo …

ci: add minimum GitHub token permissions for workflow

---

message_definitions/v1.0/common.xml

MAV_CMD_SET_MESSAGE_INTERVAL can be used to set a default interval. This update makes it clear that the default interval might be 0 (and probably will be if the message isn't streaming when this is first sent).
This is to reduce the minor risk that someone will call the method expecting default to mean "some sensible non-zero value"; if the value is not streaming then the sensible default value is zero.
As discussed with @peterbarker .

MAV_CMD_SET_MESSAGE_INTERVAL - default interval may be 0

---

message_definitions/v1.0/common.xml

Fixes copy paste typo described here https://github.com/mavlink/mavlink/pull/1799#discussion_r994348458

fix typo MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml
message_definitions/v1.0/standard.xml

There are three core XML definition files that comprise the standard; at time of writing everything else is a dialect. The meaning of these is (at least historically):
- `minimal.xml`: The minimal set of XML definitions needed to have a functioning mavlink network. 
- `standard.xml`: The set of XML definitions that are "standard". The expectation is that these definitions are supported by at least two flight stacks in a compatible way. You could reasonably hope that most flight stacks would support them.
- `common.xml`: A library of definitions; a flight stack does not have to support these definitions, but if it supports the kind of functionality it must use the definitions from the library.
This is still a logical and desirable setup, albeit the descriptions do not precisely describe …

Common should depend on standard and not visa versa

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

- Extended status (state) flags 
- Extended actions to support Eject Package and Load Package
- Added Component ID for Winch

Winch extended support

---

message_definitions/v1.0/common.xml

This removes wip tagging from: MAV_CMD_CAMERA_TRACK_POINT, MAV_CMD_CAMERA_TRACK_RECTANGLE, MAV_CMD_CAMERA_STOP_TRACKING, CAMERA_FOV_STATUS, CAMERA_TRACKING_IMAGE_STATUS, CAMERA_TRACKING_GEO_STATUS
This is (I understand) in a number of mavlink camera vendors and has also been integrated into QGC and MAVSDK. I am not sure about PX4 "integration". I do know that both ArduPilot and PX4 allow passthrough of these messages, so will work with cameras supporting the API.
Follows up plan to remove WIP where possible in #1669
FYI @auturgy @julianoes

Camera Protocol v2 - Remove WIP tracking

---

message_definitions/v1.0/common.xml

This is the first of a sequence of four PRs, which are intended to finally get the looming changes with regards to the gimbal device protocol merged. These are of two kinds: handling of yaw absolute and relative, and handling of RC signals.
The four PRs are:
1. https://github.com/mavlink/mavlink/pull/1911
2. https://github.com/mavlink/mavlink/pull/1912
3. https://github.com/mavlink/mavlink/pull/1914
4. https://github.com/mavlink/mavlink/pull/1913
The additions to the gimbal device flags and messages have been discussed and agreed to before in
- https://github.com/mavlink/mavlink/issues/1860 "Yet another effort towards unified gimbal device messages"
- https://github.com/mavlink/mavlink/pull/1885 "gimbal: more flexible attitude messages"
see especially …

Gimbal Device: Some spelling

---

message_definitions/v1.0/common.xml

This is the fourth of a sequence of four PRs, which are intended to finally get the looming changes with regards to the gimbal device protocol merged. These are of two kinds: handling of yaw absolute and relative, and handling of RC signals.
The four PRs are:
1. https://github.com/mavlink/mavlink/pull/1911
2. https://github.com/mavlink/mavlink/pull/1912
3. https://github.com/mavlink/mavlink/pull/1914
4. https://github.com/mavlink/mavlink/pull/1913
The additions to the gimbal device flags and messages have been discussed and agreed to before in
- https://github.com/mavlink/mavlink/issues/1860 "Yet another effort towards unified gimbal device messages"
- https://github.com/mavlink/mavlink/pull/1885 "gimbal: more flexible attitude messages"
see especially …

Gimbal Device: Adding RC handling

---

message_definitions/v1.0/common.xml

This is the third of a sequence of four PRs, which are intended to finally get the looming changes with regards to the gimbal device protocol merged. These are of two kinds: handling of yaw absolute and relative, and handling of RC signals.
The four PRs are:
1. https://github.com/mavlink/mavlink/pull/1911
2. https://github.com/mavlink/mavlink/pull/1912
3. https://github.com/mavlink/mavlink/pull/1914
4. https://github.com/mavlink/mavlink/pull/1913
The additions to the gimbal device flags and messages have been discussed and agreed to before in
- https://github.com/mavlink/mavlink/issues/1860 "Yet another effort towards unified gimbal device messages"
- https://github.com/mavlink/mavlink/pull/1885 "gimbal: more flexible attitude messages"
see especially …

Gimbal Device: Adding handling of absolute/relative yaw

---

.github/workflows/test_and_deploy.yml

This should fix the node CI tests.
This includes https://github.com/ArduPilot/pymavlink/pull/752.

pymavlink: update submodule

---

message_definitions/v1.0/common.xml

Following discussion with Peter Barker and AndrewTridgell, a small change to the description of the ATTITUDE message to clarify Euler rotation order is ZYX.

Clarifying Euler angle axis order

---

message_definitions/v1.0/common.xml

This adds a flag to the gimbal device error flags which indicates that the gimbal device is not assigned to a gimbal manger.
This is useful to check/see if the system is healthy (operational). It is not strictly an error, like calibration is not strictly an error, but like calibration it is a mal condition. Note that gimbal devices must not be used except by the gimbal manager, which implies that there must be such a gimbal manager and that the gimbal device must have discovered its gimbal manager.
Such as flag is also in the storm32.xml protocol, and was found to be useful.

Gimbal Device: Add error flag no gimbal manager

---

message_definitions/v1.0/common.xml

The ZOOM_TYPE_RANGE and CAMERA_MODE imply that ranges are percentages of full range, but feedback from an implementer is that this is not canonical/is ambigous. Removing possible confusion.

common.xml - camera zoom settings - range values percentages of full range

---

message_definitions/v1.0/common.xml

I can not find CELLUAR_STATUS_FAILED, may be it means CELLULAR_STATUS_FLAG_FAILED ?

fix CELLULAR_STATUS typo

---

message_definitions/v1.0/development.xml

This enables a use case where the serial number of a component is required, in our case it's a winch.

component_information_basics: add serial number

---

message_definitions/v1.0/common.xml

The lower 16 bits of the gimbal manager flags and cap flags are supposed to coincide the gimbal device flags and cap flags. This PR aligns the manager flags & cap flags with the recent additions to the gimbal device flags & cap flags. I have also added .'s in the descriptions of the gimbal manager flags, as it's so in the descriptions of the gimbal manager cap flags.

Gimbal manager: Add gimbal device flags to low word of gimbal manager flags

---

message_definitions/v1.0/minimal.xml

Quoting the Wikipedia article on [Tiltwing](https://en.wikipedia.org/wiki/Tiltwing):
> A tiltwing aircraft features a wing that is horizontal for conventional forward flight and rotates up for vertical takeoff and landing. It is similar to the tiltrotor design where only the propeller and engine rotate. Tiltwing aircraft are typically fully capable of VTOL operations.
I took the liberty of re-purposing `MAV_TYPE_VTOL_RESERVED4` for this aircraft type. Of course I would be totally fine with adding a new type instead.

Add the MAV_TYPE_VTOL_TILTWING aircraft type

---

.gitignore
message_definitions/v1.0/development.xml

This moves the Airspeed message it to common and re-works it in preparation for a ArduPilot implementation (https://github.com/ArduPilot/ardupilot/pull/21729#issuecomment-1263644965).
This drops several fields to save bandwidth. Changes two pressures to a single raw pressure. Removes error and type in favor of a flags field. Finally it changes to always report indicated airspeed.

Airspeed message: update

---

message_definitions/v1.0/common.xml

From https://github.com/ArduPilot/mavlink/pull/297
Add support for reporting fuel pressure in the EFI_STATUS message. Fuel pressure is already measured and logged in ArduPilot and it can be a useful measurement to report to the GCS for diagnosing problems on the ground.

common.xml: add fuel_pressure ext. to EFI_STATUS

---

component_metadata/actuators.schema.json
component_metadata/actuators.translation.json
component_metadata/parameter.schema.json
component_metadata/parameter.translation.json
component_metadata/translation.schema.json

@hamishwillee this adds the translation support as discussed in https://github.com/mavlink/mavlink/issues/1656.
- Uses a summary json file with urls and modification timestamps to individual translated (and compressed) .ts files.
I setup an example repo under https://github.com/bkueng/px4_metadata_translations. It explains the work-flow, CI integration is not done yet. @hamishwillee do you want to look into that? In particular for the CrowdIn integration.
- It's generic so new metadata types do not require GCS changes.
- Versioning: there's different approaches, probably the simplest is to use branches in the metadata repo.
- QGC implementation: https://github.com/mavlink/qgroundcontrol/pull/10522
TODO (outside of mavlink):
- CI integrations & crowdin sync
- Documentation

COMPONENT METADATA: translation

---

scripts/test.sh

Let's look at why the node test is failing.
Turns out we need to do a `npm install` to get mocha.

Update submodule and check CI

---

message_definitions/v1.0/storm32.xml

#1941 contains an invalid enum reference that breaks generation of external libraries.
I searched for the enum definition but i couldn't find it, therefore it should be removed unless @olliw42 provides it.

remove invalid enum reference from storm32.xml

---

message_definitions/v1.0/development.xml

This is a command that allows to set AT parameters of SiK radios connected to a drone.
For example, this can be used to set the ID of a radio allowing it to be paired to another ground radio. This can be used for configuration at initial setup but also during a mission to specifically swap to a new ground radio.
More details on the possible configuration options can be found in:
https://ardupilot.org/copter/docs/common-3dr-radio-advanced-configuration-and-technical-information.html#using-the-at-command-set
https://docs.px4.io/main/en/data_links/sik_radio.html
For PX4, this would replace the existing ID configuration using a parameter which does not have proper feedback.

development: add command to configure SiK radio

---

message_definitions/v1.0/all.xml

Ras-a have agreed to restrict ids to allocated range. This chooses the free range:
messages: 51000 - 52000
commands: 51000 - 52000
Also added a placeholder to indicate the next free unallocated range (52000 +)

Allocate range for ras-a and indicate next free range

---

message_definitions/v1.0/common.xml

Enum values are supposed to be prefixed by their enum name. This changes `MAV_BATTERY_TYPE_PAYLOAD` to `MAV_BATTERY_FUNCTION_PAYLOAD`. This requires a recompile for users that specifically access this item, but is non-breaking over the wire.

Fix enum value for payload battery

---

README.md

There was some discussion about needing a quick start in the readme. This is clearly not a big problem for most users, but nor do I think it is harmful to provide an easy path for most users. 
Note, this does not include `future`, which is not needed on the listed platforms, or tkinter, which is optional. All that is linked to the official docs.

Add quickstart to the README

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This pull request extends the [LANDING_TARGET](https://mavlink.io/en/services/landing_target.html) message to include position and orientation uncertainties in order to properly fuse the landing target estimations in a Kalman filter https://github.com/PX4/PX4-Autopilot/pull/20653. It also adds the sensor's orientation at the moment of the observation, which is necessary if there is processing time (e.g. detect fiducial marker) between the observation and the message being sent. Finally, it extends the [MAV_FRAME](https://mavlink.io/en/messages/common.html#MAV_FRAME) message to allow for generic sensor frames. This allows to properly handle the [LANDING_TARGET](https://mavlink.io/en/services/landing_target.html) message: 
- if MAV_FRAME == MAV_FRAME_LOCAL_NED, the target is directly sent …

New landing target messages TARGET_ABSOLUTE/RELATIVE

---

message_definitions/v1.0/common.xml

Clarify the use of MAV_CMD_ARM_AUTHORIZATION_REQUEST, in particular w.r.t. use of progress if the request is denied.
Note that PX4 is non compliant - its sets `param2_value` rather than `progress`. Can we change this to match?
@TSC21 @julianoes

MAV_CMD_ARM_AUTHORIZATION_REQUEST - clarify use of progress

---

message_definitions/v1.0/common.xml

This starts off looking very much like MAV_RESULT but then starts to differ
Based off the name, remove this entirely so implementers are forced to move to MAV_RESULT.
Some discussion between @hamishwillee and myself here: https://github.com/ArduPilot/mavlink/pull/307
tldr is that this is broken as an enumeration to use in an extension field as a value of zero is always "unknown".

common.xml: remove MAV_CMD_ACK

---

message_definitions/v1.0/common.xml

With ArduPilot implementing these too, and some manufacturers, presumably time to remove the WIP tagging.
Any issues I should be aware of? I.e. something that no one has implemented that should remain WIP?
@julianoes Service docs indicate `MAV_CMD_DO_GIMBAL_MANAGER_TRACK_RECTANGLE` but I think you guys decided that was camera API `MAV_CMD_CAMERA_TRACK_RECTANGLE` right? 
@julianoes @olliw42 @rmackay9 @auturgy FYI Suggestions, feedback, welcome.

common - un-WIP gimbal messages

---

message_definitions/v1.0/common.xml

ArduPilot stores its home location in slot-0.
Before this change, in the case you have that home location and a single waypoint uploaded ArduPilot would report a total of 2 - but when running the mission towards this single waypoint would report going to waypoint 1.  This is contrary to expectations of the user, so exclude slot 0 from the count.
@hamishwillee please discuss but don't merge just yet?  See https://github.com/ArduPilot/ardupilot/pull/23230

common.xml: exclude any stored home location from MISSION_CURRENT.total

---

message_definitions/v1.0/common.xml

Allow the user to specify the camera zoom level as a horizontal field-of-view (HFOV) value. The primary use case for this is for systems with two cameras (with different lens/sensor combinations) where you want the two captured images to be the same.

common.xml: Add ZOOM_TYPE_HORIZONTAL_FOV to CAMERA_ZOOM_TYPE enum

---

message_definitions/v1.0/common.xml

As discussed in #1981, without a reference `MAV_FRAME` (as is sent in `COMMAND_INT`) it is possible for receiving systems to mis-interpret altitude values sent in `MAV_CMD`s. This PR updates the descriptions for `COMMAND_INT` and `COMMAND_LONG` to indicate that `COMMAND_INT` is preferred when the command includes an altitude field.

common.xml: Prefer COMMAND_INT when command includes altitude field

---

message_definitions/v1.0/common.xml

This follows on from discussion in https://github.com/mavlink/mavlink/pull/1973
The messages are already deployed and are therefore frozen. 
@Davidsastresas is working on a QGC implementation. According to @julianoes this PR is currently not compatible enough to merge, but is a fairly good indication that the existing manager set is OK. Unless there is a compelling argument that we need to change one of these messages I think this should merge.
FYI @rmackay9

Gimbal manager messages - remove WIP tagging

---

.github/workflows/test_and_deploy.yml
CMakeLists.txt

This would be a way to locally install the pip dependencies automatically. This way we don't need to get them separately. I don't have a strong opinion. Requiring the dependencies explicitly manually would also be ok.

cmake: locally install pip dependencies

---

message_definitions/v1.0/common.xml

There is no value in having `progress` being "either progress or result_param1" other than potentially it allows two separate errors to be reported at a time (which you could do anyway by providing a bitmask as your enum). However it does make the command harder to understand and implement. 
So what this does is clarify that `progress` is for progress (only) and `result_param2` is for additional result information - and that this is a separate command specific enum, with 0 value meaning "unknown", that must be documented in the associated command. 
This matches the known implementations that use `COMMAND_ACK`. It is possible that some use progress for this feedback, and this change will make those "non compliant" - but we think fairly unlikely.
This follows on from #1965 and discussion in …

COMMAND_ACK progress/result_param2 clarification

---

message_definitions/v1.0/common.xml

Per the descriptions on `COMMAND_INT` and `COMMAND_LONG`, certain `MAV_CMD`s should only be sent as one or the other. However, there is no mechanism for the receiving system to indicate this. The closest we can get at the moment is by using `MAV_RESULT_DENIED`, but that is ambiguous as to whether the issue is the `COMMAND_*` message or the actual parameters.
This PR adds two new entries to the `MAV_RESULT` enum, `MAV_RESULT_COMMAND_LONG_ONLY` and `MAV_RESULT_COMMAND_INT_ONLY`, to address this.

common.xml: Add MAV_RESULT_COMMAND_LONG_ONLY and MAV_RESULT_COMMAND_INT_ONLY to MAV_RESULT

---

README.md

update instructions to install pymavlink package instead of just its dependencies
note the instructions were broken anyway - you need the -r flag to install from a requirements file

update instructions to install pymavlink

---

message_definitions/v1.0/common.xml

According to archeology research by @peterbarker , `MAV_PROTOCOL_CAPABILITY_SET_ACTUATOR_TARGET` indicates support for [ACTUATOR_CONTROL_TARGET](https://mavlink.io/en/messages/common.html#ACTUATOR_CONTROL_TARGET). That is not a very useful message because it has no sysid or component id - and you would not want to broadcast this. 
There is another message one id earlier [SET_ACTUATOR_CONTROL_TARGET](https://mavlink.io/en/messages/common.html#SET_ACTUATOR_CONTROL_TARGET) that does have the id. But you couldn't rely on it being supported. 
This is not set by PX4 or ArduPilot. I'm tempted to mark it reserved as not used, because it is not useful. This change is the minimum for it not to be ambiguous.
@julianoes @auturgy OK, or should we just mark it reserved?

MAV_PROTOCOL_CAPABILITY_SET_ACTUATOR_TARGET for ACTUATOR_CONTROL_TARGET

---

message_definitions/v1.0/minimal.xml

GCS's typically use `MAV_TYPE` to tailor the interface to a specific vehicle type, if the vehicle has not yet been configured, or has a unusual type that does not fall in to the provided types the existing `TYPE_GENERIC` is not specific enough to give the GCS a clue about what sort of vehicle it is. 
https://github.com/ArduPilot/ardupilot/pull/22658, https://github.com/ArduPilot/ardupilot/issues/22657
On AP this can happen during initial setup when the frame class is not setup. Or if a frame type is setup that falls outside of the given types, one could use scripting to setup a vehicle with 5 rotors for example.

minimal: add `MAV_TYPE`  `MAV_TYPE_GENERIC_MULTIROTOR`

---

message_definitions/v1.0/all.xml
message_definitions/v1.0/ardupilotmega.xml
message_definitions/v1.0/csAirLink.xml

Hi. I am adding the ability to connect ground stations with Qgroundcontrol and MissionPlanner software to [AirLink lte modules](https://ardupilot.org/plane/docs/common-airlink-telemetry.html). Adding changes to master will help speed up the work.

Air-Link: Added messages for connections to air-link modules

---

.gitignore

These are more properly managed within the pymavlink repository

remove pymavlink files from gitignore

---

doc/mavlink_to_html_table_gitbook.xsl

Following on from discussion in #1982, this updates docs generator to add a note to any command that has either `hasDestination=true` or `isDestingation=true` attribute. This renders as a line at the end of the description like this:
Are we OK with the text? More questions to follow; they wouldn't block this, but would result in follow on work.
FYI @sypaq-nexton @peterbarker

Command int long fixes

---

message_definitions/v1.0/development.xml

This brings the message from https://github.com/mavlink/rfcs/pull/23.
Allows to dynamically update the list of modes.

development: add available modes monitor

---

message_definitions/v1.0/common.xml

[`MAV_CMD_VIDEO_START_CAPTURE`](https://mavlink.io/en/messages/common.html#MAV_CMD_VIDEO_START_CAPTURE), [`MAV_CMD_VIDEO_STOP_CAPTURE`](https://mavlink.io/en/messages/common.html#MAV_CMD_VIDEO_STOP_CAPTURE), 
[`MAV_CMD_AIRFRAME_CONFIGURATION`](https://mavlink.io/en/messages/common.html#MAV_CMD_AIRFRAME_CONFIGURATION), 
All have param 5, 6 [reserved](https://mavlink.io/en/guide/define_xml_element.html#reserved) as `NaN`, indicating that senders should always set the values to `NaN` even if they are unused. This allows the reserved values to be resused later on for properties where "0" is an allowed value of the setting, because you would still sent `NaN` to mean "no change".
This PR changes the reserved params to have default values of 0, such that a GCS should send 0 by default for the …

MAV_CMD_VIDEO_START_CAPTURE et al change param5/6 to 0 default

---

message_definitions/v1.0/common.xml

If MAV_CMD has a location where the frame is not explicitly specified this is taken from the `COMMAND_INT.frame` field. There is no way to query what frames are supported for a particular command by a particular flight stack. Many flight stacks just ignore the frame, using whatever arbitrary frame they support.
This adds a `MAV_RESULT_COMMAND_UNSUPPORTED_MAV_FRAME` to tell a user that the command may be valid, but not with the supported frame. If implemented a user could use this to determine what frames are supported. 
Note that if autopilots continue to do the very bad thing of silently just accepting any frame this will make no difference. But this is still "the right design" by any measure.

Add MAV_RESULT_COMMAND_UNSUPPORTED_MAV_FRAME

---

message_definitions/v1.0/common.xml

Waypoints are for missions, while do_reposition is for guided movement. You might in theory use either for both cases, but the fields are "optimized" for the particular use/would be ambiguous in the other use.
- came up in https://discord.com/channels/1022170275984457759/1115872575663382592

Clarify DO_REPOSITION vs NAV_WAYPOINT

---

message_definitions/v1.0/common.xml

MAV_CMD_PAYLOAD_PREPARE_DEPLOY had note about the units if using "MISSION_ITEM (deprecated) the units are degrees (unscaled)". This is unnecessary given that MISSION_ITEM is deprecated in all stacks.
This came out of tidy up in https://github.com/mavlink/mavlink/pull/1992#issuecomment-1560448292

MAV_CMD_PAYLOAD_PREPARE_DEPLOY - remove note about MISSION_ITEM

---

message_definitions/v1.0/common.xml

`MAV_CMD_FIXED_MAG_CAL_YAW` has latitude and longitude specified in param 3, 4, rather than 5, 6 by convention. This means that the values must be sent in a float and will be less precise than they might be.
1. Does lack of precision matter? My assumption is "no" - this is just used for getting WMM field tables which won't be granular to metres.
2. Does not having a frame specified matter? I mean, should we add "Global (WGS84) coordinate frame" is used by default?
3. Is it worth duplicating these in param 5, 6 to follow convention? We could add a note to suggest flight stacks send values in both, and param 5, 6 values be used if set, in order to eventually have a consistent command. Reason not to is "hassle" and also that 0 is a valid value. I think we should do it.
Following on from …

MAV_CMD_FIXED_MAG_CAL_YAW - help clarify frame and location

---

message_definitions/v1.0/minimal.xml

As discussed in https://github.com/mavlink/mavlink/wiki/20230607-Dev-Meeting a consumer should be able to monitor for vehicle being in a non-normal failsafe state by looking at the MAV_STATE in the heartbeat. What this does is add a note that the critical/emergency states "failsafe" so that this comes up if someone is searching for the term in the mavlink docs - I tried to find something and missed this.

Minimal.xml - MAV_STATE - add failsafe to affected states

---

message_definitions/v1.0/common.xml

This change arises out of https://github.com/mavlink/mavlink/pull/1980#issuecomment-1552208805 "should the device id be 0 or 1 indexed"
@julianoes I have taken the text you suggested from [GIMBAL_MANAGER_SET_ATTITUDE](https://mavlink.io/en/messages/common.html#GIMBAL_MANAGER_SET_ATTITUDE). However I'm not completely convinced it is correct to use gimbal component IDs.
The id absolutely does have to be indexed from one. However I thought the concept of the id as set in the manager was to abstract component IDs for the gimbal - so we'd always use 1-6 and not have to think about what device IDs were actually mapped to - the manager would sort that out.
Conceptually I find that much easier when working with a gimbal manager. I'm also a bit worried that you might have both mavlink and …

Gimbal manager/status - device ids

---

.github/workflows/test_and_deploy.yml

This removes the Python 2.7 from the test and deploy workflow. I don't think anything else is required?
Why? It's EOL and the test always fails. It's time to remove support. 
@peterbarker @auturgy @julianoes OK?

test_and_deploy.yml - remove python 2.7 tests

---

message_definitions/v1.0/all.xml

This adds additional range information to all.xml. I'd rather have this in the files themselves, but good to have an overview.
This is from https://mavlink.io/en/guide/define_xml_element.html and by inspection.
@peterbarker OK?

all.xml: Add message/command ranges for other dialects

---

message_definitions/v1.0/common.xml

Following #2006 issue. This commit adds a new field to CAMERA_INFORMATION to link it to a gimbal device. 
I think the convention should follow the same logic as gimbal device id, which is 1-6 for non mavlink gimbals ( gimbals devices "simulated" by an autopilot ) and the rest of the numbers should be interpreted as component ID, for gimbal devices that are actually an independent mavlink system.
I am not that familiar with mavlink, so I am not sure if this way it is all right, in the sense of how to present it so the message is trimmed if we are not using this field, please let me know if it needs to be fixed.

Master pr/camera info gimbal associated

---

message_definitions/v1.0/common.xml

After the discussion in https://github.com/mavlink/mavlink/pull/2013, it seems that there is a possibility that the quaternion in the `SET_ATTITUDE_TARGET` can be interpreted between different frames.
This commit clarifies which attitude the quaternion is defined in respect to the `MAV_FRAME` convention

Clarify SET_ATTITUDE_TARGET quaternion field

---

message_definitions/v1.0/development.xml

This PR removes MISSION_CHECKSUM .
MISSION_CHECKSUM is supposed to provide a checksum of various parts of the plan. The theory is that a ground station can calculate the same checksum for its current plan and therefore know if it has the current fence, mission, rally points. 
Unfortunately the theory is flawed because flight stacks do not necessarily store all the data in the original mission.
Replaced the functionality by https://github.com/mavlink/mavlink/pull/2012

development.xml - remove mission_checksum

---

scripts/update_c_library.sh

This attempts to fix the build order of the prebuilt MAVLink libraries.
The order in which things are built matters. This is due to a bug in mavgen, which means that if there are any shared enum values then they only only appear the top level library that is built.
In practise this means that if you build `ardupilotmega.xml` then `ardupilotmega/ardupilotmega.h` will contain the `mav_cmd` definitions, and `common/common.h` (which is nested) will not.
To ensure that every level of library is correct you therefore need to build top level libraries first, and then any libraries that they nest. In other words, ensure that the last time a library is built, is when it the top level library. 
This is the order to get the entire library, including everything in all.xml. IOt shows what is included …

Fix c_library_vX build order

---

message_definitions/v1.0/common.xml

Based my reading of the message types and discussion here: https://groups.google.com/g/mavlink/c/cocB5FwakRI/m/B25tXOkD3mQJ , I think this value should probably fit in an int16_t.

fix RC_CHANNELS_SCALED inactive channel

---

message_definitions/v1.0/common.xml

For various use cases additional knobs on the remote can be mapped to change the behavior of the vehicle on the fly e.g. change a tuning parameter, change the speed in one axis of the vehicle, move an actuator or payload, change the radius of the flown arc and similar. Since we cannot cover every single combination of such effect in any mode that might ever come up through the ground station sending a specific MAVLink message I suggest we introduce auxiliary continuous (aka analog) inputs which can then be mapped to have a certain effect depending on the operation mode on the receiving side.
Initial applications:
PX4 already allows mapping auxiliary RC channels to change a parameter on the fly or map certain payload functionality. The use case I'm specifically requesting this for is a …

common: extend MANUAL_CONTROL with auxiliary continuous inputs

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This pr is part of a work which aims to enable "slow mode" on a vehicle. This mode allows to scale down the vehicle's velocities by limiting the maximum values. It is useful in scenarios such as: EASA 3m/s velocity limit, camera zooming. Corresponding work can be found [here](https://github.com/PX4/PX4-Autopilot/pull/21790)
The velocity_limits message consists of: 
* ~horizontal velocity limit~ horizontal speed limit
* ~vertical velocity limit~ vertical speed limit 
* yaw rate limit

Add VELOCITY_LIMITS msg

---

message_definitions/v1.0/common.xml

I am working on enhancing camera and gimbal interface in Ardupilot, We are adding support of multiple cameras so a camera instance field is required for telling the camera in which we want to start and stop capturing images.

common:  Add camera instance field to MAV_CMD_IMAGE_START/STOP_CAPTURE

---

message_definitions/v1.0/common.xml

This adds enum for speed types that can be set in [MAV_CMD_DO_CHANGE_SPEED](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_SPEED).
Fixes #1997

SPEED_TYPE enum for MAV_CMD_DO_CHANGE_SPEED

---

message_definitions/v1.0/ardupilotmega.xml
message_definitions/v1.0/common.xml

We added SPEED_TYPE to common.xml and got no errors in building ... but we are now and it appears to be because this is already defined in ardupilotmega.xml.
I've removed from ardupilot. The values are the same for the existing value, but common defines extra values and uses SPEED_TYPE_GROUND_SPEED rather than SPEED_TYPE_GROUNDSPEED. I have modified that here to match the deleted APM stuff too.
@peterbarker @auturgy - OK?
This is what is in common. 
```
<enum name="SPEED_TYPE">
<description>Speed setpoint types used in MAV_CMD_DO_CHANGE_SPEED</description>
<entry value="0" name="SPEED_TYPE_AIRSPEED">
<description>Airspeed</description>
</entry>
<entry value="1" name="SPEED_TYPE_GROUND_SPEED">
<description>Groundspeed</description>
</entry>
<entry value="2" name="SPEED_TYPE_CLIMB_SPEED"> …
```

Update ardupilotmega.xml - delete SPEED_TYPE

---

.github/workflows/test_and_deploy.yml

The node 12 tests fail due to use of optional chaining in generated code, added in node 14. This removes node 12.
I added node 16 because we should be promoting a more recent versions. Possibly even 18.
Part of fixing #2040

Update test_and_deploy.yml - drop node 12

---

message_definitions/v1.0/development.xml

This removes the proposed cmd for setting an action. The [reasons given for this](https://github.com/mavlink/mavlink/issues/2043#issuecomment-1757452638) are mostly about it being far too complex.
The proposal is to replace it with #2048
```xml
<entry value="5010" name="MAV_CMD_SET_FENCE_BREACH_ACTION" hasLocation="false" isDestination="false">
<description>Sets the action on geofence breach.
If sent using the command protocol this sets the system-default geofence action.
As part of a mission protocol plan it sets the fence action for the next complete geofence definition *after* the command.
Note: A fence action defined in a plan will override the default system setting (even if the system-default is `FENCE_ACTION_NONE`).
Note: Every geofence in a plan can have its own action; if no …
```

development - delete MAV_CMD_SET_FENCE_BREACH_ACTION

---

message_definitions/v1.0/ardupilotmega.xml
message_definitions/v1.0/common.xml

Looking  for some guidance on if I should keep the original ID from the ardupilot dialect or if it should be changed.
I am aware of the ID ranges, however, I noticed there are other messages which were moved to common but the ID was kept.

moved MAV_CMD_EXTERNAL_POSITION_ESTIMATE from ardupilotmega to common

---

message_definitions/v1.0/common.xml

... and COMMAND_LONG_ONLY
It doesn't really matter why the command is being rejected, just that it is.
Adding constraints about why an autopilot might send the message reduces the usefulness of this.
I hit this problem when writing https://github.com/ArduPilot/ardupilot/pull/25643 .  In this case the new define in ArduPilot simply removes `COMMAND_LONG` support, so if you set the new define to true in ArduPilot *all* commands will be rejected with "INT_ONLY".  We do not want to check the validity of the commands in this case, just say, "INT_ONLY".
@nexton-winjeel

common.xml: remove validity requirement for COMMAND_INT_ONLY

---

message_definitions/v1.0/common.xml

This PR proposes a mechanism (for discussion) for determining whether part of an on-vehicle plan type (mission, fence, rally points) have changed, so that a GCS can upload the changed plan, or more importantly choose _not_ to upload a plan that it already has.
This replaces the `MISSION_CHECKSUM` which is being removed in https://github.com/mavlink/mavlink/pull/2010.
Plan upload/download can consume quite a lot of bandwidth, especially for large missions.
Currently ground stations upload the vehicle plan every time they connect, even if they already have a matching plan. Further, if a second ground station or companion updates the plan on a vehicle, there is no reliable way for other ground stations to know that they have to update.
The ideal solution for this problem is for vehicles and …

Common - Opaque IDs for detecting plan changes

---

message_definitions/v1.0/common.xml

I suspect a typo - REQUEST_DATA_STREAM was deprecated by MAV_CMD_SET_MESSAGE_INTERVAL

Fixed deprecation typo for MAV_CMD_SET_MESSAGE_INTERVAL

---

message_definitions/v1.0/common.xml

The vehicle outputs a quaternion of vehicle roll/pitch/yaw  in the [HOME_POSITION](https://mavlink.io/en/messages/common.html#SET_HOME_POSITION) message.
As discussed in https://github.com/mavlink/mavlink/pull/1843, the expectation is that either the quaternion outputs accurate values or NaNs for all value (even if you have a value for the yaw, you can't output it in the form of a quaternion unless you also have "some" roll and pitch value). 
The proposal here is that we allow the `MAV_CMD_DO_SET_HOME` to also specify a roll and pitch of the home position.
Note, there is no way to say "I don't know the pitch, roll" of the surface at home - if you don't know you're saying it's flat. Is that OK?

MAV_CMD_DO_SET_HOME - add home position roll/pitch

---

message_definitions/v1.0/minimal.xml

MAV_TYPE_VTOL_TAILSITTER was referring to old names MAV_TYPE_VTOL_DUOROTOR or MAV_TYPE_VTOL_QUADROTOR for MAV_TYPE_VTOL_TAILSITTER_DUOROTOR or MAV_TYPE_VTOL_TAILSITTER_QUADROTOR.
This falls out of discussion in https://github.com/ArduPilot/pymavlink/pull/889#issuecomment-1870058548
FYI only @peterbarker

Update MAV_TYPE_VTOL_TAILSITTER description to refer to existing types

---

message_definitions/v1.0/development.xml

the <enum name="MAV_CMD"> element with the same name existed twice in the parent enums element in the development.xml. Some xml parser seem to have a problem with that. Thus grouping them together.
Only cosmetic change, no wording message are changed.

development.xml: merge both MAV_CMD enums together

---

message_definitions/v1.0/common.xml

As a follow up to https://github.com/mavlink/mavlink/pull/2069, here is a proposal for the BATTERY_INFO message:
1. renamed SMART_BATTERY_INFO to BATTERY_INFO based on the assumption that there were no users of the old message
2. removed the extension tag because if we're going to rename the message then old consumers can't use it anyway, so no need for the last few fields to be extensions
3. added a state_of_health field just below the capacity fields which I think are all related
I suppose that more analysis is required to confirm that this message is complete before we can merge.

Common: rename SMART_BATTERY_INFO to BATTERY_INFO and add SOH

---

message_definitions/v1.0/development.xml

Manufacturer date has been requested in https://github.com/mavlink/mavlink/pull/2063, and seems generally useful.
This adds it as a unix timestamp in seconds.
FYI @julianoes @potaito @auturgy

COMPONENT_INFORMATION_BASIC - add manufacturer date

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This replaces https://github.com/mavlink/mavlink/pull/2027 - moves to develpment.xml and adds some context.
NOte that this is approved in #2086

MAV_CMD_ODID_SET_EMERGENCY - 

---

message_definitions/v1.0/common.xml

This adds a mavlink command to change the active camera lens (e.g. which camera lens is being streamed to the GCS).  This is useful for cameras with multiple lenses like the ViewPro and Xacti cameras.
ArduPilot already has support for doing this through an auxiliary switch and the corresponding ArduPilot PRs are:
- AP mavlink: https://github.com/ArduPilot/mavlink/pull/351
- AP flightcode: https://github.com/ArduPilot/ardupilot/pull/26172
I think the main question is whether we are happy with the "device id" field which I've modelled after the similar "Gimbal device id" field found in many gimbal related commands and messages including [MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW](https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml#L2109)

common: add set-camera-source command

---

message_definitions/v1.0/common.xml

The fields roll, pitch and yaw of [SIM_STATE message](https://mavlink.io/en/messages/common.html#SIM_STATE) do not specify their unit. Even if the recommended use is only for human-readable outputs, I believe it would be beneficial to have the unit specified.
Reasons for choosing radians:
- angular speeds of the same message are in rad/s
- consistency with ATTITUDE, MANUAL_SETPOINT, LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET, HIL_STATE, [GLOBAL_|VICON_]VISION_POSITION_ESTIMATE
- ArduPilot already sends them as rad (I don't have a PX4 setup ready to confirm)
Other units used for roll and pitch angles in common dialect:
- MAV_CMD_DO_SET_HOME - doesn't refer to attitude, but terrain
- MAV_CMD_DO_MOUNT_CONTROL, MOUNT_ORIENTATION - refers to gimbal and is deprecated, new messages use rad
- …

common: SIM_STATE specify attitude units as rad

---

message_definitions/v1.0/common.xml

This fixes the unit of the tracking "point" radius. My choice is relative to frame width and not pixels because camera and stream might not have the same resolution.

common: trying to make sense of radius unit

---

message_definitions/v1.0/common.xml

The MAV_CMD_DO_FENCE_ENABLE states that it is a mission item, but it can, and is sent as a command. This attempts to clarify the expected behaviour in this case. 
The points of interest being that:
- mission settings persist in the mission context, even on flight stacks that pause by switching mode to "Hold": on return to the mission the mission setting would be used.
- As a command the value only persists until mode change or reboot.
- A command can affect a mission
Originates from discussion with @andyp1per in https://github.com/ArduPilot/mavlink/pull/349#discussion_r1482155395
@sfuhrer @peterbarker Does this makes sense? Is it what is done? That's my assumption on what you'd want to happen but I haven't tested.

DO_FENCE_ENABLE when sent as a command

---

message_definitions/v1.0/common.xml

This adds support for a new "land rejoin" waypoint. This acts as a marker to the autopilot that it can rejoin a mission at any point after this marker and before a landing or MAV_CMD_DO_LAND_START.
AP demo: https://youtu.be/SoHXRTD0vEs?si=pHTvRDMcOsStv4l6
AP PR: https://github.com/ArduPilot/ardupilot/pull/26383

Common: add MAV_CMD_DO_RETURN_PATH_START

---

message_definitions/v1.0/common.xml

`ILLUMINATOR_ERROR_FLAGS` is meant to be bit flags so `ILLUMINATOR_ERROR_FLAGS_THERMISTOR_FAILURE` value should be 4 (bit 2) instead of 3

Fix ILLUMINATOR_ERROR_FLAGS

---

message_definitions/v1.0/common.xml

I don't think anybody actually implements this.
ArduPilot doesn't.
PX4 doesn't seem to.
QGC doesn't seem to
MissionPlanner doesn't.
MAVProxy doesn't

common.xml: deprecate MAV_CMD_SET_PARAMETER

---

message_definitions/v1.0/development.xml

- BATTERY_STATUS_V2.capacity_remaining had impossible invalid value - changed to NaN
- Referred to SMART_BATTERY_INFO which has been renamed to BATTERY_INFO

BATTERY_STATUS_V2 - fix typos

---

.editorconfig
component_metadata/parameter.schema.json
doc/README.md
doc/mavlink_gitbook.py
doc/mavlink_to_html_table.xsl
doc/mavlink_to_html_table_gitbook.xsl
examples/c/udp_example.c
mavgenerate.py
message_definitions/v1.0/all.xml
message_definitions/v1.0/matrixpilot.xml

Add an EditorConfig to make sure editors know how to correctly edit and save files. Also strip trailing whitespace in some files that don't need it, as configured in the EditorConfig file.

style: add EditorConfig and format some files

---

.github/workflows/docs_build_and_deploy.yml
doc/mavlink_xml_to_markdown.py
doc/requirements.txt

The current docs generation toolchain uses XSL conversion of the XML to HTML, followed by some massaging of the produced HTML to produce some final output.
This is very clever and all, but inherently limited for generating docs, because:
1. Files don't know about each other - we can't, for example, create a combined file, even if we want.
2. The output is HTML. That should work in markdown, but rendering is spotty.
So what this does is copy the ideas behind mavgen parser (but using beautifulsoup) to parse the XML into Python, and then generate markdown output. 
This replaces the top level files. 
Includes workflow to build the files, and start of workflow to deploy files. However no point finishing that until the old version is disabled, which depends on CI that relies on Daniel Agar. …

Improved docs from XML generation_toolchain

---

doc/mavlink_xml_to_markdown.py

This PR changes the label for maxValue to be `max` rather than `min`, and also fixes the bug which causes increment to be shown when maxValue is set, even if there's no increment

Fix missing increment and max value typo

---

message_definitions/v1.0/common.xml

This adds id field to allow commands to be sent to a specific camera.
Note, this mirrors the [MAV_CMD_IMAGE_START_CAPTURE](https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_START_CAPTURE)/[MAV_CMD_IMAGE_STOP_CAPTURE](https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_STOP_CAPTURE) commands by setting param1=id where possible, but otherwise would pick a free id.
Don't think we need to do anything for video messages, which use a stream id: `MAV_CMD_VIDEO_START_CAPTURE`,  `MAV_CMD_VIDEO_STOP_CAPTURE`, `MAV_CMD_VIDEO_START_STREAMING`, `MAV_CMD_VIDEO_STOP_STREAMING`
Do we need to modify the information messages, such as [CAMERA_INFORMATION](https://mavlink.io/en/messages/common.html#CAMERA_INFORMATION) ? from:
> [[Message] …

Set camera ids on messages that might have flight-stack attached cameras

---

message_definitions/v1.0/common.xml

We added a `multiplier` attribute to indicate that the value is scaled. The value is the amount you multiply the received value to get the actual value in the specified units (if there are any).
This adds multiplier for eph/epv of 1E-2 and multiplier of `360/255` for satellite_azimuth
Fixes #2062
Related to https://github.com/ArduPilot/pymavlink/pull/885, https://github.com/ArduPilot/pymavlink/pull/894
Docs update in https://github.com/mavlink/mavlink-devguide/pull/540
@shancock884 @peterbarker @julianoes This OK?

common - multiplier values for azimuth and eph/epv

---

message_definitions/v1.0/development.xml

This is a proposal for a message to report fuel levels in a generic way that can be displayed by a GCS, and used for autopilot fuel-level failsafes. Note that ArduPilot simply uses the battery messages fields for this, with the consequence that the values displayed are inaccurate. This message can be used for all sorts of fuels.
The design is similar to the battery messages but has some differences. 
1.  Consumed/remaining levels are _measured_ values or NaN.
Battery messages are designed around power monitors that can only measure consumed charge, and that hence report consumed charge and make an assumption that the battery is full for estimating/providing remaining charge. A smart battery tracks the amounts effectively, so they have a flag there to indicate when the values can be …

FUEL_STATUS message proposal

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

Add fields to report resilience and status information from GNSS receivers back to ground control stations for representation in the user interface.

gps: add status and integrity information

---

message_definitions/v1.0/common.xml

Adds documentation that field `squawk` of `ADSB_VEHICLE` message is encoded in decimal, not in octal.
The ADS-B drivers of PX4 and ArduPilot receive the squawk as octal number, but convert it to decimal when creating the MAVLink `ADSB_VEHICLE` message.
This may come as a surprise to aerospace engineers who tend to interpret Squawk as an octal number. In turn, this can lead to a lack of recognition of emergency statuses (safety issue) or mis-identification of emergency statuses (less critical, but still a safety issue).

ADSB_VEHICLE.squawk octal code is sent as if decimal

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

When taking off in GNSS denied environments with a fixed wing or a VTOL airplane, wind dead-reckoning performance strongly relies on an accurate wind estimate. Since the wind states are not really observable without any velocity / position aiding, it makes sense to allow the operator to externally set the wind states in order to improve dead-reckoning performance.

Added MAV_CMD_EXTERNAL_WIND_ESTIMATE to development

---

doc/README.md
doc/mavlink_xml_to_markdown.py

The multiplier attribute was recently added to XSD. You multiply the value received and the multiplier value to get the actual value sent. This is only defined in a few values currently.
This adds support to messages and commands, such that a new column is added for multiplier if the attribute is used on any field/param.
This came out of this discussion #2124

Add multiplier field to docs, if present

---

message_definitions/v1.0/common.xml

By adding a camera_device_id to a CAMERA_INFORMATION message, we allow an autopilot to be a proxy for a MAVLink or non-MAVLink camera.
The idea is similar to a gimbal manager implemented by an autopilot.
@hamishwillee we likely need it in a few other places and will have to think the edge cases.
This was @rmackay9's idea when trying to figure out how QGC can detect a gimbal that's proxied by the autopilot.
Also see https://github.com/mavlink/qgroundcontrol/pull/11574
An alternative would be for the autopilot to send out heartbeats from two component IDs, something that no one seems to want to do. PX4 doesn't even though it sends out messages as the camera component, and ArduPilot is reluctant to do such a hack. Plus it screws with sequence numbers unless two channels are occupied.

common: add camera_device_id to CAMERA_INFORMATION

---

message_definitions/v1.0/common.xml

Cameras that support H.265 are becoming more common. We need a way to specify the encoding of the video stream.

common.xml: Add "encoding" field to VIDEO_STREAM_INFORMATION

---

doc/mavlink_xml_to_markdown.py

This makes common.xml only display XML entities in full for included files - other dialects only include a heading.
This also improves the heading text for dialects, listing the source repo where known.
There are some that still need to be confirmed.

Docs generation improvements

---

message_definitions/v1.0/common.xml

The docs were rending this item as italic when in markdown as shown. 
> MAV_CMD_DO_SET_ROI (201) — [DEP]
> DEPRECATED: Replaced By MAV*CMD_DO_SET_ROI*\* (2018-01)
This forces the markdown to code. SHould be good because this information is not rendered in the docs from the generators.
Fixes #2136 
@peterbarker Make sense to you?

comment - use markdown in replaced by to fix rendering

---

message_definitions/v1.0/common.xml

This adds a new message to allow sending a thermal camera's min and max temperatures (including the location on the image) to the ground station in real time.  This is useful for search & rescue and firefighting applications because the ground station can overlay a rectangle over the hotspot along with its temperature
I've tried to make it consistent with other CAMERA messages including the tracking message in the hopes that that makes it easier to merge.  I've also included the camera_device_id field consistent with PR https://github.com/mavlink/mavlink/pull/2142
Over on the AP side we've recently been improving our support for thermal cameras including the Siyi ZT6, ZT30 and the Topotek gimbals.  This has been tested on real-hardware using a Siyi ZT6
The equivalent AP PR is here …

common: add camera-thermal-status

---

message_definitions/v1.0/common.xml

This adds parameter details to [MAV_CMD_SET_MESSAGE_INTERVAL](https://mavlink.io/en/messages/common.html#MAV_CMD_SET_MESSAGE_INTERVAL ) to mirror [MAV_CMD_REQUEST_MESSAGE](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_MESSAGE) .
Specifically, request message allows you to get a particular instance of a message. So if you're only interested in the message for Battery_status instance 2 say, then that's the one you'll get. This allows you to do the same thing for intervals, if you're only interested in setting the interval for one thing. Note, I'm not sure you'll ever need this, and it would be a pain to implement, but the facility is there.
Further, you might want to configure other information that decides what values you get back, and this updates the remaining params to be …

MAV_CMD_SET_MESSAGE_INTERVAL - additional params for requestor

---

message_definitions/v1.0/common.xml

Having these two capability flags means that ground stations don't have to ask any discovered components for CAMERA_INFORMATION and GIMBAL_MANAGER_INFORMATION messages and can instead only do so when they see this capability flag set.
This means however, that each ground station now needs to request either AUTOPILOT_VERSION or COMPONENT_INFORMATION_BASIC from any MAVLink component that it discovers, so it's only slightly better.
The alternative would be to make it explicit that cameras and gimbals need to send out CAMERA_CAPTURE_STATUS and GIMBAL_MANAGER_STATUS messages respsectively, to signal implementing a camera/gimbal manager.
FYI @Davidsastresas

common: add capability flags for camera and gimbal

---

doc/mavlink_xml_to_markdown.py

This is a typo. The bolding happens in the method.

mavlink_xml_to_markdown.py - remove unclosed b tag

---

message_definitions/v1.0/common.xml

Similar to #2035
> At some point we decided why put the bitmask entry on the user, when it is a property of the enum. So we have <enum
> name="GIMBAL_MANAGER_FLAGS" bitmask="true">.
> That said, we're inconsistent on this and we should decide if we want one or the other or both.
I personally think it should be explicitly stated in both places for consitency with the existing code as not specifying it breaks some code that depends on these definition files (I am coming from [mavlink/rust-mavlink](https://github.com/mavlink/rust-mavlink/)).
Since however the `ILLUMINATOR_STATUS` message merged in #2047 uses the none-`bitmask` enum `ILLUMINATOR_MODE` as both `bitmask=true` and without it I can see that specifying this should probably be moved to the message field definition consistenly in …

common.xml: GIMBAL_MANAGER_FLAGS display as bitmask

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

Implement basic functionality for a MAV to broadcast information about the current MAVLink component (usually a GCS) in control of it and a new command to request this control. This follows the discussion in https://github.com/mavlink/mavlink/issues/2098, specifically the latest comments @hamishwillee suggested in https://github.com/mavlink/mavlink/issues/2098#issuecomment-2360036137 about the "cannot be taken over bit", as it makes more sense than the previous approach suggested.
A controlled vehicle should only accept MAVLink commands (or command-like messages) that are sent by the controlling GCS, or from other components with the same system id. Commands from other system should be rejected with MAV_RESULT_PERMISSION_DENIED (except for this command, which may be acknowledged with …

development.xml: First prototype for multi-GCS operation.

---

doc/README.md
doc/mavlink_xml_to_markdown.py

The docs for development.xml (say) were displaying full messages/enums/commands for declarations, but only a heading and a link for included entities. Ditto for everything except common.xml, which had full docs for all entities, whether included or not.
This proved a bit hard to use for working out what was the subset you can use everywhere and what you can use in your dialect. I.e. in development you are only interested really in the entities that are risky to use. Even if you're using ardupilotmega.xml it is easier to be able to look at just what is in the file.
Anyway, common.xml stays the same, but everything else no longer displays a heading for included entities.

Docs: Remove the imported headers for everything except common.xml

---

message_definitions/v1.0/common.xml

Based on recommendation to add for CRSF binding
https://github.com/PX4/PX4-Autopilot/pull/23294#issuecomment-2303311359

add rc_type_crsf

---

message_definitions/v1.0/common.xml

`SMART_BATTERY_INFO` was renamed and modified to `BATTERY_INFO` in https://github.com/mavlink/mavlink/pull/2070 on assumption that no smart batteries have been implemented.
As pointed out by @tridge in https://discord.com/channels/899843920987562014/902774723925147649/1305677432224743426 [there are projects that use `SMART_BATTERY_INFO`](https://github.com/search?q=SMART_BATTERY_INFO_send&type=code), so it should have been left in place, deprecated, and the new `BATTERY_INFO` should have had a new ID.
Now none of those projects appear to have noted this change but they might be affected in future. This PR proposes reverting the change and moving BATTERY_INFO up one item.
1. Is this the right thing to do? Is it less disruptive than living with the change: …

[Discussion] SMART_BATTERY_INFO - revert and renumber BATTERY_INFO

---

message_definitions/v1.0/development.xml

It collides with a new command in Ardupilotmega.xml, in Ardupilot repo. See:
https://github.com/ArduPilot/mavlink/blob/4c64b9522f9bb9815b089ab98cf2f33f11bded52/message_definitions/v1.0/ardupilotmega.xml#L344
Is it alright to do this being in development.xml @hamishwillee? Thanks!

development.xml: change OPERATOR_CONTROL id to 43006:

---

message_definitions/v1.0/development.xml

This message and enum was added in 2021 in https://github.com/mavlink/mavlink/pull/1601.
Appears to have no implementation. Need to determine its future.
@aviaks Can you confirm an implementation exists? Do you need this? Note that things in development.xml are "work in progress" which means that the MAVLink team reserve the right to modify or remove them at any time.

WIFI_NETWORK_SECURITY - wip removal

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

FUEL_STATUS was added to development.xml in  #2107 as a better way of reporting fuel than faking it with BATTERY_STATUS.
However there is no evidence of implementation since June 2024, so this is preparation for removing it. Would love to bring it back once someone shows interest.
but no indication of implementation.
FYI, @TSC21 @Pedro-Roque You were original stakeholders in this. Can you confirm that by removing this we won't be harming anyone, and if not, provide evidence the implementation was satisfactory?
Removed items are:
```xml
<enum name="MAV_FUEL_TYPE">
<description>Fuel types for use in FUEL_TYPE. Fuel types specify the units for the maximum, available and consumed fuel, and for the flow rates.</description>
<entry value="0" name="MAV_FUEL_TYPE_UNKNOWN">
<description>Not …
```

dev: move FUEL_STATUS to common

---

message_definitions/v1.0/development.xml

The `MAV_CMD_GROUP_START` and `_END` commands were added in 2021 (https://github.com/mavlink/mavlink/pull/1687) but do not appear to have implementations.
More specifically, there is this unmerged PR here:
- https://github.com/PX4/PX4-Autopilot/pull/18279
Its been more than two years. Have confirmed with @MatejFranceskin that there is no intent at this time to continue implementation. Removing from development.xml.
```xml
<entry value="301" name="MAV_CMD_GROUP_START" hasLocation="false" isDestination="false">
<description>Define start of a group of mission items. When control reaches this command a GROUP_START message is emitted.
The end of a group is marked using MAV_CMD_GROUP_END with the same group id.
Group ids are expected, but not required, to iterate sequentially.
Groups can be …
```

[development.xml] delete MAV_CMD_GROUP_START and _GROUP_END  (no implementation)

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

After some discussions with @hamishwillee and @julianoes, apply folowing fixes:
- Include in one of the request parameters the timeout time: so we can show a "synchronized" indicator both on the requestor GCS, and on the GCS in control. This will control how long a control request is visible before being automatically rejected. See screenshot of current QGC approach under development.
- If the GCS in control ( with takeover not allowed ) accepts allow takeover after a request, have a fixed timeout to re-request control with takeover not allowed, in case the requestor GCS doesn't take control, fixed to 10 seconds. This is used to prevent operators forgetting they allowed takeover for a possible failed ownership change. If requestor GCS doesn't take control before those 10 seconds, GCS in …

Some modifications to multi-GCS protocol

---

message_definitions/v1.0/common.xml

Speed/velocity uncertainty units should be in units of distance/time - right?

Speed uncertainty units mm/s

---

message_definitions/v1.0/ardupilotmega.xml

MAV_CMD_EXTERNAL_POSITION_ESTIMATE was moved from common to xml. However this has not been updated in ArduPilotMega.xml in Ardupilot/mavlink. So when we pulled that in we created a crash.
Undoing that particular change.
@peterbarker Would it be possible to remove MAV_CMD_EXTERNAL_POSITION_ESTIMATE from downstream and pull in the changes where this was copied into common.xml?

ardupilotmega - remove_mav_cmd_external_estimate

---

message_definitions/v1.0/common.xml

This was added in #2145 
It has been deployed in ArduPilot and according to @rmackay9 in https://github.com/mavlink/mavlink/pull/2145#issuecomment-2511342820 
> this is fully baked. We used it very successfully in this year's [Japan Innovation Challenge](https://discuss.ardupilot.org/t/tap-j-at-the-japan-innovation-challenge-2024/125750). The ability to get the real time maximum absolute temperature was critical in this success. There's a pic in the middle of the linked blog post showing what it looked like on Mission Planner when we flew over a dummy.
The API is not as good as you might get by merging metadata in a parallel video stream, but we know that up front. This is very reasonable for what can be done pragmatically with MAVLink.
@julianoes @auturgy ?

CAMERA_THERMAL_RANGE - no longer WIP

---

doc/mavlink_xml_to_markdown.py

This fixes up the generated markdown for XML files to use vitepress notes etc. 
In addition, I'm splitting the sidebar into standard messages and dialects. Right now it is very easy to find common.xml (which is good) but hard to find development.xml and standard, which is not.
The common.xml will still be highlighted, but this will keep the information about the managed files together.

Create index.md, dialects.md and make notes/warning work with vitepress

---

message_definitions/v1.0/development.xml

This merges the standard modes MAV_STANDARD_MODE_RETURN_HOME and STANDARD_MODE_SAFE_RECOVERY  into one mode, and renumbers the mode enum.
The original thinking was that it was useful for a user to know whether the vehicle is performing a smart return or a simple/direct RTL. However generally the user is the person who will have done any off-standard configuration, so they will know the expected behaviour. This won't change unless they change it, so telling them they are doing a smart return or an RTL isn't going to be telling them anything they wouldn't know already.
In addition, discussion during prototyping indicates this may be confusing for users. For example, if they set a smart RTL but the vehicle is configured to RTL then it is unclear whether the vehicle should reject a command to …

Merge STANDARD_MODE_SAFE_RECOVERY and MAV_STANDARD_MODE_RETURN_HOME

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This was added in #1693 but never implemented. This removes it from development.xml to remove the clutter.
The purpose was to allow groups of parameters to be applied atomically. ArduPilot don't need it because they can do this with a file-based system if needed. PX4 have not implemented in 4 years.
XML below so that this can be added back if we need in future. 
```xml
<enum name="PARAM_TRANSACTION_TRANSPORT">
<description>Possible transport layers to set and get parameters via mavlink during a parameter transaction.</description>
<entry value="0" name="PARAM_TRANSACTION_TRANSPORT_PARAM">
<description>Transaction over param transport.</description>
</entry>
<entry value="1" name="PARAM_TRANSACTION_TRANSPORT_PARAM_EXT">
<description>Transaction over param_ext transport.</description> …
```

development: Remove parameter transaction proposal

---

message_definitions/v1.0/common.xml

The message CAMERA_IMAGE_CAPTURED is lacking a camera_device_id but I think we can just use the unused camera_id instead.

common: use camera ID for CAMERA_IMAGE_CAPTURED

---

message_definitions/v1.0/common.xml

This fixes up `PING` to point to TIMESYNC instead of SYSTEM_TIME (obviously) and TIMESYNC to point to the more concreted docs.
Replaces https://github.com/mavlink/mavlink-devguide/pull/585
@julianoes This makes sense to me - can you please sanity check?

common.xml - PING fix

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

Standard modes are now in PX4 v1.15. So no longer in development.
- PX4 is a full-ish implementation of the concept except it omits the vehicle-specific modes. Have asked Beat to do those.
- QGC implements this and you can test this now for PX4 v1.15.
- To test the dynamic modes you have to use daily build and companion computer setup.
Ardupilot PR for same thing: https://github.com/ArduPilot/ardupilot/pull/28566 - 
This moves the relevant messages. 
Corresponding docs work https://github.com/mavlink/mavlink-devguide/pull/557

Standard modes - move to common.xml

---

message_definitions/v1.0/common.xml

AVAILABLE_modes - first sentence had poor grammar/typo. 
This also adds some better cross linking between modes, including a link to the microservice docs
Self merging.

Standard modes - improve cross linking

---

message_definitions/v1.0/development.xml

PR from https://github.com/mavlink/mavlink/pull/2206, should be last bit not all bits.
Added in https://github.com/mavlink/mavlink/pull/1846.
We could also remove it. Its not used and refers to a possible extension that may or may not be added in the future. If we did want to reserve it I think a comment in the xml would serve just as well without having to have unused things in the generated output since we don't support `reserved="true"` for enums entrys.

development: `MAV_BATTERY_STATUS_FLAGS_EXTENDED` correct final bit `MAV_BATTERY_STATUS_FLAGS_EXTENDED`

---

message_definitions/v1.0/common.xml

PR from https://github.com/mavlink/mavlink/pull/2206, the last value includes all bits, so it is not a true bitmask. If you want all you can check all from the existing definitions. Its posible that removing this is not correct, instead maybe it should be `32,768` for just the last bit rather than all bits?
Added in https://github.com/mavlink/mavlink/pull/1643
We do deal with this in AP, but we don't use the MAVLink enum rather defining our own. There we end up doing some funny messing about to set the all bits rather than just or-ing all the other bits together. 
https://github.com/ArduPilot/ardupilot/blob/e5f719b65a7fc30740b285fd656626b476df8de6/libraries/GCS_MAVLink/GCS_Common.cpp#L2239-L2246

common: `HIGHRES_IMU_UPDATED_FLAGS` enum remove `HIGHRES_IMU_UPDATED_ALL` value

---

message_definitions/v1.0/development.xml

Found by https://github.com/mavlink/mavlink/pull/2206. Although embarrassingly this one is my bug in the first place. 
Bitmask should be values, I put in bit numbers. This is implemented in AP, it is doing the bit shift to get the right value, that will have to be removed once this is merged.
https://github.com/ArduPilot/ardupilot/blob/09c8ad81bb1624fb049967ab2987dc0a2aafd0b0/libraries/GCS_MAVLink/GCS_Common.cpp#L2386
https://github.com/ArduPilot/ardupilot/blob/09c8ad81bb1624fb049967ab2987dc0a2aafd0b0/libraries/GCS_MAVLink/GCS_Common.cpp#L2393

development: `AIRSPEED_SENSOR_FLAGS` correct bitmask

---

message_definitions/v1.0/common.xml

Found by https://github.com/mavlink/mavlink/pull/2206. These values are all unnecessary, none of them are referenced by AP.
There are a couple of other 0's in bitmasks in this file, but there not so clear cut, I will PR those individually in the future.

common: remove unneeded 0 values in bitmasks

---

message_definitions/v1.0/common.xml

also point out flag value can be different based on transport
@julianoes whoops.  I completely missed the instances-start-at-zero thing...

common.xml: adjust field instance descriptions

---

message_definitions/v1.0/common.xml

temperature_air now corresponds to the ambient temperature which is not necessarily dependent on the airspeed sensor.
According to the new logic in PX4: https://github.com/PX4/PX4-Autopilot/pull/24272
hierarchy is now:
1. Airspeed temperature
2. External baro
3. Default ambient temperature

Adjust HIGH_LATENCY2 temperature_air field description

---

message_definitions/v1.0/common.xml

Added payload types for ModalAI vendor use for Mavlink tunnel messages.

Added payload types for ModalAI vendor use

---

message_definitions/v1.0/common.xml

There is some confusion about how fence polygons are numbered in param1: https://groups.google.com/g/mavlink/c/S-Z2d9Vyv78/m/W-Lv2CUuAAAJ
Basically my testing (previously) shows that the vertices in a polygon all follow each other in the sequence of a fence, and have the same total vertices count. 
This clarifies the commands.

MAV_CMD_NAV_FENCE_POLYGON_VERTEX_ - numbering info

---

message_definitions/v1.0/common.xml

This adds a mode property to allow a GCS to distinguish between custom auto and manual modes. 
@sfuhrer proposed that this is a flaw for being able to configure the UI, which I think is reasonable.
@sfuhrer @bkueng @julianoes @auturgy @IamPete1 What do you think? We don't make additions unless they are going to be implemented/have a stakeholder. Anyone interested in this in a more than abstract way?

MAV_MODE_PROPERTY for auto/manual distinquishing

---

message_definitions/v1.0/common.xml

This proposes removal of `display="bitmask"` on enum fields that use bitmasks. 
All the corresponding enums that use this are marked up as bitmasks with the attribute `bitmask="true"`, so this information both inferrable and duplicated. The enum should define that it is a bitmask where it is used.
We know that this attribute is not used in QGC or Mission Planner or MAVProxy. It might be used elsewhere, but unlikely.
Downstream dialects fixes

common.xml - remove display="bitmask"

---

message_definitions/v1.0/common.xml

As suggested in https://github.com/mavlink/mavlink/pull/2224#discussion_r1972634931

MAV_CMD_ACTUATOR_TEST: more specific description of response

---

message_definitions/v1.0/development.xml
message_definitions/v1.0/minimal.xml
message_definitions/v1.0/storm32.xml

This removes the last cases of `display="bitmask"` from this repo - in minimal, development.xml and storm. I checked corresponding enums do have the bitmask attribute set.

Remove cases display bitmask

---

message_definitions/v1.0/common.xml

Found by https://github.com/mavlink/mavlink/pull/2220
Adds a full enum rather than trying to enumerate in the description.

common: `HIL_ACTUATOR_CONTROLS` and `HIL_ACTUATOR_CONTROLS_FLAGS` enum

---

message_definitions/v1.0/common.xml

Found by https://github.com/mavlink/mavlink/pull/2206.
This is used in `MAV_CMD_DO_AUTOTUNE_ENABLE`:
https://github.com/mavlink/mavlink/blob/fe18c424e55e8f5e95e2c933d10db03f79c5b09d/message_definitions/v1.0/common.xml#L1782-L1791
A value of 0 is a special case meaning to do the default. This seems reasonable behavior, but it should not be in the bitmask.
This enum is not used by ArduPilot.

common: `AUTOTUNE_AXIS` remove 0 from bitmask

---

message_definitions/v1.0/common.xml

Found by https://github.com/mavlink/mavlink/pull/2206.
The command was removed by https://github.com/mavlink/mavlink/pull/2053 but the enum and reserved spot were overlooked.

common: remove orphaned `FENCE_ACTION` enum and refence to `MAV_CMD_SET_FENCE_BREACH_ACTION`

---

message_definitions/v1.0/common.xml

0 is not a valid shifted bit value
ArduPilot equivalent here: https://github.com/ArduPilot/mavlink/pull/391

common.xml: remove FENCE_TYPE_ALL from FENCE_TYPE enumeration

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/development.xml

This proposes MAV_CMD_SET_GLOBAL_ORIGIN, a replacement for SET_GPS_GLOBAL_ORIGIN. The semantics are command like - the only reason it isn't a command is because it is a very early message.

MAV_CMD_SET_GLOBAL_ORIGIN supersedes SET_GPS_GLOBAL_ORIGIN

---

message_definitions/v1.0/common.xml

Found by https://github.com/mavlink/mavlink/pull/2206. 
This is used in `MAV_CMD_DO_FENCE_ENABLE`:
https://github.com/mavlink/mavlink/blob/fe18c424e55e8f5e95e2c933d10db03f79c5b09d/message_definitions/v1.0/common.xml#L1726-L1741
This one is a little odd. Is a bit-mask but if no bits are set the description says to treat it the same as all bits being set. So 0x00 should be the same behavior as 0xFF. It has to be this way so that 0 works for unset.
But then the first param has a value that results in ignoring the second param (The first param is also a example of a param that should have a enum but is instead enumerated in the description).
Maybe it would be better to invert the bit mask so each bit is a fence to ignore the command for
In conclusion the enum is odd, but I think removing the …

common: `FENCE_TYPE` bitmask clarifications

---

message_definitions/v1.0/development.xml

Tidy MAV_CMD_DO_SET_GLOBAL_ORIGIN to make it clear that should be sent in a COMMAND_INT where frame can be set, but that MAV_FRAME_GLOBAL is "expected" sent in COMMAND_LONG).
This falls out of https://github.com/mavlink/mavlink/pull/2247/files#r2036231744

development.xml - frame for setting the position in MAV_CMD_DO_SET_GLOBAL_ORIGIN

---

.github/workflows/test_and_deploy.yml
message_definitions/v1.0/common.xml

Fix a typo. Is in description so no compat issue. Self merging.
Also updating the workflow so that tests run.

common.xml - typo MISSION_SET_CURRENT not SET_MISSION_CURRENT

---

doc/mavlink_xml_to_markdown.py

The entries in enum field is allowed to be given as dezimals but also as hex-es, like 0x0001, see the mavlink scheme definition. The mavlink_xml_to_markdown.py script however terminates with a ValueError in that case then. 
The issue is related ti using an int() conversion, which per default assumes a base of 10, and for strings like 0x0001 thus raises said error. int() however can be made to auto-determine the base form the given string, by setting the base to 0. This is what this PR does.
The issue apperaed in https://github.com/mavlink/mavlink/pull/2265, where the xml file wants to benefit form using hex calues, but the check fails for the above reason.
I have tested it on my machine that the proposed fix makes mavlink_xml_to_markdown.py to run through fine.
Note: There is another …

doc xml_to_markdown py script, fix for hex enum entries

---

message_definitions/v1.0/storm32.xml

Removes a bad enum entry, which violates that enums which represent bitmasks should have only bit values.
followup to https://github.com/mavlink/mavlink/pull/2265#pullrequestreview-2820107177
sorry for not having realized this earlier.

Update storm32.xml, bitmask enums should only have bit values

---

scripts/update_c_library.sh

Due to the error described in https://github.com/ArduPilot/pymavlink/pull/544, the generated build libraries are sensitive to build order. 
This appears to have caused the error discussed in https://github.com/mavlink/qgroundcontrol/pull/12410 and https://discord.com/channels/1022170275984457759/1362458777835802766
This attempts to fix the build issues by adding the missing libraries. NOTE, that I don't think this should make any difference. Both before and after this the generated libraries for all.xml appear to include the development messages (i.e. by looking at CRCs) but all.xml does not link them.
I think I have found the reason in https://github.com/ArduPilot/pymavlink/pull/544/files#r2069976980

Try fix build order of generated libraries

---

message_definitions/v1.0/all.xml

This adds a dummy command to all.xml. This forces merging of the development/ardupilotmega (and lower) and other peers into the top level all.h file, fixing the problem outlined in https://github.com/ArduPilot/pymavlink/pull/544/files#r2069976980
Note this would still potentially miss other merged enums.
The original and allcom (with commands) is shown below. This does show at least the development.xml and ardupilotmega.xml commands are indeed now present at the top level. 
[mavlink_allcom.zip](https://github.com/user-attachments/files/20033784/mavlink_allcom.zip)
@julianoes @peterbarker This is clearly "more right" than what we had. Peter can you suggest words you'd like for that all.xml command entry?

Add dummy command to all.xml to force merging in commands from lower levels

---

message_definitions/v1.0/common.xml

I'm proposing to change the unit of DO_REPOSITION param4, which is used for the yaw setpoint for multirotors.
Currently, the spec specifies degrees, however, PX4 implements it as radians:
- https://github.com/PX4/PX4-Autopilot/blob/fee575f944191546c0d8ab1845db7cfc676f60f4/src/modules/navigator/navigator_main.cpp#L318
- https://github.com/PX4/PX4-Autopilot/blob/fee575f944191546c0d8ab1845db7cfc676f60f4/msg/PositionSetpoint.msg#L25
And so did MAVSDK until I fixed it by accident:
- https://github.com/mavlink/MAVSDK/pull/2562/files
But I have to revert:
- https://github.com/mavlink/MAVSDK/pull/2567
ArduPilot seems to ignore param4, so we should not be breaking anything, if I read this right:
- https://github.com/ArduPilot/ardupilot/blob/384f0ffa6a2230bcb2d3beca7468a3a147958a6a/ArduCopter/GCS_MA …

common: change unit of DO_REPOSITION yaw

---

message_definitions/v1.0/common.xml

This is proposal following discussion in https://github.com/mavlink/mavlink/issues/2186
This changes the continuous zoom and focus from a value of +1/0/1 to a range [-1..0..+1], allowing control over the rate of change for cameras that support it.
On existing GCS setup the values of -1, 0, 1 _should_ be sent which will have the same behaviour.
@peterbarker @julianoes Does this make sense to you? We were considering having another enum value for this, but doesn't seem necessary.
FYI @nrd8

common.xml - ZOOM_TYPE, FOCUS_TYPE continuous

---

message_definitions/v1.0/common.xml

This PR documents the existing behavior of param6 in MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN. While this parameter is already supported by multiple autopilot implementations, its intended values and behavior are currently not described in the MAVLink specification.
Specifically:
REBOOT_SHUTDOWN_ALLOWED: reboot only if allowed by safety checks REBOOT_SHUTDOWN_FORCE: force reboot, bypassing all safety checks

MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN use of param6

---

message_definitions/v1.0/common.xml

The use of SYSTEM_TIME was inferred but not stated. This updates it following the changes in https://github.com/PX4/PX4-Autopilot/pull/24807
Is there a rate at which this should nominally be streamed, or should it be requested by a flight stack or anything else that wants to know the time?
How does this relate to use of [TIME_SYNC](https://mavlink.io/en/services/timesync.html#time-synchronization-protocol-v2). I mean if everything sets itself to the time in this is TIME_SYNC needed? Should you first do SYSTEM_TIME then time_sync? etc.
@dakejahl @peterbarker Thoughts?

common.xml-SYSTEM_TIME detail

---

message_definitions/v1.0/minimal.xml

Add a generic quadruped ground rover type to describe robots that are not well described by existing types. This type is meant to describe robots such as the Boston Dynamics Spot or Unitree Go2.

Add Generic 4 Legged Quadruped Rover

---

message_definitions/v1.0/common.xml

The two trajectory representation messages are no longer supported in PX4, and hence not in any flight stack.
The messages can meet certain use case so they are not "bad" but they don't meet the criteria for being in common.xml any more. This marks the messages as deprecated to make it clear that they are on the path for removal.
Corresponding changes made to docs in https://github.com/mavlink/mavlink-devguide/pull/593 (accidentally already merged). I'll unmerge that if there are any objections to this.
Note discussed/agreed in mav call.

TRAJECTORY_REPRESENTATION_ - deprecated

---

doc/mavlink_xml_to_markdown.py

This PR corrects a logic error where `minValue` was mistakenly added to `parent.fieldnames` instead of `maxValue`. Now, `maxValue` is correctly tracked when set.

Fix incorrect field name assignment from minValue to maxValue

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/minimal.xml

This remove references to `MAV_MODE` and replaces them with `MAV_MODE_FLAG`. `MAV_MODE` is a enum with a subset of combinations for the `MAV_MODE_FLAG` bitmask. Treating it like a enum where only the given values are accepted just leads to confusion.
Really I would like to remove `MAV_MODE` altogether, the information is redundant. This does leave it in and mentions it in the `MAV_MODE` description.
This also removes a reference to `MAV_NAV_MODE` because it doesn't exist.

Replace `MAV_MODE` with `MAV_MODE_FLAG`.

---

message_definitions/v1.0/common.xml

This adds flags to `MAV_DO_REPOSITION_FLAGS`  enum for relative yaw. The enum is used in:
`MAV_CMD_DO_REPOSITION` 
I don't have a fantastically important use case here, but it was useful for a project and we have values free in the enum. 
https://github.com/ArduPilot/ardupilot/pull/30190

common: DO_REPOSITION: support relative yaw

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/storm32.xml

Follow up to https://github.com/mavlink/mavlink/pull/2241 a few regressions have crept in, found by https://github.com/mavlink/mavlink/pull/2220
All enums are marked as bitmasks:
https://github.com/mavlink/mavlink/blob/81c0901153695d7db5077330a47408fae585e794/message_definitions/v1.0/minimal.xml#L219
https://github.com/mavlink/mavlink/blob/81c0901153695d7db5077330a47408fae585e794/message_definitions/v1.0/common.xml#L5261
https://github.com/mavlink/mavlink/blob/81c0901153695d7db5077330a47408fae585e794/message_definitions/v1.0/storm32.xml#L232

remove display="bitmask"

---

message_definitions/v1.0/common.xml

The description of the field is truncated because of the pipes in the table. 
This fixes the problem by escaping the pipes and marking the whole block as code. 
I tried initially just to block it in code, but that didn't work (though it should have). I also tried using  `&vert` for the pipe, but that didn't render properly either.
TO

Fix camera information firmware version

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/standard.xml

The [script shows a bunch of things](https://github.com/mavlink/mavlink/pull/2220#issue-2856311358) that might reasonably be enums rather than text stating values. Our current rule is that we only bother with an enum if there are more than three items.
That said, there are quite a few cases where we have a command that enables something or disables something by setting a value to 1 or 0. Sometimes these cause us problems because implementers decide to implement them as greater than or less than 0.5, which makes later extension impossible. If we use a generic enum then we force 0 or 1 for the values.
This adds a `BOOLEAN` enum with values `BOOLEAN_TRUE` and `BOOLEAN_FALSE` in standard.xml, and then updates a few cases with the enum instead of max/min/increment. 
What I'm after here is a …

[DISCUSSION] Add BOOLEAN enum for true/false cases

---

doc/mavlink_xml_to_markdown.py

https://docs.astral.sh/ruff/rules/useless-object-inheritance
% `ruff check --select=UP004 --fix`
```
Found 10 errors (10 fixed, 0 remaining).
```

Remove useless Python object inheritance

---

mavgenerate.py

% `ruff check --select=E703 --fix`
```
Found 5 errors (5 fixed, 0 remaining).
```
% `ruff rule E703`
Derived from the **pycodestyle** linter.
Fix is always available.
Checks for statements that end with an unnecessary semicolon.
A trailing semicolon is unnecessary and should be removed.
```python
do_four();  # useless semicolon
```
Use instead:
```python
do_four()
```

useless-semicolon: ruff check --select=E703 --fix

---

message_definitions/v1.0/all.xml
message_definitions/v1.0/marsh.xml

For the past few years, I have been contributing to a research flight simulator in [FRAME-Lab](https://www.aero.polimi.it/en/research-labs/frame-lab-fixed-and-rotary-wing-aircraft-multidisciplinary-eng) at [Department of Aerospace Science and Technology](https://www.aero.polimi.it/) of Politecnico di Milano, I would like to get our local dialect upstream primarily to simplify the usage for my colleagues. I believe it to be fairly mature and stable at this point, but there may be minor changes in the upcoming few months.
The name MARSH stands for "Modular Architecture for Reconfigurable Simulation of Helicopters". The project has detailed documentation at https://marsh-sim.github.io/, but TLDR is that MAVLink precisely defined a lot of things I needed to build a helicopter simulator, and …

MARSH dialect for crewed flight simulators 

---

mavgenerate.py
ruff.toml
scripts/xml_consistency_check.py

% `ruff check --select=E711,E712,F841 --statistics`
```
11	E711	none-comparison
1	E712	true-false-comparison
1	F841	unused-variable
Found 13 errors.
No fixes available (13 hidden fixes can be enabled with the `--unsafe-fixes` option).
```
% `ruff rule E711`
[ ... ]
According to [PEP 8], "Comparisons to singletons like None should always be done with
`is` or `is not`, never the equality operators."
[ ... ]

Fix ruff rules E711,E712,F841

---

message_definitions/v1.0/common.xml

@hamishwillee These are in production use for 7 years now. There are implementations for both multicopter and fixed-wing in PX4 and QGC and the message must be kept compatible.

common: remove wip tag from MAV_CMD_DO_ORBIT and ORBIT_EXECUTION_STATUS

---

message_definitions/v1.0/development.xml

Used for an auxiliary global position sensor such as a map matching sensor.

Add GLOBAL_POSITION message

---

.github/workflows/test_and_deploy.yml

[`codespell`](https://pypi.org/project/codespell/) passes on all files, not just these four.

Typos: Run codespell on all files

---

message_definitions/v1.0/minimal.xml

Add 3 new component IDs in the `MAV_COMPONENT` enum:
- `MAV_COMP_ID_RADIO=110, /* Radio #1. | */`
- `MAV_COMP_ID_RADIO2=111, /* Radio #2. | */`
- `MAV_COMP_ID_RADIO3=112, /* Radio #3. | */`
Use the space between `MAV_COMP_ID_CAMERA6=105` and `MAV_COMP_ID_SERVO1=140` because it leaves a big gap in between in case we need to add new values in the future.
The primary use of the new IDs is for setups where you connect multiple radios between the airframe and GCS.
Ex: low bandwidth radio + high bandwidth radio
The IDs can be used to identify the different `RADIO_STATUS` messages coming from each individual radio.

Add new component IDs for multiple radios

---

message_definitions/v1.0/common.xml

Tracking algorithms can track a target through obscuration (e.g. a vehicle going under a bridge or a drone going behind a tree) by predicting the position of the target and re-acquiring the track when it is visible again. The common term for this is coasting. This PR adds a `COASTING` flag to `CAMERA_TRACKING_STATUS_FLAGS` to report when this occurs.
Extends #2323.

common.xml: Add COASTING flag to CAMERA_TRACKING_STATUS_FLAGS

---

message_definitions/v1.0/common.xml
message_definitions/v1.0/standard.xml

This moves `GLOBAL_POSITION_INT` from common to standard.
It is identical in PX4 and ArduPilot repos, and supported by both (FYI emitted by both simulators for copter at rates 4 (apm), 50Hz (PX4).
@peterbarker Any objections? FYI @julianoes @auturgy

GLOBAL_POSITION_INT - move from common to standard

---

message_definitions/v1.0/common.xml

Following up discussion in https://github.com/mavlink/mavlink-devguide/pull/625#issuecomment-3195105682.
I'm not sure if this is a valid way of creating a link here, but the XML resources I found suggested adding the XLink namespace, which I didn't understand well enough to be inclined to try it (especially if it then adds an online requirement to currently offline things). Hopefully this is ok as-is, but happy to update it to some other syntax, or just "link" by mentioning the protocol name, if that's preferable.

common.xml: link MANUAL_CONTROL message to its protocol

---

message_definitions/v1.0/common.xml

allows an error regarding parameter sub-protocol to be passed around
Talking point only, let's not merge it *right now*...

common.xml: add PARAM_ERROR message
